<a href="https://colab.research.google.com/github/freida20git/bird-detection-tracking/blob/main/model_on_videos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

testing inference of bestbirdspnly.pt on multiple videos compared to yolo11n and yolo11m

In [1]:
!gdown --folder "https://drive.google.com/drive/folders/1k6zdJ7NJX8lAgpqBogU346DZoiPj-CO5"
!gdown --folder "https://drive.google.com/drive/folders/1lPxmAk2Akj-ELYQ7_9tSIkyaokVhivvE"

Retrieving folder contents
Processing file 1fSmfgg1vQLNtKAKbdy71LWpK6D2MY5rL birds_beach_856799-hd_1920_1080_25fps.mp4
Processing file 1Zgbc8oewMAAQe7-FLi5Z6IsNlcpnJ3fN birds_sky.mp4
Processing file 1zJuJDol52GsPvuTpgZMmqkA0Hp7JUnFe desert_birds_4438487-uhd_3840_2160_24fps.mp4
Processing file 1nQHp1ze49jPNC0lgUY7yMV5NOBBwTC3i oclusion_birds_2927931-uhd_4096_2160_24fps.mp4
Processing file 1XGeddfek_Q21YUW5OwZgS9QUR5c6NY-S similar_birds_8824697-uhd_3840_2160_30fps.mp4
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1fSmfgg1vQLNtKAKbdy71LWpK6D2MY5rL
To: /content/videos /birds_beach_856799-hd_1920_1080_25fps.mp4
100% 5.65M/5.65M [00:00<00:00, 35.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Zgbc8oewMAAQe7-FLi5Z6IsNlcpnJ3fN
To: /content/videos /birds_sky.mp4
100% 5.23M/5.23M [00:00<00:00, 113MB/s]
Downloading...
From: https://drive.google.com/uc?id=1zJuJDol52GsPvuTpgZMmqkA0Hp7JUnFe
To: /content/videos /desert_birds_4438487-uhd_3840_2160_24fps.mp4
100% 86.5M/86.5M [00:00<00:00, 130MB/s]
Downloading...
From: https://drive.google.com/uc?id=1nQHp1ze49jPNC0lgUY7yMV5NOBBwTC3i
To: /content/videos /oclusion_birds_2927931-uhd_4096_2160_24fps.mp4
100% 22.2M/22.2M [00:00<00:00, 60.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1XGeddfek_Q21YUW5OwZgS9QUR5c6NY-S
To: /content/videos /similar_birds_8824697-uhd_3840_2160_30fps.mp4
100% 24.8M/24.8M [00:00<00:00, 79.4MB/s]
Download completed
Retrieving folder contents
Processing file 1ygrd2vWBXFfv-Wk9nQEwMb3DoG3Azqcq gt_birds_beach.json
Processing file 157mAI9K596GzangljcEMmpgtXIzHQgto gt_birds_sky.json
Processing file 18wOPOmKm6xirr-b30_X9GT6ZViz0rthT gt_desert_birds.json
Processing file 1dMIE8rFKd8p8eLamXYF7rVuUs_2_7bJH gt_occlusion_birds.json
Processing file 1ictdbXQ7efG6RUoL9qMnBG_wcSt8VGQ_ gt_similar_birds.json
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1ygrd2vWBXFfv-Wk9nQEwMb3DoG3Azqcq
To: /content/ground truth/gt_birds_beach.json
100% 151k/151k [00:00<00:00, 66.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=157mAI9K596GzangljcEMmpgtXIzHQgto
To: /content/ground truth/gt_birds_sky.json
100% 355k/355k [00:00<00:00, 95.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=18wOPOmKm6xirr-b30_X9GT6ZViz0rthT
To: /content/ground truth/gt_desert_birds.json
100% 371k/371k [00:00<00:00, 99.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1dMIE8rFKd8p8eLamXYF7rVuUs_2_7bJH
To: /content/ground truth/gt_occlusion_birds.json
100% 173k/173k [00:00<00:00, 70.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ictdbXQ7efG6RUoL9qMnBG_wcSt8VGQ_
To: /content/ground truth/gt_similar_birds.json
100% 322k/322k [00:00<00:00, 118MB/s]
Download completed

In [34]:
!git clone https://github.com/freida20git/bird-detection-tracking.git

Cloning into 'bird-detection-tracking'...
remote: Enumerating objects: 119, done.
remote: Counting objects: 100% (119/119), done.
remote: Compressing objects: 100% (114/114), done.
remote: Total 119 (delta 54), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (119/119), 43.99 MiB | 13.63 MiB/s, done.
Resolving deltas: 100% (54/54), done.

# ***Its suggested to use the full pipeline function under "Generalized function":***

#installations and imports:

In [14]:
# pre OCSORT installations:
!git clone https://github.com/noahcao/OC_SORT.git
!cd OC_SORT
!pip3 install -r /content/OC_SORT/requirements.txt
!python3 setup.py develop
!apt-get install -y build-essential
!pip install cython
!pip install lap
!pip install filterpy
!pip install ultralytics
# make sure the ocsort object file exists:
!ls /content/OC_SORT/trackers/ocsort_tracker
!pip install motmetrics

Cloning into 'OC_SORT'...
remote: Enumerating objects: 554, done.
remote: Counting objects: 100% (150/150), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 554 (delta 86), reused 67 (delta 67), pack-reused 404 (from 2)
Receiving objects: 100% (554/554), 45.40 MiB | 31.35 MiB/s, done.
Resolving deltas: 100% (210/210), done.
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from -r /content/OC_SORT/requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: torch>=1.7 in /usr/local/lib/python3.11/dist-packages (from -r /content/OC_SORT/requirements.txt (line 3)) (2.6.0+cu124)
Requirement already satisfied: opencv_python in /usr/local/lib/python3.11/dist-packages (from -r /content/OC_SORT/requirements.txt (line 4)) (4.11.0.86)
Collecting loguru (from -r /content/OC_SORT/requirements.txt (line 5))
  Using cached loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.11/dist-packages (from -r /content/OC_SORT/requirements.txt (line 6)) (0.25.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from -r /content/OC_SORT/requirements.txt (line 7)) (4.67.1)
Requirement already satisfied: torchvision>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from -r /content/OC_SORT/requirements.txt (line 8)) (0.21.0+cu124)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from -r /content/OC_SORT/requirements.txt (line 9)) (11.2.1)
Collecting thop (from -r /content/OC_SORT/requirements.txt (line 10))
  Using cached thop-0.1.1.post2209072238-py3-none-any.whl.metadata (2.7 kB)
Collecting ninja (from -r /content/OC_SORT/requirements.txt (line 11))
  Using cached ninja-1.11.1.4-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: tabulate in /usr/local/lib/python3.11/dist-packages (from -r /content/OC_SORT/requirements.txt (line 12)) (0.9.0)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.11/dist-packages (from -r /content/OC_SORT/requirements.txt (line 13)) (2.18.0)
Requirement already satisfied: lap in /usr/local/lib/python3.11/dist-packages (from -r /content/OC_SORT/requirements.txt (line 14)) (0.5.12)
Requirement already satisfied: filterpy in /usr/local/lib/python3.11/dist-packages (from -r /content/OC_SORT/requirements.txt (line 16)) (1.4.5)
Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from -r /content/OC_SORT/requirements.txt (line 17)) (3.14.0)
Collecting onnx==1.8.1 (from -r /content/OC_SORT/requirements.txt (line 20))
  Using cached onnx-1.8.1.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.8.0 (from versions: 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.17.0, 1.17.1, 1.17.3, 1.18.0, 1.18.1, 1.19.0, 1.19.2, 1.20.0, 1.20.1, 1.21.0, 1.21.1, 1.22.0)
ERROR: No matching distribution found for onnxruntime==1.8.0
python3: can't open file '/content/setup.py': [Errno 2] No such file or directory
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
Requirement already satisfied: cython in /usr/local/lib/python3.11/dist-packages (3.0.12)
Requirement already satisfied: lap in /usr/local/lib/python3.11/dist-packages (0.5.12)
Requirement already satisfied: numpy>=1.21.6 in /usr/local/lib/python3.11/dist-packages (from lap) (2.0.2)
Requirement already satisfied: filterpy in /usr/local/lib/python3.11/dist-packages (1.4.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from filterpy) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from filterpy) (1.15.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from filterpy) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->filterpy) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->filterpy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->filterpy) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->filterpy) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->filterpy) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->filterpy) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->filterpy) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->filterpy) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->filterpy) (1.17.0)
Requirement already satisfied: ultralytics in /usr/local/lib/python3.11/dist-packages (8.3.158)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (4.11.0.86)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (11.2.1)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (6.0.2)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.32.3)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (1.15.3)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.6.0+cu124)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (0.21.0+cu124)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.11/dist-packages (from ultralytics) (9.0.0)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.2.2)
Requirement already satisfied: ultralytics-thop>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.0.14)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.4->ultralytics) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.4->ultralytics) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2025.6.15)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (4.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.2)
association.py	kalmanfilter.py  ocsort.py
Requirement already satisfied: motmetrics in /usr/local/lib/python3.11/dist-packages (1.4.0)
Requirement already satisfied: numpy>=1.12.1 in /usr/local/lib/python3.11/dist-packages (from motmetrics) (2.0.2)
Requirement already satisfied: pandas>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from motmetrics) (2.2.2)
Requirement already satisfied: scipy>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from motmetrics) (1.15.3)
Requirement already satisfied: xmltodict>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from motmetrics) (0.14.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.23.1->motmetrics) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.23.1->motmetrics) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.23.1->motmetrics) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.23.1->motmetrics) (1.17.0)

In [8]:
'''
import sys
sys.path.append('/content/OC_SORT/trackers')  # <- Add *this* path
from ocsort_tracker.ocsort import OCSort  # <- Update import

tracker = OCSort(det_thresh=0.5)
print("OCSort loaded successfully!")
'''

OCSort loaded successfully!

In [15]:
import cv2
import numpy as np
import json
from ultralytics import YOLO
import random
import cv2
import torch
import ultralytics
ultralytics.checks()
from ultralytics import YOLO
from IPython.display import Image
from collections import defaultdict
import numpy as np
import motmetrics as mm
import pandas as pd
import json
import json
from pathlib import Path
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval

Ultralytics 8.3.158 🚀 Python-3.11.13 torch-2.6.0+cu124 CPU (Intel Xeon 2.20GHz)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 41.9/107.7 GB disk)

In [39]:
import sys
sys.path.append('/content/bird-detection-tracking')

from func_ocsort import run_ocsort_save_json
from Tracking_metrics_functions import *


'''
def convert_to_coco(data, is_gt=True, frame_width=None, frame_height=None)
def convert_json_to_mot(json_path, output_path)
def compute_tracking_metrics(gt_file, pred_file)
def map_calc_coco(gt_json_path, pred_json_path, video_path)
get_video_resolution(...)
convert_to_coco_gt(...)
convert_predictions_to_coco(...)

'''

'\ndef convert_to_coco(data, is_gt=True, frame_width=None, frame_height=None)\ndef convert_json_to_mot(json_path, output_path)\ndef compute_tracking_metrics(gt_file, pred_file)\ndef map_calc_coco(gt_json_path, pred_json_path, video_path)\nget_video_resolution(...)\nconvert_to_coco_gt(...)\nconvert_predictions_to_coco(...)\n\n'

# runing inference on 5 videos 3 models:

**yolo11n:**

In [23]:
model =YOLO("yolo11n.pt")

In [26]:
run_ocsort_save_json(model, "/content/videos /birds_sky.mp4", "output_birds_sky.mp4", "birds_sky_results.json")
convert_json_to_mot("/content/ground truth/gt_birds_sky.json", "/content/birds_sky_gt.txt")
convert_json_to_mot("birds_sky_results.json", "birds_sky_results.txt")
compute_tracking_metrics("/content/birds_sky_gt.txt", "birds_sky_results.txt")

map_5095, map_50 = map_calc_coco(
    gt_json_path="/content/ground truth/gt_birds_sky.json",
    pred_json_path="/content/birds_sky_results.json",
    video_path="/content/videos /birds_sky.mp4"
)

print(f"mAP@0.50: {map_50:.4f}")
print(f"mAP@0.50:0.95: {map_5095:.4f}")

0: 384x640 6 birds, 403.3ms
Speed: 21.7ms preprocess, 403.3ms inference, 40.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 185.2ms
Speed: 16.1ms preprocess, 185.2ms inference, 2.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 155.3ms
Speed: 7.0ms preprocess, 155.3ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 149.5ms
Speed: 7.3ms preprocess, 149.5ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 167.3ms
Speed: 15.0ms preprocess, 167.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 132.5ms
Speed: 6.8ms preprocess, 132.5ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 138.0ms
Speed: 4.7ms preprocess, 138.0ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 133.5ms
Speed: 4.9ms preprocess, 133.5ms inference, 2.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 230.7ms
Speed: 4.7ms preprocess, 230.7ms inference, 2.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 209.3ms
Speed: 4.7ms preprocess, 209.3ms inference, 2.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 birds, 211.6ms
Speed: 10.4ms preprocess, 211.6ms inference, 2.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 birds, 203.3ms
Speed: 4.5ms preprocess, 203.3ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 195.1ms
Speed: 5.1ms preprocess, 195.1ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 196.2ms
Speed: 6.7ms preprocess, 196.2ms inference, 2.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 195.0ms
Speed: 6.1ms preprocess, 195.0ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 177.6ms
Speed: 4.4ms preprocess, 177.6ms inference, 2.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 188.4ms
Speed: 4.6ms preprocess, 188.4ms inference, 3.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 177.8ms
Speed: 4.3ms preprocess, 177.8ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 211.0ms
Speed: 7.0ms preprocess, 211.0ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 114.8ms
Speed: 4.0ms preprocess, 114.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 116.9ms
Speed: 4.3ms preprocess, 116.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 119.0ms
Speed: 4.3ms preprocess, 119.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 122.3ms
Speed: 4.0ms preprocess, 122.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 116.7ms
Speed: 4.2ms preprocess, 116.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 133.5ms
Speed: 5.1ms preprocess, 133.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 117.3ms
Speed: 3.9ms preprocess, 117.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 119.0ms
Speed: 4.0ms preprocess, 119.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 120.5ms
Speed: 4.1ms preprocess, 120.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 115.0ms
Speed: 4.3ms preprocess, 115.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 113.2ms
Speed: 4.3ms preprocess, 113.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 117.2ms
Speed: 4.2ms preprocess, 117.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 119.0ms
Speed: 4.3ms preprocess, 119.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 133.2ms
Speed: 5.0ms preprocess, 133.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 132.7ms
Speed: 5.1ms preprocess, 132.7ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 139.7ms
Speed: 4.7ms preprocess, 139.7ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 130.7ms
Speed: 7.0ms preprocess, 130.7ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 132.4ms
Speed: 4.8ms preprocess, 132.4ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 138.0ms
Speed: 4.7ms preprocess, 138.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 119.3ms
Speed: 4.4ms preprocess, 119.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 122.2ms
Speed: 4.1ms preprocess, 122.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 119.3ms
Speed: 4.1ms preprocess, 119.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 115.8ms
Speed: 4.5ms preprocess, 115.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 119.3ms
Speed: 4.2ms preprocess, 119.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 128.3ms
Speed: 4.4ms preprocess, 128.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 126.0ms
Speed: 4.2ms preprocess, 126.0ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 128.3ms
Speed: 5.1ms preprocess, 128.3ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 130.7ms
Speed: 4.8ms preprocess, 130.7ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 5 birds, 136.6ms
Speed: 4.3ms preprocess, 136.6ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 136.2ms
Speed: 4.4ms preprocess, 136.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 1 kite, 165.1ms
Speed: 4.5ms preprocess, 165.1ms inference, 7.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 141.3ms
Speed: 4.7ms preprocess, 141.3ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 1 kite, 137.2ms
Speed: 5.1ms preprocess, 137.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 131.4ms
Speed: 4.8ms preprocess, 131.4ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 128.8ms
Speed: 4.9ms preprocess, 128.8ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 141.0ms
Speed: 4.4ms preprocess, 141.0ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 birds, 144.0ms
Speed: 7.1ms preprocess, 144.0ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 133.4ms
Speed: 4.9ms preprocess, 133.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 124.9ms
Speed: 4.7ms preprocess, 124.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 130.3ms
Speed: 4.4ms preprocess, 130.3ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 133.8ms
Speed: 4.6ms preprocess, 133.8ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 133.5ms
Speed: 4.3ms preprocess, 133.5ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 140.5ms
Speed: 7.2ms preprocess, 140.5ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 121.0ms
Speed: 4.4ms preprocess, 121.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 117.0ms
Speed: 4.1ms preprocess, 117.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 120.1ms
Speed: 4.9ms preprocess, 120.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 123.5ms
Speed: 4.1ms preprocess, 123.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 120.1ms
Speed: 3.9ms preprocess, 120.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 130.8ms
Speed: 3.9ms preprocess, 130.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 132.1ms
Speed: 4.8ms preprocess, 132.1ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 136.4ms
Speed: 4.7ms preprocess, 136.4ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 132.4ms
Speed: 5.0ms preprocess, 132.4ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 127.4ms
Speed: 6.0ms preprocess, 127.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 129.5ms
Speed: 5.5ms preprocess, 129.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 143.4ms
Speed: 6.3ms preprocess, 143.4ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 126.0ms
Speed: 4.6ms preprocess, 126.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 128.4ms
Speed: 4.8ms preprocess, 128.4ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 130.0ms
Speed: 4.4ms preprocess, 130.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 130.7ms
Speed: 4.7ms preprocess, 130.7ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 160.7ms
Speed: 4.4ms preprocess, 160.7ms inference, 2.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 221.4ms
Speed: 4.4ms preprocess, 221.4ms inference, 2.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 210.8ms
Speed: 5.8ms preprocess, 210.8ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 204.6ms
Speed: 4.2ms preprocess, 204.6ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 215.6ms
Speed: 4.1ms preprocess, 215.6ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 201.1ms
Speed: 7.3ms preprocess, 201.1ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 5 birds, 202.1ms
Speed: 6.7ms preprocess, 202.1ms inference, 2.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 193.6ms
Speed: 4.9ms preprocess, 193.6ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 211.1ms
Speed: 4.9ms preprocess, 211.1ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 222.3ms
Speed: 4.5ms preprocess, 222.3ms inference, 2.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 233.8ms
Speed: 6.6ms preprocess, 233.8ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 126.8ms
Speed: 4.9ms preprocess, 126.8ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 129.0ms
Speed: 9.1ms preprocess, 129.0ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 128.3ms
Speed: 4.4ms preprocess, 128.3ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 131.2ms
Speed: 3.9ms preprocess, 131.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 124.8ms
Speed: 4.5ms preprocess, 124.8ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 115.3ms
Speed: 4.2ms preprocess, 115.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 114.8ms
Speed: 4.2ms preprocess, 114.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 118.7ms
Speed: 4.3ms preprocess, 118.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 115.4ms
Speed: 4.0ms preprocess, 115.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 117.9ms
Speed: 4.5ms preprocess, 117.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 129.0ms
Speed: 4.3ms preprocess, 129.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 117.9ms
Speed: 4.0ms preprocess, 117.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 125.8ms
Speed: 3.7ms preprocess, 125.8ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 118.0ms
Speed: 4.3ms preprocess, 118.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 119.3ms
Speed: 5.0ms preprocess, 119.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 119.2ms
Speed: 4.4ms preprocess, 119.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 116.8ms
Speed: 4.3ms preprocess, 116.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 126.9ms
Speed: 4.7ms preprocess, 126.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 114.3ms
Speed: 4.3ms preprocess, 114.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 114.9ms
Speed: 4.2ms preprocess, 114.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 117.7ms
Speed: 4.3ms preprocess, 117.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 116.3ms
Speed: 4.4ms preprocess, 116.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 115.0ms
Speed: 4.4ms preprocess, 115.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 3 kites, 129.0ms
Speed: 4.0ms preprocess, 129.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1 kite, 113.5ms
Speed: 5.7ms preprocess, 113.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 117.7ms
Speed: 3.7ms preprocess, 117.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 114.2ms
Speed: 4.2ms preprocess, 114.2ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 118.8ms
Speed: 4.3ms preprocess, 118.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 114.0ms
Speed: 3.9ms preprocess, 114.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 128.1ms
Speed: 4.9ms preprocess, 128.1ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 144.9ms
Speed: 5.0ms preprocess, 144.9ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 124.5ms
Speed: 4.9ms preprocess, 124.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 125.2ms
Speed: 4.7ms preprocess, 125.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 128.9ms
Speed: 4.5ms preprocess, 128.9ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 124.4ms
Speed: 4.5ms preprocess, 124.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 131.6ms
Speed: 5.5ms preprocess, 131.6ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 143.2ms
Speed: 4.4ms preprocess, 143.2ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 132.9ms
Speed: 4.6ms preprocess, 132.9ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 126.2ms
Speed: 4.8ms preprocess, 126.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 129.5ms
Speed: 4.6ms preprocess, 129.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 122.5ms
Speed: 4.7ms preprocess, 122.5ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 125.9ms
Speed: 4.6ms preprocess, 125.9ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 140.4ms
Speed: 4.5ms preprocess, 140.4ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 135.4ms
Speed: 4.6ms preprocess, 135.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 130.5ms
Speed: 4.6ms preprocess, 130.5ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 130.3ms
Speed: 4.4ms preprocess, 130.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 126.9ms
Speed: 4.7ms preprocess, 126.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 124.4ms
Speed: 4.6ms preprocess, 124.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 133.7ms
Speed: 5.1ms preprocess, 133.7ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 123.4ms
Speed: 4.2ms preprocess, 123.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 117.3ms
Speed: 4.2ms preprocess, 117.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1 clock, 118.4ms
Speed: 4.5ms preprocess, 118.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1 clock, 119.3ms
Speed: 4.4ms preprocess, 119.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1 clock, 122.3ms
Speed: 4.2ms preprocess, 122.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1 clock, 131.1ms
Speed: 5.2ms preprocess, 131.1ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1 clock, 151.0ms
Speed: 4.4ms preprocess, 151.0ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 134.9ms
Speed: 6.8ms preprocess, 134.9ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 130.3ms
Speed: 4.8ms preprocess, 130.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 131.7ms
Speed: 4.5ms preprocess, 131.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 129.6ms
Speed: 4.5ms preprocess, 129.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 122.4ms
Speed: 4.2ms preprocess, 122.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 162.4ms
Speed: 4.5ms preprocess, 162.4ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 174.9ms
Speed: 3.9ms preprocess, 174.9ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 182.7ms
Speed: 5.4ms preprocess, 182.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 181.2ms
Speed: 3.9ms preprocess, 181.2ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 194.0ms
Speed: 7.0ms preprocess, 194.0ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 182.4ms
Speed: 4.7ms preprocess, 182.4ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 185.9ms

In [ ]:
run_ocsort_save_json(model, "similar_birds.mp4", "output_similar_birds.mp4", "similar_birds_results.json",  OCSort(
    det_thresh=0.4,
    max_age=50,
    min_hits=4,
    iou_threshold=0.3,
    delta_t=3,
    inertia=0.4,
    asso_func="iou"
))
convert_json_to_mot("/content/annotations_gt_SB.json", "/content/annotations_gt_SB.txt")
convert_json_to_mot("similar_birds_results.json", "similar_birds_results.txt")
compute_tracking_metrics("annotations_gt_SB.txt", "similar_birds_results.txt")

0: 384x640 5 airplanes, 120.2ms
Speed: 4.2ms preprocess, 120.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 127.0ms
Speed: 4.8ms preprocess, 127.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 133.2ms
Speed: 4.5ms preprocess, 133.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 132.9ms
Speed: 4.4ms preprocess, 132.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 133.7ms
Speed: 4.9ms preprocess, 133.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 airplanes, 1 bird, 128.9ms
Speed: 4.5ms preprocess, 128.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 131.2ms
Speed: 5.0ms preprocess, 131.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 3 birds, 135.0ms
Speed: 4.3ms preprocess, 135.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 146.0ms
Speed: 4.3ms preprocess, 146.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 131.5ms
Speed: 4.6ms preprocess, 131.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 4 birds, 132.7ms
Speed: 4.5ms preprocess, 132.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 5 birds, 135.6ms
Speed: 4.4ms preprocess, 135.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 3 birds, 137.7ms
Speed: 4.3ms preprocess, 137.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 4 birds, 136.5ms
Speed: 4.5ms preprocess, 136.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 130.5ms
Speed: 4.5ms preprocess, 130.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 133.2ms
Speed: 4.5ms preprocess, 133.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 4 birds, 130.6ms
Speed: 4.4ms preprocess, 130.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 4 birds, 144.0ms
Speed: 4.6ms preprocess, 144.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 132.3ms
Speed: 4.3ms preprocess, 132.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 134.1ms
Speed: 4.4ms preprocess, 134.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 128.7ms
Speed: 4.4ms preprocess, 128.7ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 airplanes, 133.6ms
Speed: 4.3ms preprocess, 133.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 airplanes, 133.1ms
Speed: 4.1ms preprocess, 133.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 airplanes, 130.8ms
Speed: 4.3ms preprocess, 130.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 airplanes, 130.8ms
Speed: 5.9ms preprocess, 130.8ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 airplanes, 131.9ms
Speed: 4.6ms preprocess, 131.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 145.5ms
Speed: 4.3ms preprocess, 145.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 128.1ms
Speed: 4.3ms preprocess, 128.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 3 birds, 133.8ms
Speed: 4.4ms preprocess, 133.8ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 3 birds, 130.9ms
Speed: 4.4ms preprocess, 130.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 5 birds, 148.9ms
Speed: 5.9ms preprocess, 148.9ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 193.5ms
Speed: 6.9ms preprocess, 193.5ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 4 birds, 208.5ms
Speed: 4.3ms preprocess, 208.5ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 5 birds, 201.5ms
Speed: 4.9ms preprocess, 201.5ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 3 birds, 217.3ms
Speed: 6.1ms preprocess, 217.3ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 210.0ms
Speed: 10.5ms preprocess, 210.0ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 195.3ms
Speed: 13.5ms preprocess, 195.3ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 205.0ms
Speed: 4.2ms preprocess, 205.0ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 135.2ms
Speed: 6.5ms preprocess, 135.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 133.9ms
Speed: 4.1ms preprocess, 133.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 128.0ms
Speed: 4.4ms preprocess, 128.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 145.5ms
Speed: 5.7ms preprocess, 145.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 127.3ms
Speed: 4.5ms preprocess, 127.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 airplanes, 137.8ms
Speed: 4.3ms preprocess, 137.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 131.8ms
Speed: 4.6ms preprocess, 131.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 132.1ms
Speed: 4.3ms preprocess, 132.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 134.6ms
Speed: 4.2ms preprocess, 134.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 2 birds, 134.6ms
Speed: 4.7ms preprocess, 134.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 4 birds, 132.9ms
Speed: 4.6ms preprocess, 132.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 5 birds, 133.3ms
Speed: 4.4ms preprocess, 133.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 149.7ms
Speed: 4.8ms preprocess, 149.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 5 birds, 140.0ms
Speed: 4.5ms preprocess, 140.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 135.3ms
Speed: 5.1ms preprocess, 135.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 134.5ms
Speed: 5.5ms preprocess, 134.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 137.7ms
Speed: 4.6ms preprocess, 137.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 135.9ms
Speed: 4.5ms preprocess, 135.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 131.6ms
Speed: 4.5ms preprocess, 131.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 5 birds, 144.7ms
Speed: 5.6ms preprocess, 144.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 135.0ms
Speed: 4.4ms preprocess, 135.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 151.1ms
Speed: 5.8ms preprocess, 151.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 135.8ms
Speed: 4.6ms preprocess, 135.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 137.5ms
Speed: 4.5ms preprocess, 137.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 134.7ms
Speed: 5.1ms preprocess, 134.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 airplanes, 149.3ms
Speed: 4.4ms preprocess, 149.3ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 airplanes, 1 bird, 138.0ms
Speed: 4.4ms preprocess, 138.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 142.5ms
Speed: 5.1ms preprocess, 142.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 136.3ms
Speed: 4.5ms preprocess, 136.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 134.8ms
Speed: 4.5ms preprocess, 134.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 149.8ms
Speed: 7.0ms preprocess, 149.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 137.9ms
Speed: 5.5ms preprocess, 137.9ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 134.6ms
Speed: 4.5ms preprocess, 134.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 4 birds, 137.9ms
Speed: 5.0ms preprocess, 137.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 150.2ms
Speed: 4.5ms preprocess, 150.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 136.3ms
Speed: 4.4ms preprocess, 136.3ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 8 birds, 135.6ms
Speed: 4.7ms preprocess, 135.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 5 birds, 133.3ms
Speed: 4.6ms preprocess, 133.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 4 birds, 132.2ms
Speed: 4.5ms preprocess, 132.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 146.1ms
Speed: 6.1ms preprocess, 146.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 139.4ms
Speed: 4.5ms preprocess, 139.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 138.5ms
Speed: 4.5ms preprocess, 138.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 134.6ms
Speed: 4.5ms preprocess, 134.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 221.2ms
Speed: 4.4ms preprocess, 221.2ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 213.8ms
Speed: 4.7ms preprocess, 213.8ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 236.0ms
Speed: 6.4ms preprocess, 236.0ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 222.1ms
Speed: 4.5ms preprocess, 222.1ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 218.4ms
Speed: 5.9ms preprocess, 218.4ms inference, 2.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 202.4ms
Speed: 4.6ms preprocess, 202.4ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 234.1ms
Speed: 4.4ms preprocess, 234.1ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 137.9ms
Speed: 11.5ms preprocess, 137.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 132.3ms
Speed: 4.4ms preprocess, 132.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 140.4ms
Speed: 5.9ms preprocess, 140.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 4 birds, 159.5ms
Speed: 4.4ms preprocess, 159.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 4 birds, 134.7ms
Speed: 4.7ms preprocess, 134.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 136.0ms
Speed: 5.1ms preprocess, 136.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 136.0ms
Speed: 4.7ms preprocess, 136.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 4 birds, 142.3ms
Speed: 4.6ms preprocess, 142.3ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 4 birds, 137.0ms
Speed: 6.2ms preprocess, 137.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 4 birds, 131.9ms
Speed: 8.6ms preprocess, 131.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 136.3ms
Speed: 4.4ms preprocess, 136.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 137.7ms
Speed: 4.4ms preprocess, 137.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 3 birds, 146.6ms
Speed: 6.9ms preprocess, 146.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 2 birds, 136.1ms
Speed: 4.8ms preprocess, 136.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 140.8ms
Speed: 4.5ms preprocess, 140.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 135.4ms
Speed: 4.4ms preprocess, 135.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 152.5ms
Speed: 4.5ms preprocess, 152.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 136.9ms
Speed: 4.7ms preprocess, 136.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 139.2ms
Speed: 4.5ms preprocess, 139.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 130.4ms
Speed: 4.6ms preprocess, 130.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 3 birds, 137.7ms
Speed: 5.3ms preprocess, 137.7ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 3 birds, 151.6ms
Speed: 4.2ms preprocess, 151.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 5 birds, 132.4ms
Speed: 4.6ms preprocess, 132.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 2 birds, 139.3ms
Speed: 4.5ms preprocess, 139.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 3 birds, 140.0ms
Speed: 4.8ms preprocess, 140.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 6 birds, 150.6ms
Speed: 4.4ms preprocess, 150.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 134.6ms
Speed: 4.4ms preprocess, 134.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 137.2ms
Speed: 4.8ms preprocess, 137.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 131.6ms
Speed: 4.5ms preprocess, 131.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 140.0ms
Speed: 4.7ms preprocess, 140.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 138.2ms
Speed: 4.6ms preprocess, 138.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 133.1ms
Speed: 4.5ms preprocess, 133.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 132.3ms
Speed: 4.6ms preprocess, 132.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 139.0ms
Speed: 4.6ms preprocess, 139.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 157.5ms
Speed: 4.9ms preprocess, 157.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 134.5ms
Speed: 4.5ms preprocess, 134.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 2 birds, 143.7ms
Speed: 4.8ms preprocess, 143.7ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 140.8ms
Speed: 4.5ms preprocess, 140.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 2 birds, 149.6ms
Speed: 4.5ms preprocess, 149.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 132.0ms
Speed: 4.5ms preprocess, 132.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 142.4ms
Speed: 4.6ms preprocess, 142.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 138.9ms
Speed: 4.4ms preprocess, 138.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 3 birds, 169.9ms
Speed: 4.5ms preprocess, 169.9ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 198.7ms
Speed: 4.4ms preprocess, 198.7ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 228.2ms
Speed: 4.5ms preprocess, 228.2ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 4 birds, 204.4ms
Speed: 8.6ms preprocess, 204.4ms inference, 5.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 3 birds, 196.1ms
Speed: 4.4ms preprocess, 196.1ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 3 birds, 203.0ms
Speed: 8.4ms preprocess, 203.0ms inference, 2.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 3 birds, 218.1ms
Speed: 6.2ms preprocess, 218.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 2 birds, 203.2ms
Speed: 6.7ms preprocess, 203.2ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 2 birds, 139.4ms
Speed: 4.4ms preprocess, 139.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 2 birds, 135.1ms
Speed: 4.4ms preprocess, 135.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 3 birds, 138.3ms
Speed: 6.2ms preprocess, 138.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 141.8ms
Speed: 4.5ms preprocess, 141.8ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 140.4ms
Speed: 4.7ms preprocess, 140.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 136.3ms
Speed: 4.8ms preprocess, 136.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 139.6ms
Speed: 4.6ms preprocess, 139.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 5 birds, 154.6ms
Speed: 4.7ms preprocess, 154.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)


              idf1      mota      motp  num_switches
Tracking  0.480213  0.790073  0.466668            35

In [ ]:
run_ocsort_save_json(model, "/content/oclusion_birds.mp4", "output_oclusion_birds.mp4", "oclusion_birds_results.json")
convert_json_to_mot("/content/occlusion_birds_gt.json", "/content/occlusion_birds_gt.txt")
convert_json_to_mot("oclusion_birds_results.json", "oclusion_birds_results.txt")
compute_tracking_metrics("/content/occlusion_birds_gt.txt", "oclusion_birds_results.txt")

0: 352x640 1 airplane, 195.5ms
Speed: 4.7ms preprocess, 195.5ms inference, 2.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 191.9ms
Speed: 7.6ms preprocess, 191.9ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 191.1ms
Speed: 5.1ms preprocess, 191.1ms inference, 1.9ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 203.6ms
Speed: 4.0ms preprocess, 203.6ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 200.6ms
Speed: 6.4ms preprocess, 200.6ms inference, 2.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 187.8ms
Speed: 3.7ms preprocess, 187.8ms inference, 1.9ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 115.0ms
Speed: 4.4ms preprocess, 115.0ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 137.7ms
Speed: 4.2ms preprocess, 137.7ms inference, 1.5ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 117.4ms
Speed: 4.0ms preprocess, 117.4ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 119.4ms
Speed: 4.1ms preprocess, 119.4ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 117.1ms
Speed: 4.4ms preprocess, 117.1ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 118.5ms
Speed: 4.2ms preprocess, 118.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 119.7ms
Speed: 4.0ms preprocess, 119.7ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 121.6ms
Speed: 4.5ms preprocess, 121.6ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 121.0ms
Speed: 3.9ms preprocess, 121.0ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 116.6ms
Speed: 4.4ms preprocess, 116.6ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 126.7ms
Speed: 4.0ms preprocess, 126.7ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 113.7ms
Speed: 4.0ms preprocess, 113.7ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 133.0ms
Speed: 4.2ms preprocess, 133.0ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 116.6ms
Speed: 4.2ms preprocess, 116.6ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 123.8ms
Speed: 4.1ms preprocess, 123.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 119.8ms
Speed: 3.8ms preprocess, 119.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 117.8ms
Speed: 4.0ms preprocess, 117.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 119.6ms
Speed: 4.5ms preprocess, 119.6ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 117.5ms
Speed: 4.6ms preprocess, 117.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 118.7ms
Speed: 4.2ms preprocess, 118.7ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 116.2ms
Speed: 4.0ms preprocess, 116.2ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 122.3ms
Speed: 4.1ms preprocess, 122.3ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 119.3ms
Speed: 3.9ms preprocess, 119.3ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 2 birds, 133.1ms
Speed: 4.1ms preprocess, 133.1ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 118.9ms
Speed: 4.2ms preprocess, 118.9ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 116.0ms
Speed: 4.0ms preprocess, 116.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 115.5ms
Speed: 4.0ms preprocess, 115.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 124.6ms
Speed: 4.0ms preprocess, 124.6ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 116.3ms
Speed: 3.9ms preprocess, 116.3ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 128.2ms
Speed: 3.8ms preprocess, 128.2ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 120.2ms
Speed: 4.2ms preprocess, 120.2ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 117.4ms
Speed: 3.8ms preprocess, 117.4ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 119.8ms
Speed: 4.1ms preprocess, 119.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 119.0ms
Speed: 4.0ms preprocess, 119.0ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 132.0ms
Speed: 3.9ms preprocess, 132.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 123.0ms
Speed: 3.5ms preprocess, 123.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 114.5ms
Speed: 4.1ms preprocess, 114.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 120.1ms
Speed: 4.1ms preprocess, 120.1ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 123.2ms
Speed: 4.2ms preprocess, 123.2ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 120.8ms
Speed: 4.2ms preprocess, 120.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 133.8ms
Speed: 4.0ms preprocess, 133.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 119.4ms
Speed: 4.6ms preprocess, 119.4ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 118.3ms
Speed: 4.0ms preprocess, 118.3ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 4 airplanes, 119.9ms
Speed: 4.3ms preprocess, 119.9ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 116.7ms
Speed: 4.0ms preprocess, 116.7ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 130.1ms
Speed: 4.1ms preprocess, 130.1ms inference, 1.9ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 117.0ms
Speed: 4.0ms preprocess, 117.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 120.8ms
Speed: 4.0ms preprocess, 120.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 116.6ms
Speed: 3.9ms preprocess, 116.6ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 118.5ms
Speed: 3.9ms preprocess, 118.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 116.3ms
Speed: 4.3ms preprocess, 116.3ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 141.2ms
Speed: 4.2ms preprocess, 141.2ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 115.8ms
Speed: 6.1ms preprocess, 115.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 163.5ms
Speed: 4.0ms preprocess, 163.5ms inference, 1.8ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 178.6ms
Speed: 4.0ms preprocess, 178.6ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 208.7ms
Speed: 4.1ms preprocess, 208.7ms inference, 2.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 172.2ms
Speed: 4.1ms preprocess, 172.2ms inference, 1.8ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 189.2ms
Speed: 11.3ms preprocess, 189.2ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 173.2ms
Speed: 7.9ms preprocess, 173.2ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 188.8ms
Speed: 4.1ms preprocess, 188.8ms inference, 2.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 181.7ms
Speed: 4.2ms preprocess, 181.7ms inference, 2.8ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 187.1ms
Speed: 4.1ms preprocess, 187.1ms inference, 1.9ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 kite, 122.8ms
Speed: 4.3ms preprocess, 122.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 1 kite, 116.8ms
Speed: 4.4ms preprocess, 116.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 132.3ms
Speed: 5.9ms preprocess, 132.3ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 kites, 117.3ms
Speed: 4.4ms preprocess, 117.3ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 120.3ms
Speed: 4.2ms preprocess, 120.3ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 kites, 117.1ms
Speed: 4.0ms preprocess, 117.1ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 kites, 121.1ms
Speed: 3.9ms preprocess, 121.1ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 kite, 135.3ms
Speed: 4.1ms preprocess, 135.3ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 kites, 115.5ms
Speed: 7.0ms preprocess, 115.5ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 kite, 124.7ms
Speed: 4.2ms preprocess, 124.7ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 kite, 113.8ms
Speed: 4.0ms preprocess, 113.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 kite, 116.4ms
Speed: 4.1ms preprocess, 116.4ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 120.0ms
Speed: 4.4ms preprocess, 120.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 128.0ms
Speed: 4.1ms preprocess, 128.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 118.9ms
Speed: 3.9ms preprocess, 118.9ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 121.4ms
Speed: 4.1ms preprocess, 121.4ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 116.0ms
Speed: 4.2ms preprocess, 116.0ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 birds, 119.9ms
Speed: 6.2ms preprocess, 119.9ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 3 birds, 114.2ms
Speed: 3.9ms preprocess, 114.2ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 birds, 121.3ms
Speed: 3.8ms preprocess, 121.3ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 112.8ms
Speed: 3.8ms preprocess, 112.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 120.8ms
Speed: 4.1ms preprocess, 120.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 118.5ms
Speed: 3.9ms preprocess, 118.5ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 118.3ms
Speed: 4.0ms preprocess, 118.3ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 131.1ms
Speed: 4.1ms preprocess, 131.1ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 119.7ms
Speed: 4.6ms preprocess, 119.7ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 116.9ms
Speed: 4.6ms preprocess, 116.9ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 119.4ms
Speed: 4.3ms preprocess, 119.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 113.3ms
Speed: 4.1ms preprocess, 113.3ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 120.0ms
Speed: 3.7ms preprocess, 120.0ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 137.1ms
Speed: 4.0ms preprocess, 137.1ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 1 kite, 125.7ms
Speed: 4.0ms preprocess, 125.7ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 114.2ms
Speed: 4.0ms preprocess, 114.2ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 123.7ms
Speed: 4.1ms preprocess, 123.7ms inference, 1.7ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 120.1ms
Speed: 4.1ms preprocess, 120.1ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 119.0ms
Speed: 4.3ms preprocess, 119.0ms inference, 1.9ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 124.7ms
Speed: 4.0ms preprocess, 124.7ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 117.6ms
Speed: 4.2ms preprocess, 117.6ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 121.7ms
Speed: 3.9ms preprocess, 121.7ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 115.6ms
Speed: 4.0ms preprocess, 115.6ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 116.9ms
Speed: 3.9ms preprocess, 116.9ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 132.9ms
Speed: 3.9ms preprocess, 132.9ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 116.9ms
Speed: 4.1ms preprocess, 116.9ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 121.4ms
Speed: 4.1ms preprocess, 121.4ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 116.9ms
Speed: 4.0ms preprocess, 116.9ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 118.5ms
Speed: 4.2ms preprocess, 118.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 116.6ms
Speed: 4.4ms preprocess, 116.6ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 122.7ms
Speed: 4.2ms preprocess, 122.7ms inference, 1.5ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 121.8ms
Speed: 4.1ms preprocess, 121.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 120.3ms
Speed: 4.1ms preprocess, 120.3ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 116.8ms
Speed: 4.1ms preprocess, 116.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 117.2ms
Speed: 4.1ms preprocess, 117.2ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 135.9ms
Speed: 4.1ms preprocess, 135.9ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 119.1ms
Speed: 4.3ms preprocess, 119.1ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 168.6ms
Speed: 4.1ms preprocess, 168.6ms inference, 1.8ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 174.2ms
Speed: 4.1ms preprocess, 174.2ms inference, 1.8ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 191.9ms
Speed: 4.1ms preprocess, 191.9ms inference, 2.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 176.6ms
Speed: 6.0ms preprocess, 176.6ms inference, 1.8ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 171.7ms
Speed: 4.2ms preprocess, 171.7ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 166.9ms
Speed: 7.3ms preprocess, 166.9ms inference, 1.7ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 177.4ms
Speed: 4.1ms preprocess, 177.4ms inference, 1.9ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 185.8ms
Speed: 4.1ms preprocess, 185.8ms inference, 1.9ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 184.7ms
Speed: 3.7ms preprocess, 184.7ms inference, 1.9ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 182.1ms
Speed: 6.1ms preprocess, 182.1ms inference, 2.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 117.6ms
Speed: 4.0ms preprocess, 117.6ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 136.7ms
Speed: 4.0ms preprocess, 136.7ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 117.9ms
Speed: 3.7ms preprocess, 117.9ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 118.0ms
Speed: 4.0ms preprocess, 118.0ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 119.8ms
Speed: 4.1ms preprocess, 119.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 115.6ms
Speed: 4.0ms preprocess, 115.6ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 119.7ms
Speed: 4.1ms preprocess, 119.7ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 129.7ms
Speed: 4.0ms preprocess, 129.7ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 119.9ms
Speed: 4.0ms preprocess, 119.9ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 113.3ms
Speed: 4.0ms preprocess, 113.3ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 130.6ms
Speed: 4.1ms preprocess, 130.6ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 126.2ms
Speed: 4.3ms preprocess, 126.2ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 129.7ms
Speed: 4.0ms preprocess, 129.7ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 120.3ms
Speed: 4.3ms preprocess, 120.3ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 119.0ms
Speed: 4.3ms preprocess, 119.0ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 121.4ms
Speed: 4.1ms preprocess, 121.4ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 123.3ms
Speed: 3.9ms preprocess, 123.3ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 122.8ms
Speed: 4.1ms preprocess, 122.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 151.2ms
Speed: 4.0ms preprocess, 151.2ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 114.4ms

              idf1      mota      motp  num_switches
Tracking  0.677558  0.762903  0.199847            18

In [ ]:
run_ocsort_save_json(model, "/content/birds_beach.mp4", "output_birds_beach.mp4", "birds_beach_results.json")

convert_json_to_mot("birds_beach_results.json", "birds_beach_results.txt") # bb
convert_json_to_mot("/content/bb_gt_output.json", "/content/bb_gt_output.txt") # bb gt

compute_tracking_metrics("/content/bb_gt_output.txt", "birds_beach_results.txt") #compare

0: 384x640 2 birds, 112.1ms
Speed: 5.5ms preprocess, 112.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 112.0ms
Speed: 4.1ms preprocess, 112.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 108.3ms
Speed: 4.1ms preprocess, 108.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 123.2ms
Speed: 4.3ms preprocess, 123.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 111.6ms
Speed: 3.7ms preprocess, 111.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 111.7ms
Speed: 4.2ms preprocess, 111.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 110.2ms
Speed: 3.7ms preprocess, 110.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 114.4ms
Speed: 3.7ms preprocess, 114.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 109.7ms
Speed: 4.4ms preprocess, 109.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 109.9ms
Speed: 4.1ms preprocess, 109.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 121.7ms
Speed: 5.1ms preprocess, 121.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 107.0ms
Speed: 4.2ms preprocess, 107.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 110.6ms
Speed: 4.2ms preprocess, 110.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 109.5ms
Speed: 3.9ms preprocess, 109.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 113.1ms
Speed: 3.6ms preprocess, 113.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 109.1ms
Speed: 3.6ms preprocess, 109.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 110.3ms
Speed: 3.8ms preprocess, 110.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 123.4ms
Speed: 3.6ms preprocess, 123.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 2 birds, 110.0ms
Speed: 3.7ms preprocess, 110.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 110.1ms
Speed: 3.6ms preprocess, 110.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 110.3ms
Speed: 3.7ms preprocess, 110.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 111.5ms
Speed: 3.6ms preprocess, 111.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 113.1ms
Speed: 3.6ms preprocess, 113.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 111.7ms
Speed: 3.7ms preprocess, 111.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 125.1ms
Speed: 3.7ms preprocess, 125.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 112.0ms
Speed: 4.0ms preprocess, 112.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 113.2ms
Speed: 4.8ms preprocess, 113.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 114.2ms
Speed: 4.5ms preprocess, 114.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 118.1ms
Speed: 4.4ms preprocess, 118.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 110.9ms
Speed: 3.9ms preprocess, 110.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 110.4ms
Speed: 3.7ms preprocess, 110.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 141.9ms
Speed: 3.8ms preprocess, 141.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 168.2ms
Speed: 7.6ms preprocess, 168.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 174.9ms
Speed: 4.0ms preprocess, 174.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 171.6ms
Speed: 4.1ms preprocess, 171.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 168.1ms
Speed: 4.1ms preprocess, 168.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 167.7ms
Speed: 6.4ms preprocess, 167.7ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 164.3ms
Speed: 3.9ms preprocess, 164.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 170.3ms
Speed: 6.3ms preprocess, 170.3ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 168.0ms
Speed: 9.1ms preprocess, 168.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 187.0ms
Speed: 5.0ms preprocess, 187.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 182.0ms
Speed: 4.1ms preprocess, 182.0ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 158.0ms
Speed: 7.2ms preprocess, 158.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 109.0ms
Speed: 4.5ms preprocess, 109.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 109.7ms
Speed: 4.1ms preprocess, 109.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 113.1ms
Speed: 4.2ms preprocess, 113.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 124.0ms
Speed: 4.1ms preprocess, 124.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 112.2ms
Speed: 4.4ms preprocess, 112.2ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 109.9ms
Speed: 4.1ms preprocess, 109.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 109.5ms
Speed: 4.2ms preprocess, 109.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 110.0ms
Speed: 4.7ms preprocess, 110.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 109.9ms
Speed: 4.4ms preprocess, 109.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 109.0ms
Speed: 4.3ms preprocess, 109.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 123.8ms
Speed: 4.3ms preprocess, 123.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 112.6ms
Speed: 4.0ms preprocess, 112.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 115.5ms
Speed: 3.8ms preprocess, 115.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 110.5ms
Speed: 3.8ms preprocess, 110.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 107.7ms
Speed: 3.9ms preprocess, 107.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 110.4ms
Speed: 4.1ms preprocess, 110.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 108.9ms
Speed: 4.5ms preprocess, 108.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 123.1ms
Speed: 4.0ms preprocess, 123.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 111.4ms
Speed: 3.9ms preprocess, 111.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 2 birds, 113.7ms
Speed: 3.9ms preprocess, 113.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 110.3ms
Speed: 4.3ms preprocess, 110.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 112.0ms
Speed: 3.6ms preprocess, 112.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 111.2ms
Speed: 4.1ms preprocess, 111.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 110.6ms
Speed: 3.6ms preprocess, 110.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 122.7ms
Speed: 3.6ms preprocess, 122.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 111.9ms
Speed: 4.0ms preprocess, 111.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 112.3ms
Speed: 4.5ms preprocess, 112.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 108.1ms
Speed: 4.0ms preprocess, 108.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 110.2ms
Speed: 4.3ms preprocess, 110.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 108.4ms
Speed: 4.2ms preprocess, 108.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 109.6ms
Speed: 4.1ms preprocess, 109.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 122.7ms
Speed: 4.0ms preprocess, 122.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 112.9ms
Speed: 3.9ms preprocess, 112.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 110.3ms
Speed: 3.9ms preprocess, 110.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 109.4ms
Speed: 3.7ms preprocess, 109.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 111.6ms
Speed: 3.6ms preprocess, 111.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 110.8ms
Speed: 3.6ms preprocess, 110.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 109.9ms
Speed: 3.7ms preprocess, 109.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 124.0ms
Speed: 3.6ms preprocess, 124.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 112.8ms
Speed: 4.1ms preprocess, 112.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 109.0ms
Speed: 4.0ms preprocess, 109.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 115.7ms
Speed: 4.4ms preprocess, 115.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 111.3ms
Speed: 3.7ms preprocess, 111.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 110.4ms
Speed: 3.8ms preprocess, 110.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 116.2ms
Speed: 3.6ms preprocess, 116.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 124.6ms
Speed: 4.0ms preprocess, 124.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 109.8ms
Speed: 4.1ms preprocess, 109.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 111.0ms
Speed: 4.0ms preprocess, 111.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 113.3ms
Speed: 5.4ms preprocess, 113.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 107.5ms
Speed: 4.4ms preprocess, 107.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 109.7ms
Speed: 4.5ms preprocess, 109.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 111.4ms
Speed: 4.1ms preprocess, 111.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 115.6ms
Speed: 4.0ms preprocess, 115.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 108.1ms
Speed: 4.0ms preprocess, 108.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 109.5ms
Speed: 4.2ms preprocess, 109.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 108.4ms
Speed: 4.3ms preprocess, 108.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 109.1ms
Speed: 4.2ms preprocess, 109.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 108.8ms
Speed: 4.5ms preprocess, 108.8ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 111.8ms
Speed: 4.3ms preprocess, 111.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 113.0ms
Speed: 4.2ms preprocess, 113.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 110.6ms
Speed: 3.9ms preprocess, 110.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 111.1ms
Speed: 4.1ms preprocess, 111.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 115.2ms
Speed: 4.4ms preprocess, 115.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 115.4ms
Speed: 4.0ms preprocess, 115.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 110.5ms
Speed: 4.5ms preprocess, 110.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 109.9ms
Speed: 4.1ms preprocess, 109.9ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 141.6ms
Speed: 7.0ms preprocess, 141.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 167.0ms
Speed: 4.5ms preprocess, 167.0ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 172.6ms
Speed: 4.1ms preprocess, 172.6ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 165.3ms
Speed: 4.6ms preprocess, 165.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 180.7ms
Speed: 6.6ms preprocess, 180.7ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 162.3ms
Speed: 4.4ms preprocess, 162.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 166.7ms
Speed: 4.3ms preprocess, 166.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 165.0ms
Speed: 4.1ms preprocess, 165.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 164.9ms
Speed: 4.2ms preprocess, 164.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 180.8ms
Speed: 4.1ms preprocess, 180.8ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 173.4ms
Speed: 6.2ms preprocess, 173.4ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 127.9ms
Speed: 4.2ms preprocess, 127.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 2 birds, 109.9ms
Speed: 4.8ms preprocess, 109.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 110.1ms
Speed: 4.2ms preprocess, 110.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 112.9ms
Speed: 4.1ms preprocess, 112.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 123.4ms
Speed: 3.9ms preprocess, 123.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 106.3ms
Speed: 4.1ms preprocess, 106.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 108.8ms
Speed: 4.2ms preprocess, 108.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 109.9ms
Speed: 3.9ms preprocess, 109.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 107.0ms
Speed: 4.2ms preprocess, 107.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 110.4ms
Speed: 4.5ms preprocess, 110.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 111.9ms
Speed: 3.9ms preprocess, 111.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 122.2ms
Speed: 4.2ms preprocess, 122.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 111.0ms
Speed: 3.9ms preprocess, 111.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 111.0ms
Speed: 3.9ms preprocess, 111.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 109.9ms
Speed: 3.8ms preprocess, 109.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 111.3ms
Speed: 3.7ms preprocess, 111.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 112.9ms
Speed: 3.7ms preprocess, 112.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 112.8ms
Speed: 3.8ms preprocess, 112.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 125.3ms
Speed: 3.7ms preprocess, 125.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 110.4ms
Speed: 4.0ms preprocess, 110.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 106.5ms
Speed: 4.1ms preprocess, 106.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 110.8ms
Speed: 4.2ms preprocess, 110.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 111.2ms
Speed: 4.1ms preprocess, 111.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 114.2ms
Speed: 3.9ms preprocess, 114.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 110.7ms
Speed: 4.0ms preprocess, 110.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 123.4ms
Speed: 3.8ms preprocess, 123.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 108.2ms
Speed: 3.9ms preprocess, 108.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 109.4ms
Speed: 3.7ms preprocess, 109.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 3 birds, 109.9ms
Speed: 3.8ms preprocess, 109.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 109.6ms
Speed: 3.7ms preprocess, 109.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 111.9ms
Speed: 4.4ms preprocess, 111.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 108.9ms
Speed: 7.1ms preprocess, 108.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 120.8ms
Speed: 4.0ms preprocess, 120.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 107.7ms
Speed: 4.0ms preprocess, 107.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 109.5ms
Speed: 3.9ms preprocess, 109.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 110.6ms
Speed: 3.9ms preprocess, 110.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 113.0ms
Speed: 4.0ms preprocess, 113.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 112.9ms

              idf1     mota     motp  num_switches
Tracking  0.803197  0.74122  0.73417            31

In [ ]:
run_ocsort_save_json(model, "/content/desert_birds.mp4", "output_desert_birds.mp4", "desert_birds_results.json")
convert_json_to_mot("desert_birds_results.json", "desert_birds_results.txt")
convert_json_to_mot("/content/gt_desert_annotations.json", "/content/gt_desert_annotations.txt")
compute_tracking_metrics("/content/gt_desert_annotations.txt", "desert_birds_results.txt")

0: 384x640 5 birds, 121.4ms
Speed: 4.1ms preprocess, 121.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 129.4ms
Speed: 4.2ms preprocess, 129.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 144.2ms
Speed: 4.4ms preprocess, 144.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 127.4ms
Speed: 4.4ms preprocess, 127.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 136.0ms
Speed: 4.4ms preprocess, 136.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 141.7ms
Speed: 4.4ms preprocess, 141.7ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 133.0ms
Speed: 4.4ms preprocess, 133.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 126.3ms
Speed: 4.4ms preprocess, 126.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 130.5ms
Speed: 4.3ms preprocess, 130.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 127.4ms
Speed: 4.4ms preprocess, 127.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 126.3ms
Speed: 4.2ms preprocess, 126.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 birds, 127.1ms
Speed: 4.4ms preprocess, 127.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 122.7ms
Speed: 4.3ms preprocess, 122.7ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 144.9ms
Speed: 3.8ms preprocess, 144.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 129.8ms
Speed: 4.3ms preprocess, 129.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 127.4ms
Speed: 4.3ms preprocess, 127.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 128.3ms
Speed: 4.9ms preprocess, 128.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 131.4ms
Speed: 4.2ms preprocess, 131.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 129.0ms
Speed: 4.2ms preprocess, 129.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 128.0ms
Speed: 5.6ms preprocess, 128.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 131.4ms
Speed: 4.2ms preprocess, 131.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 123.4ms
Speed: 4.4ms preprocess, 123.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 142.3ms
Speed: 7.4ms preprocess, 142.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 128.8ms
Speed: 4.4ms preprocess, 128.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 127.9ms
Speed: 4.2ms preprocess, 127.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 128.0ms
Speed: 4.4ms preprocess, 128.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 132.0ms
Speed: 4.2ms preprocess, 132.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 134.2ms
Speed: 4.4ms preprocess, 134.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 129.5ms
Speed: 4.3ms preprocess, 129.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 131.8ms
Speed: 4.3ms preprocess, 131.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 131.6ms
Speed: 4.5ms preprocess, 131.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 146.4ms
Speed: 4.1ms preprocess, 146.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 129.3ms
Speed: 4.4ms preprocess, 129.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 126.9ms
Speed: 4.3ms preprocess, 126.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 134.8ms
Speed: 4.6ms preprocess, 134.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 136.7ms
Speed: 4.6ms preprocess, 136.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 126.3ms
Speed: 4.7ms preprocess, 126.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 132.1ms
Speed: 4.4ms preprocess, 132.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 129.2ms
Speed: 5.2ms preprocess, 129.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 128.9ms
Speed: 4.0ms preprocess, 128.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 206.1ms
Speed: 4.6ms preprocess, 206.1ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 187.1ms
Speed: 12.3ms preprocess, 187.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 211.5ms
Speed: 4.2ms preprocess, 211.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 214.8ms
Speed: 10.7ms preprocess, 214.8ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 210.4ms
Speed: 5.1ms preprocess, 210.4ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 190.4ms
Speed: 4.0ms preprocess, 190.4ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 217.9ms
Speed: 4.2ms preprocess, 217.9ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 150.7ms
Speed: 6.2ms preprocess, 150.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 129.6ms
Speed: 4.2ms preprocess, 129.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 129.3ms
Speed: 5.0ms preprocess, 129.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 141.2ms
Speed: 4.3ms preprocess, 141.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 121.1ms
Speed: 4.3ms preprocess, 121.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 131.2ms
Speed: 5.2ms preprocess, 131.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 129.9ms
Speed: 5.7ms preprocess, 129.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 125.0ms
Speed: 4.2ms preprocess, 125.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 136.8ms
Speed: 3.9ms preprocess, 136.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 124.7ms
Speed: 4.2ms preprocess, 124.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 128.7ms
Speed: 4.5ms preprocess, 128.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 128.1ms
Speed: 4.8ms preprocess, 128.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 136.3ms
Speed: 4.2ms preprocess, 136.3ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 125.2ms
Speed: 4.1ms preprocess, 125.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 128.0ms
Speed: 4.1ms preprocess, 128.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 128.4ms
Speed: 4.2ms preprocess, 128.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 121.8ms
Speed: 4.7ms preprocess, 121.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 144.8ms
Speed: 6.0ms preprocess, 144.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 123.5ms
Speed: 4.8ms preprocess, 123.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 123.7ms
Speed: 4.1ms preprocess, 123.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 131.4ms
Speed: 4.3ms preprocess, 131.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 124.8ms
Speed: 4.2ms preprocess, 124.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 125.9ms
Speed: 4.3ms preprocess, 125.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 131.4ms
Speed: 4.3ms preprocess, 131.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 123.6ms
Speed: 4.2ms preprocess, 123.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 124.1ms
Speed: 4.3ms preprocess, 124.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 145.9ms
Speed: 3.9ms preprocess, 145.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 125.9ms
Speed: 5.3ms preprocess, 125.9ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 124.0ms
Speed: 4.2ms preprocess, 124.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 137.6ms
Speed: 4.2ms preprocess, 137.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 125.0ms
Speed: 5.1ms preprocess, 125.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 142.5ms
Speed: 4.1ms preprocess, 142.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 131.2ms
Speed: 4.1ms preprocess, 131.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 127.5ms
Speed: 4.3ms preprocess, 127.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 125.7ms
Speed: 5.3ms preprocess, 125.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 130.7ms
Speed: 5.9ms preprocess, 130.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 123.2ms
Speed: 4.4ms preprocess, 123.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 123.7ms
Speed: 4.2ms preprocess, 123.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 130.2ms
Speed: 4.2ms preprocess, 130.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 124.0ms
Speed: 4.2ms preprocess, 124.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 137.8ms
Speed: 4.3ms preprocess, 137.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 127.1ms
Speed: 4.5ms preprocess, 127.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 126.6ms
Speed: 4.3ms preprocess, 126.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 123.0ms
Speed: 4.4ms preprocess, 123.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 127.1ms
Speed: 5.3ms preprocess, 127.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 219.9ms
Speed: 5.4ms preprocess, 219.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 197.5ms
Speed: 8.4ms preprocess, 197.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 209.9ms
Speed: 7.9ms preprocess, 209.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 199.2ms
Speed: 4.2ms preprocess, 199.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 198.8ms
Speed: 4.3ms preprocess, 198.8ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 202.0ms
Speed: 4.3ms preprocess, 202.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 211.3ms
Speed: 4.2ms preprocess, 211.3ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 163.1ms
Speed: 8.6ms preprocess, 163.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 130.5ms
Speed: 3.8ms preprocess, 130.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 124.3ms
Speed: 4.1ms preprocess, 124.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 141.7ms
Speed: 4.1ms preprocess, 141.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 138.9ms
Speed: 3.8ms preprocess, 138.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 123.9ms
Speed: 4.2ms preprocess, 123.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 137.8ms
Speed: 4.2ms preprocess, 137.8ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 129.6ms
Speed: 4.9ms preprocess, 129.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 126.1ms
Speed: 4.2ms preprocess, 126.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 123.3ms
Speed: 4.1ms preprocess, 123.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 132.2ms
Speed: 5.4ms preprocess, 132.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 123.7ms
Speed: 4.2ms preprocess, 123.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 138.1ms
Speed: 4.3ms preprocess, 138.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 126.8ms
Speed: 4.3ms preprocess, 126.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 124.3ms
Speed: 4.2ms preprocess, 124.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 125.1ms
Speed: 4.2ms preprocess, 125.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 125.3ms
Speed: 4.5ms preprocess, 125.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 141.6ms
Speed: 4.2ms preprocess, 141.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 127.4ms
Speed: 5.1ms preprocess, 127.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 128.7ms
Speed: 4.3ms preprocess, 128.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 129.7ms
Speed: 4.9ms preprocess, 129.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 125.6ms
Speed: 5.2ms preprocess, 125.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 126.8ms
Speed: 4.2ms preprocess, 126.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 125.6ms
Speed: 4.3ms preprocess, 125.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 124.3ms
Speed: 4.2ms preprocess, 124.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 130.6ms
Speed: 4.3ms preprocess, 130.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 147.0ms
Speed: 5.3ms preprocess, 147.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 120.4ms
Speed: 4.2ms preprocess, 120.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 132.2ms
Speed: 3.8ms preprocess, 132.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 127.4ms
Speed: 4.2ms preprocess, 127.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 123.6ms
Speed: 4.4ms preprocess, 123.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 128.3ms
Speed: 7.1ms preprocess, 128.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 128.2ms
Speed: 5.2ms preprocess, 128.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 125.2ms
Speed: 4.3ms preprocess, 125.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 131.1ms
Speed: 6.2ms preprocess, 131.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 140.5ms
Speed: 4.3ms preprocess, 140.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 122.5ms
Speed: 4.2ms preprocess, 122.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 127.6ms
Speed: 5.1ms preprocess, 127.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 126.7ms
Speed: 4.2ms preprocess, 126.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 126.6ms
Speed: 4.2ms preprocess, 126.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 144.6ms
Speed: 4.3ms preprocess, 144.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 126.1ms
Speed: 5.3ms preprocess, 126.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 123.1ms
Speed: 4.2ms preprocess, 123.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 134.6ms
Speed: 3.9ms preprocess, 134.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 126.0ms
Speed: 4.4ms preprocess, 126.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 195.2ms
Speed: 8.3ms preprocess, 195.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 209.4ms
Speed: 4.2ms preprocess, 209.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 200.9ms
Speed: 8.9ms preprocess, 200.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 213.3ms
Speed: 3.9ms preprocess, 213.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 203.2ms
Speed: 7.0ms preprocess, 203.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 221.4ms
Speed: 4.0ms preprocess, 221.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 210.1ms
Speed: 8.0ms preprocess, 210.1ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 164.5ms
Speed: 5.8ms preprocess, 164.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 124.5ms
Speed: 4.2ms preprocess, 124.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 126.7ms
Speed: 4.3ms preprocess, 126.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 143.0ms
Speed: 6.2ms preprocess, 143.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 125.2ms
Speed: 4.7ms preprocess, 125.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 126.3ms
Speed: 4.1ms preprocess, 126.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 134.0ms

              idf1      mota      motp  num_switches
Tracking  0.869641  0.873311  0.351887             5

**for yolo11m:**

In [ ]:
model= YOLO("yolo11m.pt")

Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11m.pt to 'yolo11m.pt'...

100%|██████████| 38.8M/38.8M [00:00<00:00, 120MB/s]

In [ ]:
run_ocsort_save_json(model, "/content/birds_sky.mp4", "output_birds_sky.mp4", "birds_sky_results.json")
convert_json_to_mot("/content/gt_birds_sky_results_yolo11x.json", "/content/birds_sky_gt.txt")
convert_json_to_mot("birds_sky_results.json", "birds_sky_results.txt")
compute_tracking_metrics("/content/birds_sky_gt.txt", "birds_sky_results.txt")

0: 384x640 6 birds, 901.4ms
Speed: 4.4ms preprocess, 901.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 800.1ms
Speed: 4.4ms preprocess, 800.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 802.0ms
Speed: 4.1ms preprocess, 802.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 749.5ms
Speed: 4.8ms preprocess, 749.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 775.4ms
Speed: 4.7ms preprocess, 775.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 760.8ms
Speed: 4.5ms preprocess, 760.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 782.9ms
Speed: 4.3ms preprocess, 782.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 740.5ms
Speed: 5.9ms preprocess, 740.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 802.3ms
Speed: 4.4ms preprocess, 802.3ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 773.2ms
Speed: 4.7ms preprocess, 773.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 767.7ms
Speed: 4.3ms preprocess, 767.7ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 1089.0ms
Speed: 4.3ms preprocess, 1089.0ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 1206.4ms
Speed: 4.5ms preprocess, 1206.4ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 845.2ms
Speed: 4.5ms preprocess, 845.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 769.2ms
Speed: 4.0ms preprocess, 769.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 751.1ms
Speed: 4.4ms preprocess, 751.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 767.9ms
Speed: 4.4ms preprocess, 767.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 766.1ms
Speed: 4.4ms preprocess, 766.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 773.8ms
Speed: 4.9ms preprocess, 773.8ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 758.7ms
Speed: 4.4ms preprocess, 758.7ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 762.9ms
Speed: 4.3ms preprocess, 762.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 764.2ms
Speed: 4.4ms preprocess, 764.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 760.1ms
Speed: 4.3ms preprocess, 760.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 759.7ms
Speed: 4.4ms preprocess, 759.7ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 749.1ms
Speed: 4.4ms preprocess, 749.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 883.0ms
Speed: 3.9ms preprocess, 883.0ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 1197.2ms
Speed: 4.5ms preprocess, 1197.2ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 1054.2ms
Speed: 4.4ms preprocess, 1054.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 771.4ms
Speed: 4.4ms preprocess, 771.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 765.2ms
Speed: 4.2ms preprocess, 765.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 769.0ms
Speed: 5.7ms preprocess, 769.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 748.0ms
Speed: 4.6ms preprocess, 748.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 747.3ms
Speed: 3.6ms preprocess, 747.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 760.6ms
Speed: 4.4ms preprocess, 760.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 762.0ms
Speed: 4.7ms preprocess, 762.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 771.3ms
Speed: 4.5ms preprocess, 771.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 739.0ms
Speed: 4.4ms preprocess, 739.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 765.0ms
Speed: 3.5ms preprocess, 765.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 763.2ms
Speed: 4.3ms preprocess, 763.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 757.2ms
Speed: 4.4ms preprocess, 757.2ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 1152.0ms
Speed: 4.4ms preprocess, 1152.0ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 1178.3ms
Speed: 4.2ms preprocess, 1178.3ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 795.9ms
Speed: 4.4ms preprocess, 795.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 742.8ms
Speed: 4.4ms preprocess, 742.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 754.0ms
Speed: 8.4ms preprocess, 754.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 761.2ms
Speed: 4.4ms preprocess, 761.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 763.7ms
Speed: 4.6ms preprocess, 763.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 760.0ms
Speed: 4.2ms preprocess, 760.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 746.4ms
Speed: 4.5ms preprocess, 746.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 767.2ms
Speed: 4.4ms preprocess, 767.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 758.9ms
Speed: 4.3ms preprocess, 758.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 774.4ms
Speed: 4.7ms preprocess, 774.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 749.2ms
Speed: 4.5ms preprocess, 749.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 764.4ms
Speed: 4.3ms preprocess, 764.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 912.5ms
Speed: 4.4ms preprocess, 912.5ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 1204.3ms
Speed: 4.4ms preprocess, 1204.3ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 980.4ms
Speed: 7.9ms preprocess, 980.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 755.7ms
Speed: 4.3ms preprocess, 755.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 756.9ms
Speed: 3.9ms preprocess, 756.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 739.1ms
Speed: 4.2ms preprocess, 739.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 748.8ms
Speed: 5.0ms preprocess, 748.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 761.3ms
Speed: 4.6ms preprocess, 761.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 758.8ms
Speed: 4.3ms preprocess, 758.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 766.0ms
Speed: 4.6ms preprocess, 766.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 759.0ms
Speed: 4.5ms preprocess, 759.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 779.0ms
Speed: 4.5ms preprocess, 779.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 783.0ms
Speed: 4.4ms preprocess, 783.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 780.2ms
Speed: 4.3ms preprocess, 780.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 775.2ms
Speed: 4.8ms preprocess, 775.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 1213.7ms
Speed: 6.0ms preprocess, 1213.7ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 1138.2ms
Speed: 7.2ms preprocess, 1138.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 756.7ms
Speed: 3.9ms preprocess, 756.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 796.5ms
Speed: 5.3ms preprocess, 796.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 874.9ms
Speed: 4.5ms preprocess, 874.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 822.6ms
Speed: 4.0ms preprocess, 822.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 816.7ms
Speed: 4.3ms preprocess, 816.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 815.0ms
Speed: 5.0ms preprocess, 815.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 776.1ms
Speed: 5.1ms preprocess, 776.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 817.6ms
Speed: 3.9ms preprocess, 817.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 818.3ms
Speed: 4.4ms preprocess, 818.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 817.2ms
Speed: 4.4ms preprocess, 817.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 809.6ms
Speed: 4.6ms preprocess, 809.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 920.4ms
Speed: 4.4ms preprocess, 920.4ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 1245.2ms
Speed: 4.2ms preprocess, 1245.2ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 1024.9ms
Speed: 4.8ms preprocess, 1024.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 784.2ms
Speed: 4.7ms preprocess, 784.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 777.5ms
Speed: 4.0ms preprocess, 777.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 793.0ms
Speed: 4.3ms preprocess, 793.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 789.1ms
Speed: 4.4ms preprocess, 789.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 770.8ms
Speed: 4.3ms preprocess, 770.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 782.7ms
Speed: 4.3ms preprocess, 782.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 780.1ms
Speed: 4.0ms preprocess, 780.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 796.1ms
Speed: 4.4ms preprocess, 796.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 788.9ms
Speed: 4.3ms preprocess, 788.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 789.0ms
Speed: 3.9ms preprocess, 789.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 780.4ms
Speed: 4.3ms preprocess, 780.4ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 880.9ms
Speed: 5.2ms preprocess, 880.9ms inference, 2.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 1246.5ms
Speed: 4.3ms preprocess, 1246.5ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 1062.0ms
Speed: 4.4ms preprocess, 1062.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 770.3ms
Speed: 4.4ms preprocess, 770.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 778.2ms
Speed: 4.4ms preprocess, 778.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 784.1ms
Speed: 3.8ms preprocess, 784.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 772.7ms
Speed: 4.2ms preprocess, 772.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 768.4ms
Speed: 4.3ms preprocess, 768.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 761.7ms
Speed: 4.4ms preprocess, 761.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 773.0ms
Speed: 4.3ms preprocess, 773.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 789.4ms
Speed: 4.4ms preprocess, 789.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 780.1ms
Speed: 4.3ms preprocess, 780.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 777.1ms
Speed: 4.4ms preprocess, 777.1ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 772.2ms
Speed: 4.3ms preprocess, 772.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 851.1ms
Speed: 3.9ms preprocess, 851.1ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1222.8ms
Speed: 4.1ms preprocess, 1222.8ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1112.9ms
Speed: 4.4ms preprocess, 1112.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 777.0ms
Speed: 3.9ms preprocess, 777.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 778.6ms
Speed: 4.3ms preprocess, 778.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 786.5ms
Speed: 4.3ms preprocess, 786.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 777.8ms
Speed: 4.6ms preprocess, 777.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 753.9ms
Speed: 4.2ms preprocess, 753.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 771.6ms
Speed: 4.3ms preprocess, 771.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 781.3ms
Speed: 4.3ms preprocess, 781.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 787.8ms
Speed: 3.7ms preprocess, 787.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 760.0ms
Speed: 4.2ms preprocess, 760.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 768.6ms
Speed: 4.4ms preprocess, 768.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 775.3ms
Speed: 3.8ms preprocess, 775.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 769.2ms
Speed: 4.3ms preprocess, 769.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1217.6ms
Speed: 4.3ms preprocess, 1217.6ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1235.2ms
Speed: 4.3ms preprocess, 1235.2ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 788.5ms
Speed: 4.4ms preprocess, 788.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 785.6ms
Speed: 4.1ms preprocess, 785.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 791.1ms
Speed: 4.0ms preprocess, 791.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 771.6ms
Speed: 4.3ms preprocess, 771.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 793.7ms
Speed: 3.9ms preprocess, 793.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 796.3ms
Speed: 4.0ms preprocess, 796.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 779.9ms
Speed: 4.0ms preprocess, 779.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 765.5ms
Speed: 4.3ms preprocess, 765.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 773.2ms
Speed: 3.9ms preprocess, 773.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 775.6ms
Speed: 4.3ms preprocess, 775.6ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 794.5ms
Speed: 4.5ms preprocess, 794.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 769.5ms
Speed: 4.3ms preprocess, 769.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1110.5ms
Speed: 5.8ms preprocess, 1110.5ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1249.2ms
Speed: 4.4ms preprocess, 1249.2ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 826.4ms
Speed: 4.4ms preprocess, 826.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 787.7ms
Speed: 4.2ms preprocess, 787.7ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 795.2ms
Speed: 4.1ms preprocess, 795.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 797.6ms
Speed: 4.4ms preprocess, 797.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 800.8ms
Speed: 4.2ms preprocess, 800.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 800.4ms
Speed: 4.8ms preprocess, 800.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 800.6ms
Speed: 4.3ms preprocess, 800.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 786.0ms
Speed: 4.4ms preprocess, 786.0ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 805.9ms
Speed: 4.3ms preprocess, 805.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 800.7ms
Speed: 4.0ms preprocess, 800.7ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 798.3ms
Speed: 5.0ms preprocess, 798.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 796.4ms
Speed: 4.0ms preprocess, 796.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1226.8ms
Speed: 4.7ms preprocess, 1226.8ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1205.2ms
Speed: 4.4ms preprocess, 1205.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 806.4ms
Speed: 4.0ms preprocess, 806.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 808.7ms
Speed: 3.8ms preprocess, 808.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)


              idf1      mota      motp  num_switches
Tracking  0.985639  0.986395  0.238411             0

In [ ]:
run_ocsort_save_json(model, "similar_birds.mp4", "output_similar_birds.mp4", "similar_birds_results.json",  OCSort(
    det_thresh=0.4,
    max_age=50,
    min_hits=4,
    iou_threshold=0.3,
    delta_t=3,
    inertia=0.4,
    asso_func="iou"
))
convert_json_to_mot("/content/annotations_gt_SB.json", "/content/annotations_gt_SB.txt")
convert_json_to_mot("similar_birds_results.json", "similar_birds_results.txt")
compute_tracking_metrics("annotations_gt_SB.txt", "similar_birds_results.txt")

0: 384x640 4 airplanes, 1 bird, 879.0ms
Speed: 3.5ms preprocess, 879.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 855.7ms
Speed: 4.4ms preprocess, 855.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 771.8ms
Speed: 4.0ms preprocess, 771.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1156.7ms
Speed: 3.9ms preprocess, 1156.7ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1315.0ms
Speed: 4.2ms preprocess, 1315.0ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 744.6ms
Speed: 4.5ms preprocess, 744.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 782.2ms
Speed: 4.3ms preprocess, 782.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 734.5ms
Speed: 4.0ms preprocess, 734.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 841.9ms
Speed: 3.9ms preprocess, 841.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 4 birds, 746.4ms
Speed: 4.4ms preprocess, 746.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 5 birds, 842.9ms
Speed: 4.4ms preprocess, 842.9ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 748.1ms
Speed: 4.2ms preprocess, 748.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 770.1ms
Speed: 4.2ms preprocess, 770.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 734.9ms
Speed: 4.4ms preprocess, 734.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 1109.0ms
Speed: 32.7ms preprocess, 1109.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 3 birds, 923.3ms
Speed: 4.2ms preprocess, 923.3ms inference, 3.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 5 birds, 1651.7ms
Speed: 4.5ms preprocess, 1651.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 3 birds, 2327.2ms
Speed: 11.6ms preprocess, 2327.2ms inference, 3.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 3 birds, 1389.1ms
Speed: 14.6ms preprocess, 1389.1ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 749.7ms
Speed: 4.9ms preprocess, 749.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 3 birds, 794.1ms
Speed: 4.5ms preprocess, 794.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 3 birds, 731.0ms
Speed: 4.6ms preprocess, 731.0ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 758.7ms
Speed: 4.4ms preprocess, 758.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 744.9ms
Speed: 4.2ms preprocess, 744.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 766.0ms
Speed: 4.3ms preprocess, 766.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 744.6ms
Speed: 4.0ms preprocess, 744.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 759.5ms
Speed: 4.2ms preprocess, 759.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 730.1ms
Speed: 4.5ms preprocess, 730.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 747.2ms
Speed: 7.3ms preprocess, 747.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 1134.0ms
Speed: 4.5ms preprocess, 1134.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 1224.0ms
Speed: 6.2ms preprocess, 1224.0ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 738.4ms
Speed: 4.3ms preprocess, 738.4ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 739.0ms
Speed: 4.5ms preprocess, 739.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 743.7ms
Speed: 4.2ms preprocess, 743.7ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 762.5ms
Speed: 4.1ms preprocess, 762.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 738.1ms
Speed: 4.0ms preprocess, 738.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 756.9ms
Speed: 4.3ms preprocess, 756.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 731.0ms
Speed: 4.3ms preprocess, 731.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 753.7ms
Speed: 4.4ms preprocess, 753.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 743.1ms
Speed: 4.3ms preprocess, 743.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 760.3ms
Speed: 4.3ms preprocess, 760.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 738.8ms
Speed: 4.4ms preprocess, 738.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 802.2ms
Speed: 4.3ms preprocess, 802.2ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 1196.6ms
Speed: 4.1ms preprocess, 1196.6ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 1068.3ms
Speed: 4.4ms preprocess, 1068.3ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 756.5ms
Speed: 4.4ms preprocess, 756.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 756.4ms
Speed: 4.2ms preprocess, 756.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 727.1ms
Speed: 3.9ms preprocess, 727.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 754.8ms
Speed: 4.3ms preprocess, 754.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 2 birds, 739.9ms
Speed: 4.1ms preprocess, 739.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 4 birds, 759.6ms
Speed: 5.2ms preprocess, 759.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 4 birds, 747.1ms
Speed: 4.2ms preprocess, 747.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 741.2ms
Speed: 4.4ms preprocess, 741.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 742.0ms
Speed: 4.2ms preprocess, 742.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 763.0ms
Speed: 4.2ms preprocess, 763.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 749.1ms
Speed: 4.6ms preprocess, 749.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 992.6ms
Speed: 4.2ms preprocess, 992.6ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 3 birds, 1169.4ms
Speed: 4.4ms preprocess, 1169.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 925.6ms
Speed: 12.3ms preprocess, 925.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 754.9ms
Speed: 5.1ms preprocess, 754.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 760.7ms
Speed: 4.2ms preprocess, 760.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 742.7ms
Speed: 4.2ms preprocess, 742.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 772.5ms
Speed: 4.3ms preprocess, 772.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 4 birds, 736.8ms
Speed: 4.0ms preprocess, 736.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 4 birds, 780.7ms
Speed: 4.3ms preprocess, 780.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 747.6ms
Speed: 4.3ms preprocess, 747.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 2 birds, 755.5ms
Speed: 5.6ms preprocess, 755.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 3 birds, 744.8ms
Speed: 4.3ms preprocess, 744.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 744.0ms
Speed: 4.3ms preprocess, 744.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 4 birds, 731.1ms
Speed: 4.3ms preprocess, 731.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 4 birds, 1196.6ms
Speed: 4.5ms preprocess, 1196.6ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 1132.0ms
Speed: 3.8ms preprocess, 1132.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 773.3ms
Speed: 4.0ms preprocess, 773.3ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 727.3ms
Speed: 4.3ms preprocess, 727.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 763.6ms
Speed: 3.9ms preprocess, 763.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 745.2ms
Speed: 4.3ms preprocess, 745.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 757.7ms
Speed: 4.3ms preprocess, 757.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 744.9ms
Speed: 4.3ms preprocess, 744.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 770.6ms
Speed: 4.1ms preprocess, 770.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 734.5ms
Speed: 4.3ms preprocess, 734.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 754.9ms
Speed: 4.2ms preprocess, 754.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 739.2ms
Speed: 4.8ms preprocess, 739.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 765.3ms
Speed: 4.4ms preprocess, 765.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 897.8ms
Speed: 4.0ms preprocess, 897.8ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 1223.3ms
Speed: 4.4ms preprocess, 1223.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 945.2ms
Speed: 4.4ms preprocess, 945.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 745.9ms
Speed: 4.3ms preprocess, 745.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 3 birds, 749.4ms
Speed: 4.3ms preprocess, 749.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 730.6ms
Speed: 4.2ms preprocess, 730.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 3 birds, 750.6ms
Speed: 4.1ms preprocess, 750.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 4 birds, 768.4ms
Speed: 4.3ms preprocess, 768.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 5 birds, 745.8ms
Speed: 4.4ms preprocess, 745.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 4 birds, 752.4ms
Speed: 4.4ms preprocess, 752.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 746.4ms
Speed: 4.5ms preprocess, 746.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 743.7ms
Speed: 4.4ms preprocess, 743.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 750.6ms
Speed: 4.9ms preprocess, 750.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 747.2ms
Speed: 4.5ms preprocess, 747.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 4 birds, 1054.7ms
Speed: 4.6ms preprocess, 1054.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 4 birds, 1226.0ms
Speed: 4.5ms preprocess, 1226.0ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 764.9ms
Speed: 5.3ms preprocess, 764.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 745.3ms
Speed: 4.3ms preprocess, 745.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 746.2ms
Speed: 3.9ms preprocess, 746.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 751.3ms
Speed: 4.3ms preprocess, 751.3ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 1 bird, 738.7ms
Speed: 4.0ms preprocess, 738.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 748.0ms
Speed: 4.7ms preprocess, 748.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 746.4ms
Speed: 4.3ms preprocess, 746.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 3 birds, 746.4ms
Speed: 4.1ms preprocess, 746.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 2 birds, 735.3ms
Speed: 4.0ms preprocess, 735.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 743.1ms
Speed: 4.4ms preprocess, 743.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 751.0ms
Speed: 4.0ms preprocess, 751.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 5 birds, 753.6ms
Speed: 4.0ms preprocess, 753.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 1183.2ms
Speed: 4.3ms preprocess, 1183.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 1175.4ms
Speed: 4.4ms preprocess, 1175.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 5 birds, 751.9ms
Speed: 4.3ms preprocess, 751.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 5 birds, 766.9ms
Speed: 3.9ms preprocess, 766.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 760.9ms
Speed: 5.1ms preprocess, 760.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 3 birds, 772.0ms
Speed: 4.1ms preprocess, 772.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 751.6ms
Speed: 4.4ms preprocess, 751.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 2 birds, 752.5ms
Speed: 4.0ms preprocess, 752.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 749.1ms
Speed: 4.7ms preprocess, 749.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 767.2ms
Speed: 4.6ms preprocess, 767.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 airplanes, 3 birds, 756.4ms
Speed: 4.6ms preprocess, 756.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 airplanes, 1 bird, 769.8ms
Speed: 4.4ms preprocess, 769.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 3 birds, 731.3ms
Speed: 4.4ms preprocess, 731.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 airplanes, 2 birds, 931.4ms
Speed: 4.0ms preprocess, 931.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 3 birds, 1187.3ms
Speed: 4.3ms preprocess, 1187.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 958.5ms
Speed: 4.4ms preprocess, 958.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 748.3ms
Speed: 4.1ms preprocess, 748.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 761.2ms
Speed: 4.1ms preprocess, 761.2ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 770.8ms
Speed: 5.3ms preprocess, 770.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 767.1ms
Speed: 4.1ms preprocess, 767.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 748.4ms
Speed: 4.3ms preprocess, 748.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 763.6ms
Speed: 4.9ms preprocess, 763.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 5 birds, 737.6ms
Speed: 4.2ms preprocess, 737.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 5 birds, 752.7ms
Speed: 4.1ms preprocess, 752.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 5 birds, 748.6ms
Speed: 4.0ms preprocess, 748.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 airplane, 4 birds, 752.6ms
Speed: 4.0ms preprocess, 752.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 744.2ms
Speed: 4.1ms preprocess, 744.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 1183.3ms
Speed: 4.2ms preprocess, 1183.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 5 birds, 1188.4ms
Speed: 7.6ms preprocess, 1188.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 5 birds, 748.9ms
Speed: 4.3ms preprocess, 748.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 5 birds, 747.2ms
Speed: 4.4ms preprocess, 747.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 4 birds, 744.9ms
Speed: 4.3ms preprocess, 744.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 4 birds, 721.6ms
Speed: 4.6ms preprocess, 721.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 airplanes, 4 birds, 762.7ms
Speed: 3.9ms preprocess, 762.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)


              idf1      mota      motp  num_switches
Tracking  0.703223  0.899105  0.156479            29

In [ ]:
run_ocsort_save_json(model, "/content/oclusion_birds.mp4", "output_oclusion_birds.mp4", "oclusion_birds_results.json")
convert_json_to_mot("/content/occlusion_birds_gt.json", "/content/occlusion_birds_gt.txt")
convert_json_to_mot("oclusion_birds_results.json", "oclusion_birds_results.txt")
compute_tracking_metrics("/content/occlusion_birds_gt.txt", "oclusion_birds_results.txt")

0: 352x640 1 airplane, 1 bird, 1100.2ms
Speed: 4.2ms preprocess, 1100.2ms inference, 1.8ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 960.0ms
Speed: 3.6ms preprocess, 960.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 666.9ms
Speed: 3.9ms preprocess, 666.9ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 658.8ms
Speed: 6.6ms preprocess, 658.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 705.7ms
Speed: 3.5ms preprocess, 705.7ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 666.6ms
Speed: 3.9ms preprocess, 666.6ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 647.3ms
Speed: 3.7ms preprocess, 647.3ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 661.2ms
Speed: 4.2ms preprocess, 661.2ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 675.3ms
Speed: 3.5ms preprocess, 675.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 678.7ms
Speed: 4.6ms preprocess, 678.7ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 655.6ms
Speed: 3.5ms preprocess, 655.6ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 663.7ms
Speed: 3.4ms preprocess, 663.7ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 669.4ms
Speed: 4.3ms preprocess, 669.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 653.4ms
Speed: 3.6ms preprocess, 653.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 676.7ms
Speed: 3.5ms preprocess, 676.7ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 907.7ms
Speed: 3.4ms preprocess, 907.7ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 1077.1ms
Speed: 9.4ms preprocess, 1077.1ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 939.9ms
Speed: 5.3ms preprocess, 939.9ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 673.5ms
Speed: 3.7ms preprocess, 673.5ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 661.4ms
Speed: 3.7ms preprocess, 661.4ms inference, 1.7ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 airplanes, 1 bird, 658.4ms
Speed: 4.0ms preprocess, 658.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 674.2ms
Speed: 3.8ms preprocess, 674.2ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 666.0ms
Speed: 3.8ms preprocess, 666.0ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 658.4ms
Speed: 4.2ms preprocess, 658.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 664.4ms
Speed: 3.4ms preprocess, 664.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 669.1ms
Speed: 4.8ms preprocess, 669.1ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 650.1ms
Speed: 4.9ms preprocess, 650.1ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 671.3ms
Speed: 8.2ms preprocess, 671.3ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 673.8ms
Speed: 3.5ms preprocess, 673.8ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 659.3ms
Speed: 3.8ms preprocess, 659.3ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 650.7ms
Speed: 4.0ms preprocess, 650.7ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 2 birds, 911.5ms
Speed: 3.6ms preprocess, 911.5ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1054.4ms
Speed: 3.8ms preprocess, 1054.4ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 980.1ms
Speed: 5.2ms preprocess, 980.1ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 673.0ms
Speed: 4.3ms preprocess, 673.0ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 668.1ms
Speed: 3.7ms preprocess, 668.1ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 654.8ms
Speed: 3.9ms preprocess, 654.8ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 671.0ms
Speed: 3.9ms preprocess, 671.0ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 2 birds, 667.1ms
Speed: 4.9ms preprocess, 667.1ms inference, 1.7ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 2 birds, 651.4ms
Speed: 3.9ms preprocess, 651.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 653.6ms
Speed: 3.5ms preprocess, 653.6ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 667.4ms
Speed: 4.9ms preprocess, 667.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 660.4ms
Speed: 4.9ms preprocess, 660.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 645.0ms
Speed: 10.3ms preprocess, 645.0ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 667.2ms
Speed: 4.4ms preprocess, 667.2ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 672.7ms
Speed: 5.1ms preprocess, 672.7ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 649.6ms
Speed: 3.9ms preprocess, 649.6ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 875.1ms
Speed: 5.0ms preprocess, 875.1ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 1058.5ms
Speed: 10.7ms preprocess, 1058.5ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 990.8ms
Speed: 4.1ms preprocess, 990.8ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 666.7ms
Speed: 3.6ms preprocess, 666.7ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 672.0ms
Speed: 3.7ms preprocess, 672.0ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 645.8ms
Speed: 3.9ms preprocess, 645.8ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 651.5ms
Speed: 3.8ms preprocess, 651.5ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 658.3ms
Speed: 3.5ms preprocess, 658.3ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 665.9ms
Speed: 3.8ms preprocess, 665.9ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 655.3ms
Speed: 3.6ms preprocess, 655.3ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 673.7ms
Speed: 3.5ms preprocess, 673.7ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 airplanes, 663.4ms
Speed: 5.8ms preprocess, 663.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 654.0ms
Speed: 3.5ms preprocess, 654.0ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 663.8ms
Speed: 4.9ms preprocess, 663.8ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 673.5ms
Speed: 3.9ms preprocess, 673.5ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 647.5ms
Speed: 4.0ms preprocess, 647.5ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 819.9ms
Speed: 4.0ms preprocess, 819.9ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 1049.7ms
Speed: 3.8ms preprocess, 1049.7ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1044.0ms
Speed: 10.9ms preprocess, 1044.0ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 667.2ms
Speed: 3.9ms preprocess, 667.2ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 667.6ms
Speed: 3.9ms preprocess, 667.6ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 664.5ms
Speed: 4.0ms preprocess, 664.5ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 650.3ms
Speed: 3.9ms preprocess, 650.3ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 679.1ms
Speed: 3.9ms preprocess, 679.1ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 668.8ms
Speed: 3.7ms preprocess, 668.8ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 661.4ms
Speed: 3.9ms preprocess, 661.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 660.6ms
Speed: 3.8ms preprocess, 660.6ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 665.3ms
Speed: 3.9ms preprocess, 665.3ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 657.8ms
Speed: 4.1ms preprocess, 657.8ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 664.7ms
Speed: 3.6ms preprocess, 664.7ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 665.8ms
Speed: 4.7ms preprocess, 665.8ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 657.2ms
Speed: 3.8ms preprocess, 657.2ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 792.0ms
Speed: 3.8ms preprocess, 792.0ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 1091.0ms
Speed: 3.7ms preprocess, 1091.0ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1055.0ms
Speed: 5.9ms preprocess, 1055.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 649.7ms
Speed: 3.8ms preprocess, 649.7ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 674.1ms
Speed: 3.9ms preprocess, 674.1ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 birds, 660.5ms
Speed: 3.8ms preprocess, 660.5ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 birds, 656.1ms
Speed: 3.5ms preprocess, 656.1ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 birds, 665.4ms
Speed: 3.5ms preprocess, 665.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 856.2ms
Speed: 3.8ms preprocess, 856.2ms inference, 1.7ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1046.0ms
Speed: 10.2ms preprocess, 1046.0ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1042.9ms
Speed: 3.9ms preprocess, 1042.9ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 670.9ms
Speed: 4.8ms preprocess, 670.9ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 655.0ms
Speed: 3.9ms preprocess, 655.0ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 673.0ms
Speed: 4.7ms preprocess, 673.0ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 667.1ms
Speed: 3.8ms preprocess, 667.1ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 944.4ms
Speed: 4.2ms preprocess, 944.4ms inference, 1.7ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 1078.8ms
Speed: 3.9ms preprocess, 1078.8ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 902.2ms
Speed: 3.9ms preprocess, 902.2ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 653.5ms
Speed: 5.1ms preprocess, 653.5ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 671.6ms
Speed: 4.0ms preprocess, 671.6ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 666.6ms
Speed: 3.6ms preprocess, 666.6ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 661.5ms
Speed: 4.0ms preprocess, 661.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 655.0ms
Speed: 4.9ms preprocess, 655.0ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 665.9ms
Speed: 3.9ms preprocess, 665.9ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 677.3ms
Speed: 7.6ms preprocess, 677.3ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 662.2ms
Speed: 3.7ms preprocess, 662.2ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 665.0ms
Speed: 3.5ms preprocess, 665.0ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 664.7ms
Speed: 5.2ms preprocess, 664.7ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 658.3ms
Speed: 3.7ms preprocess, 658.3ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 690.0ms
Speed: 5.0ms preprocess, 690.0ms inference, 1.5ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 676.0ms
Speed: 3.8ms preprocess, 676.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 945.8ms
Speed: 3.8ms preprocess, 945.8ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 1 kite, 1063.5ms
Speed: 10.0ms preprocess, 1063.5ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 901.3ms
Speed: 3.8ms preprocess, 901.3ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 669.3ms
Speed: 3.8ms preprocess, 669.3ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 650.8ms
Speed: 3.9ms preprocess, 650.8ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 671.3ms
Speed: 3.9ms preprocess, 671.3ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 670.4ms
Speed: 3.7ms preprocess, 670.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 672.4ms
Speed: 3.9ms preprocess, 672.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 668.0ms
Speed: 5.8ms preprocess, 668.0ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 664.2ms
Speed: 3.8ms preprocess, 664.2ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 653.1ms
Speed: 3.9ms preprocess, 653.1ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 662.4ms
Speed: 3.9ms preprocess, 662.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 670.6ms
Speed: 3.9ms preprocess, 670.6ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 665.6ms
Speed: 3.9ms preprocess, 665.6ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 654.2ms
Speed: 3.7ms preprocess, 654.2ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 667.6ms
Speed: 3.8ms preprocess, 667.6ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 917.5ms
Speed: 5.3ms preprocess, 917.5ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 1059.9ms
Speed: 3.8ms preprocess, 1059.9ms inference, 1.5ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 938.4ms
Speed: 3.7ms preprocess, 938.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 672.9ms
Speed: 3.8ms preprocess, 672.9ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 652.5ms
Speed: 3.6ms preprocess, 652.5ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 680.8ms
Speed: 3.5ms preprocess, 680.8ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 665.4ms
Speed: 3.8ms preprocess, 665.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 655.6ms
Speed: 5.3ms preprocess, 655.6ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 665.2ms
Speed: 4.1ms preprocess, 665.2ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 663.1ms
Speed: 3.8ms preprocess, 663.1ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 656.3ms
Speed: 3.9ms preprocess, 656.3ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 673.7ms
Speed: 3.6ms preprocess, 673.7ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 668.9ms
Speed: 3.9ms preprocess, 668.9ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 662.4ms
Speed: 3.5ms preprocess, 662.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 651.7ms
Speed: 3.8ms preprocess, 651.7ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 1 kite, 662.1ms
Speed: 6.3ms preprocess, 662.1ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 1 kite, 898.7ms
Speed: 4.0ms preprocess, 898.7ms inference, 1.5ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 1079.5ms
Speed: 5.8ms preprocess, 1079.5ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 950.8ms
Speed: 3.9ms preprocess, 950.8ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 2 kites, 677.1ms
Speed: 4.3ms preprocess, 677.1ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 kites, 641.8ms
Speed: 4.4ms preprocess, 641.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 1 kite, 670.9ms
Speed: 3.7ms preprocess, 670.9ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 2 kites, 662.2ms
Speed: 3.6ms preprocess, 662.2ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 kites, 657.0ms
Speed: 4.4ms preprocess, 657.0ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)


              idf1      mota      motp  num_switches
Tracking  0.661741  0.759677  0.219943            27

In [ ]:
run_ocsort_save_json(model, "/content/birds_beach.mp4", "output_birds_beach.mp4", "birds_beach_results.json")

convert_json_to_mot("birds_beach_results.json", "birds_beach_results.txt") # bb
convert_json_to_mot("/content/bb_gt_output.json", "/content/bb_gt_output.txt") # bb gt

compute_tracking_metrics("/content/bb_gt_output.txt", "birds_beach_results.txt") #compare

0: 384x640 3 birds, 763.6ms
Speed: 6.3ms preprocess, 763.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 722.5ms
Speed: 4.0ms preprocess, 722.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 725.6ms
Speed: 4.8ms preprocess, 725.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 706.8ms
Speed: 3.8ms preprocess, 706.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 723.4ms
Speed: 3.7ms preprocess, 723.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 718.7ms
Speed: 3.9ms preprocess, 718.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 722.3ms
Speed: 4.8ms preprocess, 722.3ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 710.3ms
Speed: 3.9ms preprocess, 710.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 769.3ms
Speed: 4.2ms preprocess, 769.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 848.6ms
Speed: 4.1ms preprocess, 848.6ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 1147.1ms
Speed: 5.9ms preprocess, 1147.1ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 1020.8ms
Speed: 4.2ms preprocess, 1020.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 725.8ms
Speed: 5.0ms preprocess, 725.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 712.7ms
Speed: 4.2ms preprocess, 712.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 709.6ms
Speed: 5.6ms preprocess, 709.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 722.1ms
Speed: 4.7ms preprocess, 722.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 720.4ms
Speed: 3.9ms preprocess, 720.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 704.0ms
Speed: 4.0ms preprocess, 704.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 719.2ms
Speed: 4.8ms preprocess, 719.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 723.3ms
Speed: 4.1ms preprocess, 723.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 722.7ms
Speed: 4.4ms preprocess, 722.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 700.0ms
Speed: 4.0ms preprocess, 700.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 720.1ms
Speed: 4.1ms preprocess, 720.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 731.2ms
Speed: 5.1ms preprocess, 731.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 719.3ms
Speed: 4.0ms preprocess, 719.3ms inference, 3.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 1139.7ms
Speed: 6.8ms preprocess, 1139.7ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 1149.5ms
Speed: 4.7ms preprocess, 1149.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 726.9ms
Speed: 4.4ms preprocess, 726.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 713.1ms
Speed: 4.2ms preprocess, 713.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 720.8ms
Speed: 4.0ms preprocess, 720.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 722.1ms
Speed: 4.2ms preprocess, 722.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 711.8ms
Speed: 3.7ms preprocess, 711.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 721.9ms
Speed: 4.0ms preprocess, 721.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 726.3ms
Speed: 4.1ms preprocess, 726.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 719.0ms
Speed: 4.3ms preprocess, 719.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 709.0ms
Speed: 4.0ms preprocess, 709.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 718.8ms
Speed: 4.2ms preprocess, 718.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 738.5ms
Speed: 4.1ms preprocess, 738.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 718.6ms
Speed: 4.2ms preprocess, 718.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 704.0ms
Speed: 4.0ms preprocess, 704.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 1106.1ms
Speed: 4.3ms preprocess, 1106.1ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 1162.0ms
Speed: 4.4ms preprocess, 1162.0ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 757.0ms
Speed: 3.9ms preprocess, 757.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 725.7ms
Speed: 3.8ms preprocess, 725.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 723.8ms
Speed: 3.8ms preprocess, 723.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 704.9ms
Speed: 3.8ms preprocess, 704.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 719.7ms
Speed: 3.9ms preprocess, 719.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 720.7ms
Speed: 3.8ms preprocess, 720.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 719.1ms
Speed: 3.7ms preprocess, 719.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 704.0ms
Speed: 4.2ms preprocess, 704.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 717.3ms
Speed: 4.6ms preprocess, 717.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 720.2ms
Speed: 3.8ms preprocess, 720.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 720.2ms
Speed: 6.0ms preprocess, 720.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 706.2ms
Speed: 4.1ms preprocess, 706.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 716.9ms
Speed: 5.8ms preprocess, 716.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 973.9ms
Speed: 3.8ms preprocess, 973.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 1162.5ms
Speed: 9.1ms preprocess, 1162.5ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 866.2ms
Speed: 10.6ms preprocess, 866.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 725.4ms
Speed: 3.9ms preprocess, 725.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 706.5ms
Speed: 4.0ms preprocess, 706.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 718.0ms
Speed: 3.8ms preprocess, 718.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 716.4ms
Speed: 4.1ms preprocess, 716.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 724.1ms
Speed: 3.9ms preprocess, 724.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 717.6ms
Speed: 4.7ms preprocess, 717.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 718.0ms
Speed: 4.1ms preprocess, 718.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 716.2ms
Speed: 4.1ms preprocess, 716.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 717.3ms
Speed: 5.1ms preprocess, 717.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 706.0ms
Speed: 3.8ms preprocess, 706.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 718.3ms
Speed: 3.6ms preprocess, 718.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 714.0ms
Speed: 4.1ms preprocess, 714.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 874.7ms
Speed: 4.1ms preprocess, 874.7ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 1167.1ms
Speed: 4.1ms preprocess, 1167.1ms inference, 2.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 1004.0ms
Speed: 6.7ms preprocess, 1004.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 2 birds, 718.8ms
Speed: 4.1ms preprocess, 718.8ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 719.1ms
Speed: 4.1ms preprocess, 719.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 719.7ms
Speed: 4.5ms preprocess, 719.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 727.8ms
Speed: 4.0ms preprocess, 727.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 699.8ms
Speed: 4.0ms preprocess, 699.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 725.6ms
Speed: 4.4ms preprocess, 725.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 723.4ms
Speed: 4.0ms preprocess, 723.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 723.8ms
Speed: 4.3ms preprocess, 723.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 698.9ms
Speed: 4.0ms preprocess, 698.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 726.3ms
Speed: 4.0ms preprocess, 726.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 719.9ms
Speed: 4.1ms preprocess, 719.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 712.6ms
Speed: 4.2ms preprocess, 712.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 774.9ms
Speed: 4.0ms preprocess, 774.9ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1141.8ms
Speed: 4.1ms preprocess, 1141.8ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 1086.9ms
Speed: 8.9ms preprocess, 1086.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 719.1ms
Speed: 3.9ms preprocess, 719.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 720.6ms
Speed: 3.9ms preprocess, 720.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 726.0ms
Speed: 4.2ms preprocess, 726.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 710.7ms
Speed: 4.3ms preprocess, 710.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 727.8ms
Speed: 4.3ms preprocess, 727.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 715.9ms
Speed: 3.9ms preprocess, 715.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 728.0ms
Speed: 5.0ms preprocess, 728.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 712.3ms
Speed: 4.1ms preprocess, 712.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 718.5ms
Speed: 4.0ms preprocess, 718.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 717.9ms
Speed: 3.9ms preprocess, 717.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 714.7ms
Speed: 4.1ms preprocess, 714.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 717.4ms
Speed: 4.1ms preprocess, 717.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 731.8ms
Speed: 4.5ms preprocess, 731.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1142.2ms
Speed: 7.0ms preprocess, 1142.2ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 1164.4ms
Speed: 4.0ms preprocess, 1164.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 722.6ms
Speed: 3.5ms preprocess, 722.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 721.3ms
Speed: 4.3ms preprocess, 721.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 704.7ms
Speed: 3.9ms preprocess, 704.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 721.4ms
Speed: 3.7ms preprocess, 721.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 718.1ms
Speed: 3.9ms preprocess, 718.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 719.6ms
Speed: 3.9ms preprocess, 719.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 701.1ms
Speed: 4.0ms preprocess, 701.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 721.6ms
Speed: 3.6ms preprocess, 721.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 743.4ms
Speed: 4.1ms preprocess, 743.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 713.6ms
Speed: 4.0ms preprocess, 713.6ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 709.9ms
Speed: 4.9ms preprocess, 709.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 727.0ms
Speed: 4.1ms preprocess, 727.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 722.1ms
Speed: 3.8ms preprocess, 722.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 1064.3ms
Speed: 4.0ms preprocess, 1064.3ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 1148.7ms
Speed: 6.2ms preprocess, 1148.7ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 784.9ms
Speed: 3.7ms preprocess, 784.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 708.5ms
Speed: 3.6ms preprocess, 708.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 714.5ms
Speed: 4.1ms preprocess, 714.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 715.5ms
Speed: 4.1ms preprocess, 715.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 728.9ms
Speed: 4.2ms preprocess, 728.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 703.4ms
Speed: 4.0ms preprocess, 703.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 716.5ms
Speed: 5.2ms preprocess, 716.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 713.2ms
Speed: 3.8ms preprocess, 713.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 709.3ms
Speed: 3.7ms preprocess, 709.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 717.6ms
Speed: 7.4ms preprocess, 717.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 728.8ms
Speed: 4.5ms preprocess, 728.8ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 717.3ms
Speed: 4.1ms preprocess, 717.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 709.0ms
Speed: 3.7ms preprocess, 709.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 965.7ms
Speed: 3.8ms preprocess, 965.7ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 1152.0ms
Speed: 4.1ms preprocess, 1152.0ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 910.7ms
Speed: 4.1ms preprocess, 910.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 724.7ms
Speed: 3.7ms preprocess, 724.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 718.9ms
Speed: 4.8ms preprocess, 718.9ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 729.7ms
Speed: 4.3ms preprocess, 729.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 704.7ms
Speed: 4.0ms preprocess, 704.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 723.5ms
Speed: 3.8ms preprocess, 723.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 712.3ms
Speed: 4.0ms preprocess, 712.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 706.5ms
Speed: 7.5ms preprocess, 706.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 724.7ms
Speed: 3.9ms preprocess, 724.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 731.1ms
Speed: 5.4ms preprocess, 731.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 721.7ms
Speed: 4.3ms preprocess, 721.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 705.7ms
Speed: 4.3ms preprocess, 705.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 724.0ms
Speed: 4.6ms preprocess, 724.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 876.7ms
Speed: 4.2ms preprocess, 876.7ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 1161.7ms
Speed: 4.7ms preprocess, 1161.7ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 1011.0ms
Speed: 4.1ms preprocess, 1011.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 719.8ms
Speed: 4.2ms preprocess, 719.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 726.3ms
Speed: 4.7ms preprocess, 726.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 708.2ms
Speed: 4.5ms preprocess, 708.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 718.7ms
Speed: 4.5ms preprocess, 718.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 714.4ms
Speed: 4.0ms preprocess, 714.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 724.6ms
Speed: 4.5ms preprocess, 724.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 709.3ms
Speed: 4.0ms preprocess, 709.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 737.3ms
Speed: 3.8ms preprocess, 737.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)


              idf1      mota      motp  num_switches
Tracking  0.898999  0.768946  0.785607            34

In [ ]:
run_ocsort_save_json(model, "/content/desert_birds.mp4", "output_desert_birds.mp4", "desert_birds_results.json")
convert_json_to_mot("desert_birds_results.json", "desert_birds_results.txt")
convert_json_to_mot("/content/gt_desert_annotations.json", "/content/gt_desert_annotations.txt")
compute_tracking_metrics("/content/gt_desert_annotations.txt", "desert_birds_results.txt")

0: 384x640 5 birds, 752.8ms
Speed: 7.8ms preprocess, 752.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 741.6ms
Speed: 4.9ms preprocess, 741.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 753.6ms
Speed: 4.7ms preprocess, 753.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 750.3ms
Speed: 4.6ms preprocess, 750.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 757.6ms
Speed: 4.7ms preprocess, 757.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 760.5ms
Speed: 4.2ms preprocess, 760.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 755.0ms
Speed: 4.2ms preprocess, 755.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 748.7ms
Speed: 3.9ms preprocess, 748.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 973.7ms
Speed: 3.8ms preprocess, 973.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 1221.7ms
Speed: 4.2ms preprocess, 1221.7ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 890.5ms
Speed: 6.7ms preprocess, 890.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 756.9ms
Speed: 4.2ms preprocess, 756.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 738.6ms
Speed: 5.2ms preprocess, 738.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 768.7ms
Speed: 4.2ms preprocess, 768.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 759.8ms
Speed: 4.1ms preprocess, 759.8ms inference, 2.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 761.3ms
Speed: 4.2ms preprocess, 761.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 769.9ms
Speed: 4.2ms preprocess, 769.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 776.8ms
Speed: 4.3ms preprocess, 776.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 748.5ms
Speed: 4.3ms preprocess, 748.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 794.9ms
Speed: 5.6ms preprocess, 794.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 805.5ms
Speed: 5.1ms preprocess, 805.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 828.1ms
Speed: 4.4ms preprocess, 828.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 1203.0ms
Speed: 4.3ms preprocess, 1203.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 1071.7ms
Speed: 4.6ms preprocess, 1071.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 761.5ms
Speed: 4.3ms preprocess, 761.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 767.0ms
Speed: 4.0ms preprocess, 767.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 758.8ms
Speed: 4.0ms preprocess, 758.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 763.9ms
Speed: 4.5ms preprocess, 763.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 736.0ms
Speed: 4.3ms preprocess, 736.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 759.1ms
Speed: 4.2ms preprocess, 759.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 751.8ms
Speed: 4.3ms preprocess, 751.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 771.6ms
Speed: 4.2ms preprocess, 771.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 755.4ms
Speed: 4.3ms preprocess, 755.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 756.4ms
Speed: 6.6ms preprocess, 756.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 742.9ms
Speed: 4.7ms preprocess, 742.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 1063.3ms
Speed: 4.1ms preprocess, 1063.3ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 1165.0ms
Speed: 4.4ms preprocess, 1165.0ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 777.0ms
Speed: 4.6ms preprocess, 777.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 750.7ms
Speed: 4.2ms preprocess, 750.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 755.9ms
Speed: 4.4ms preprocess, 755.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 749.1ms
Speed: 4.4ms preprocess, 749.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 778.1ms
Speed: 4.7ms preprocess, 778.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 743.3ms
Speed: 4.4ms preprocess, 743.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 764.5ms
Speed: 3.9ms preprocess, 764.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 735.7ms
Speed: 4.1ms preprocess, 735.7ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 748.7ms
Speed: 4.0ms preprocess, 748.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 765.6ms
Speed: 3.9ms preprocess, 765.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 765.3ms
Speed: 4.9ms preprocess, 765.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 837.8ms
Speed: 4.4ms preprocess, 837.8ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1213.5ms
Speed: 7.2ms preprocess, 1213.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1049.9ms
Speed: 4.2ms preprocess, 1049.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 759.1ms
Speed: 4.4ms preprocess, 759.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 788.1ms
Speed: 4.6ms preprocess, 788.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 760.9ms
Speed: 4.2ms preprocess, 760.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 762.6ms
Speed: 4.0ms preprocess, 762.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 747.9ms
Speed: 5.7ms preprocess, 747.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 747.6ms
Speed: 4.5ms preprocess, 747.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 773.3ms
Speed: 4.2ms preprocess, 773.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 762.5ms
Speed: 4.3ms preprocess, 762.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 758.8ms
Speed: 4.4ms preprocess, 758.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 744.4ms
Speed: 7.2ms preprocess, 744.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 756.5ms
Speed: 4.4ms preprocess, 756.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 1090.6ms
Speed: 5.0ms preprocess, 1090.6ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 1208.1ms
Speed: 5.6ms preprocess, 1208.1ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 795.7ms
Speed: 7.2ms preprocess, 795.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 751.5ms
Speed: 4.4ms preprocess, 751.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 745.6ms
Speed: 4.3ms preprocess, 745.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 766.4ms
Speed: 4.2ms preprocess, 766.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 755.6ms
Speed: 5.4ms preprocess, 755.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 761.7ms
Speed: 4.4ms preprocess, 761.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 768.8ms
Speed: 5.1ms preprocess, 768.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 748.8ms
Speed: 5.7ms preprocess, 748.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 756.6ms
Speed: 4.7ms preprocess, 756.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 772.0ms
Speed: 4.3ms preprocess, 772.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 777.3ms
Speed: 4.4ms preprocess, 777.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 891.8ms
Speed: 4.8ms preprocess, 891.8ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 1209.2ms
Speed: 5.8ms preprocess, 1209.2ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 1015.2ms
Speed: 6.9ms preprocess, 1015.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 774.8ms
Speed: 4.6ms preprocess, 774.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 762.3ms
Speed: 4.4ms preprocess, 762.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 760.2ms
Speed: 4.3ms preprocess, 760.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 birds, 745.3ms
Speed: 5.1ms preprocess, 745.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 752.9ms
Speed: 4.4ms preprocess, 752.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 760.9ms
Speed: 4.3ms preprocess, 760.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 768.8ms
Speed: 4.8ms preprocess, 768.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 790.9ms
Speed: 5.4ms preprocess, 790.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 757.4ms
Speed: 4.2ms preprocess, 757.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 758.2ms
Speed: 3.9ms preprocess, 758.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 735.6ms
Speed: 4.9ms preprocess, 735.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1155.5ms
Speed: 3.8ms preprocess, 1155.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 birds, 1182.6ms
Speed: 6.7ms preprocess, 1182.6ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 767.3ms
Speed: 4.3ms preprocess, 767.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 736.0ms
Speed: 4.0ms preprocess, 736.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 764.6ms
Speed: 3.9ms preprocess, 764.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 746.9ms
Speed: 4.2ms preprocess, 746.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 764.1ms
Speed: 4.2ms preprocess, 764.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 748.8ms
Speed: 4.2ms preprocess, 748.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 764.7ms
Speed: 4.0ms preprocess, 764.7ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 739.7ms
Speed: 4.8ms preprocess, 739.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 769.4ms
Speed: 4.1ms preprocess, 769.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 758.4ms
Speed: 4.7ms preprocess, 758.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 764.4ms
Speed: 4.2ms preprocess, 764.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 871.9ms
Speed: 4.2ms preprocess, 871.9ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1239.5ms
Speed: 6.0ms preprocess, 1239.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 945.4ms
Speed: 12.3ms preprocess, 945.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 774.5ms
Speed: 4.0ms preprocess, 774.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 761.5ms
Speed: 4.2ms preprocess, 761.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 764.4ms
Speed: 4.3ms preprocess, 764.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 734.8ms
Speed: 4.4ms preprocess, 734.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 766.9ms
Speed: 4.0ms preprocess, 766.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 755.3ms
Speed: 3.9ms preprocess, 755.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 776.2ms
Speed: 4.1ms preprocess, 776.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 753.6ms
Speed: 4.3ms preprocess, 753.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 759.2ms
Speed: 4.1ms preprocess, 759.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 734.3ms
Speed: 4.3ms preprocess, 734.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 765.6ms
Speed: 4.3ms preprocess, 765.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1181.2ms
Speed: 4.6ms preprocess, 1181.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1224.3ms
Speed: 5.8ms preprocess, 1224.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 745.7ms
Speed: 5.8ms preprocess, 745.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 751.7ms
Speed: 4.1ms preprocess, 751.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 753.1ms
Speed: 4.0ms preprocess, 753.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 787.9ms
Speed: 4.1ms preprocess, 787.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 746.9ms
Speed: 4.4ms preprocess, 746.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 768.7ms
Speed: 4.4ms preprocess, 768.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 762.9ms
Speed: 4.8ms preprocess, 762.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 767.0ms
Speed: 4.4ms preprocess, 767.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 762.2ms
Speed: 4.0ms preprocess, 762.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 781.3ms
Speed: 4.0ms preprocess, 781.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 753.2ms
Speed: 4.3ms preprocess, 753.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1002.3ms
Speed: 4.3ms preprocess, 1002.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1212.9ms
Speed: 4.3ms preprocess, 1212.9ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 857.1ms
Speed: 4.4ms preprocess, 857.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 763.8ms
Speed: 5.1ms preprocess, 763.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 782.2ms
Speed: 3.9ms preprocess, 782.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 765.7ms
Speed: 4.0ms preprocess, 765.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 765.6ms
Speed: 4.3ms preprocess, 765.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 757.5ms
Speed: 5.5ms preprocess, 757.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 755.9ms
Speed: 4.3ms preprocess, 755.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 769.0ms
Speed: 4.2ms preprocess, 769.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 777.1ms
Speed: 4.3ms preprocess, 777.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 755.6ms
Speed: 4.0ms preprocess, 755.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 740.6ms
Speed: 4.2ms preprocess, 740.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 817.4ms
Speed: 8.3ms preprocess, 817.4ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1222.1ms
Speed: 4.1ms preprocess, 1222.1ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1028.1ms
Speed: 4.3ms preprocess, 1028.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 732.5ms
Speed: 4.3ms preprocess, 732.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 745.1ms
Speed: 3.9ms preprocess, 745.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 762.0ms
Speed: 5.8ms preprocess, 762.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 753.2ms
Speed: 4.3ms preprocess, 753.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 752.4ms
Speed: 4.0ms preprocess, 752.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 764.3ms
Speed: 8.3ms preprocess, 764.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 752.8ms
Speed: 4.5ms preprocess, 752.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 749.0ms
Speed: 5.4ms preprocess, 749.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 752.7ms
Speed: 4.9ms preprocess, 752.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 765.5ms
Speed: 4.6ms preprocess, 765.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 764.2ms
Speed: 4.3ms preprocess, 764.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 1072.2ms
Speed: 4.2ms preprocess, 1072.2ms inference, 3.4ms postprocess per image at shape (1, 3, 384, 640)


              idf1     mota     motp  num_switches
Tracking  0.876839  0.90625  0.20997             8

**our trained model :**

In [37]:
model=YOLO("/content/bird-detection-tracking/bestbirdsonly.pt")

In [ ]:
run_ocsort_save_json(model, "/content/birds_sky.mp4", "output_birds_sky.mp4", "birds_sky_results.json")
convert_json_to_mot("/content/gt_birds_sky_results_yolo11x.json", "/content/birds_sky_gt.txt")
convert_json_to_mot("birds_sky_results.json", "birds_sky_results.txt")
compute_tracking_metrics("/content/birds_sky_gt.txt", "birds_sky_results.txt")

0: 384x640 6 Birds, 118.0ms
Speed: 3.3ms preprocess, 118.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 111.2ms
Speed: 4.5ms preprocess, 111.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 Birds, 159.0ms
Speed: 4.4ms preprocess, 159.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 171.0ms
Speed: 6.1ms preprocess, 171.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 177.2ms
Speed: 4.1ms preprocess, 177.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 174.8ms
Speed: 4.4ms preprocess, 174.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 171.7ms
Speed: 6.5ms preprocess, 171.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 169.1ms
Speed: 4.3ms preprocess, 169.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 163.8ms
Speed: 7.5ms preprocess, 163.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 177.2ms
Speed: 4.3ms preprocess, 177.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 175.9ms
Speed: 4.5ms preprocess, 175.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 195.1ms
Speed: 4.8ms preprocess, 195.1ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 161.9ms
Speed: 8.7ms preprocess, 161.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 108.6ms
Speed: 4.4ms preprocess, 108.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 Birds, 111.8ms
Speed: 4.2ms preprocess, 111.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 111.6ms
Speed: 4.3ms preprocess, 111.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 113.6ms
Speed: 4.0ms preprocess, 113.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 Birds, 110.0ms
Speed: 3.9ms preprocess, 110.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 9 Birds, 114.8ms
Speed: 4.1ms preprocess, 114.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 Birds, 112.5ms
Speed: 4.2ms preprocess, 112.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 Birds, 115.0ms
Speed: 4.2ms preprocess, 115.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 112.2ms
Speed: 4.1ms preprocess, 112.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 111.1ms
Speed: 4.3ms preprocess, 111.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 111.7ms
Speed: 4.0ms preprocess, 111.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 112.7ms
Speed: 4.0ms preprocess, 112.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 111.7ms
Speed: 4.1ms preprocess, 111.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 111.2ms
Speed: 4.1ms preprocess, 111.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 113.6ms
Speed: 4.1ms preprocess, 113.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 112.3ms
Speed: 4.1ms preprocess, 112.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 111.1ms
Speed: 7.1ms preprocess, 111.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 111.3ms
Speed: 4.5ms preprocess, 111.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 107.2ms
Speed: 4.2ms preprocess, 107.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 112.4ms
Speed: 4.1ms preprocess, 112.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 107.3ms
Speed: 4.3ms preprocess, 107.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 114.0ms
Speed: 4.9ms preprocess, 114.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 109.2ms
Speed: 4.4ms preprocess, 109.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 123.5ms
Speed: 7.0ms preprocess, 123.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 111.5ms
Speed: 4.1ms preprocess, 111.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 113.8ms
Speed: 4.1ms preprocess, 113.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 113.7ms
Speed: 4.0ms preprocess, 113.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 111.9ms
Speed: 4.3ms preprocess, 111.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 114.7ms
Speed: 4.5ms preprocess, 114.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 114.0ms
Speed: 4.3ms preprocess, 114.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 116.6ms
Speed: 4.3ms preprocess, 116.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 113.2ms
Speed: 4.2ms preprocess, 113.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 112.5ms
Speed: 4.1ms preprocess, 112.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 110.2ms
Speed: 4.5ms preprocess, 110.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 108.5ms
Speed: 4.4ms preprocess, 108.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 Birds, 110.9ms
Speed: 4.6ms preprocess, 110.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 Birds, 109.8ms
Speed: 4.4ms preprocess, 109.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 126.1ms
Speed: 11.2ms preprocess, 126.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 113.1ms
Speed: 4.4ms preprocess, 113.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 115.2ms
Speed: 4.4ms preprocess, 115.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 111.0ms
Speed: 4.4ms preprocess, 111.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 116.7ms
Speed: 4.3ms preprocess, 116.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 114.8ms
Speed: 4.4ms preprocess, 114.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 112.4ms
Speed: 4.4ms preprocess, 112.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 115.7ms
Speed: 5.9ms preprocess, 115.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 111.1ms
Speed: 4.1ms preprocess, 111.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 110.7ms
Speed: 4.4ms preprocess, 110.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 112.4ms
Speed: 4.3ms preprocess, 112.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 112.6ms
Speed: 4.5ms preprocess, 112.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 112.1ms
Speed: 4.4ms preprocess, 112.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 107.9ms
Speed: 4.3ms preprocess, 107.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 123.7ms
Speed: 5.9ms preprocess, 123.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 115.8ms
Speed: 4.6ms preprocess, 115.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 109.4ms
Speed: 7.4ms preprocess, 109.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 111.2ms
Speed: 4.1ms preprocess, 111.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 109.3ms
Speed: 4.5ms preprocess, 109.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 108.6ms
Speed: 4.7ms preprocess, 108.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 Birds, 111.6ms
Speed: 4.4ms preprocess, 111.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 115.9ms
Speed: 4.3ms preprocess, 115.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 113.0ms
Speed: 4.3ms preprocess, 113.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 110.7ms
Speed: 4.4ms preprocess, 110.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 114.6ms
Speed: 4.2ms preprocess, 114.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 113.7ms
Speed: 4.1ms preprocess, 113.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 114.6ms
Speed: 4.1ms preprocess, 114.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 115.0ms
Speed: 4.0ms preprocess, 115.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 115.5ms
Speed: 4.5ms preprocess, 115.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 122.3ms
Speed: 3.9ms preprocess, 122.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 173.4ms
Speed: 4.1ms preprocess, 173.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 178.3ms
Speed: 7.0ms preprocess, 178.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 167.8ms
Speed: 5.4ms preprocess, 167.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 173.7ms
Speed: 4.9ms preprocess, 173.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 173.1ms
Speed: 4.4ms preprocess, 173.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 171.0ms
Speed: 5.4ms preprocess, 171.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 166.7ms
Speed: 4.3ms preprocess, 166.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 169.7ms
Speed: 4.5ms preprocess, 169.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 171.9ms
Speed: 6.5ms preprocess, 171.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 179.4ms
Speed: 4.3ms preprocess, 179.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 176.6ms
Speed: 6.3ms preprocess, 176.6ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 120.5ms
Speed: 5.5ms preprocess, 120.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 112.8ms
Speed: 4.1ms preprocess, 112.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 112.8ms
Speed: 3.9ms preprocess, 112.8ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 115.0ms
Speed: 4.0ms preprocess, 115.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 114.8ms
Speed: 3.9ms preprocess, 114.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 115.0ms
Speed: 4.2ms preprocess, 115.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 114.4ms
Speed: 3.9ms preprocess, 114.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 134.3ms
Speed: 4.2ms preprocess, 134.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 110.1ms
Speed: 4.3ms preprocess, 110.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 116.2ms
Speed: 4.0ms preprocess, 116.2ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 111.0ms
Speed: 4.2ms preprocess, 111.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 112.0ms
Speed: 4.3ms preprocess, 112.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 115.0ms
Speed: 4.2ms preprocess, 115.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 116.1ms
Speed: 3.9ms preprocess, 116.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 114.2ms
Speed: 3.9ms preprocess, 114.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 114.2ms
Speed: 4.8ms preprocess, 114.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 129.9ms
Speed: 4.5ms preprocess, 129.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 115.9ms
Speed: 4.5ms preprocess, 115.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 110.5ms
Speed: 4.4ms preprocess, 110.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 114.4ms
Speed: 3.8ms preprocess, 114.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 111.2ms
Speed: 3.8ms preprocess, 111.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 110.2ms
Speed: 3.9ms preprocess, 110.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 111.5ms
Speed: 3.8ms preprocess, 111.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 123.8ms
Speed: 4.3ms preprocess, 123.8ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 110.2ms
Speed: 4.3ms preprocess, 110.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 111.0ms
Speed: 4.3ms preprocess, 111.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 111.1ms
Speed: 4.4ms preprocess, 111.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 114.7ms
Speed: 3.9ms preprocess, 114.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 111.4ms
Speed: 3.9ms preprocess, 111.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 112.4ms
Speed: 3.9ms preprocess, 112.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 118.8ms
Speed: 4.3ms preprocess, 118.8ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 111.3ms
Speed: 3.8ms preprocess, 111.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 112.4ms
Speed: 5.1ms preprocess, 112.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 113.1ms
Speed: 4.0ms preprocess, 113.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 115.4ms
Speed: 4.3ms preprocess, 115.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 112.1ms
Speed: 4.6ms preprocess, 112.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 109.5ms
Speed: 4.3ms preprocess, 109.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 126.2ms
Speed: 4.4ms preprocess, 126.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 113.6ms
Speed: 4.6ms preprocess, 113.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 113.2ms
Speed: 4.0ms preprocess, 113.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 111.4ms
Speed: 4.6ms preprocess, 111.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 115.8ms
Speed: 3.8ms preprocess, 115.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 112.5ms
Speed: 4.5ms preprocess, 112.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 110.0ms
Speed: 4.3ms preprocess, 110.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 122.8ms
Speed: 4.3ms preprocess, 122.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 115.0ms
Speed: 4.3ms preprocess, 115.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 113.8ms
Speed: 4.0ms preprocess, 113.8ms inference, 0.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 109.5ms
Speed: 3.9ms preprocess, 109.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 111.2ms
Speed: 3.8ms preprocess, 111.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 112.6ms
Speed: 4.4ms preprocess, 112.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 112.7ms
Speed: 4.3ms preprocess, 112.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 124.3ms
Speed: 4.3ms preprocess, 124.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 117.5ms
Speed: 4.1ms preprocess, 117.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 112.3ms
Speed: 3.9ms preprocess, 112.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 111.1ms
Speed: 4.3ms preprocess, 111.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 109.3ms
Speed: 4.6ms preprocess, 109.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 108.2ms
Speed: 4.3ms preprocess, 108.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 115.2ms
Speed: 4.0ms preprocess, 115.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 124.2ms
Speed: 4.7ms preprocess, 124.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 115.3ms
Speed: 6.8ms preprocess, 115.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 117.6ms
Speed: 4.5ms preprocess, 117.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 117.7ms
Speed: 4.1ms preprocess, 117.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 111.7ms
Speed: 4.3ms preprocess, 111.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 110.9ms
Speed: 4.7ms preprocess, 110.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 110.8ms
Speed: 4.3ms preprocess, 110.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 124.8ms
Speed: 4.3ms preprocess, 124.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 114.6ms

              idf1      mota      motp  num_switches
Tracking  0.949387  0.955404  0.272833             5

In [ ]:
run_ocsort_save_json(model, "similar_birds.mp4", "output_similar_birds.mp4", "similar_birds_results.json",  OCSort(
    det_thresh=0.4,
    max_age=50,
    min_hits=4,
    iou_threshold=0.3,
    delta_t=3,
    inertia=0.4,
    asso_func="iou"
))
convert_json_to_mot("/content/annotations_gt_SB.json", "/content/annotations_gt_SB.txt")
convert_json_to_mot("similar_birds_results.json", "similar_birds_results.txt")
compute_tracking_metrics("annotations_gt_SB.txt", "similar_birds_results.txt")

0: 384x640 5 Birds, 129.9ms
Speed: 4.2ms preprocess, 129.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 111.9ms
Speed: 4.5ms preprocess, 111.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 133.8ms
Speed: 4.6ms preprocess, 133.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 124.9ms
Speed: 4.3ms preprocess, 124.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 128.5ms
Speed: 4.3ms preprocess, 128.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 129.4ms
Speed: 5.6ms preprocess, 129.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 126.9ms
Speed: 4.4ms preprocess, 126.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 125.6ms
Speed: 4.3ms preprocess, 125.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 130.2ms
Speed: 5.6ms preprocess, 130.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 141.6ms
Speed: 4.5ms preprocess, 141.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 124.2ms
Speed: 4.5ms preprocess, 124.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 129.6ms
Speed: 4.5ms preprocess, 129.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 126.0ms
Speed: 4.4ms preprocess, 126.0ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 128.6ms
Speed: 4.4ms preprocess, 128.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 144.6ms
Speed: 5.0ms preprocess, 144.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 127.6ms
Speed: 4.4ms preprocess, 127.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 123.2ms
Speed: 4.7ms preprocess, 123.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 126.7ms
Speed: 5.9ms preprocess, 126.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 127.2ms
Speed: 4.4ms preprocess, 127.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 127.2ms
Speed: 4.3ms preprocess, 127.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 124.1ms
Speed: 4.3ms preprocess, 124.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 125.1ms
Speed: 4.4ms preprocess, 125.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 127.4ms
Speed: 4.5ms preprocess, 127.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 140.4ms
Speed: 4.6ms preprocess, 140.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 124.8ms
Speed: 4.3ms preprocess, 124.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 124.0ms
Speed: 4.6ms preprocess, 124.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 137.5ms
Speed: 4.4ms preprocess, 137.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 162.2ms
Speed: 4.7ms preprocess, 162.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 161.0ms
Speed: 4.3ms preprocess, 161.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 129.4ms
Speed: 4.3ms preprocess, 129.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 192.0ms
Speed: 4.5ms preprocess, 192.0ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 195.7ms
Speed: 4.3ms preprocess, 195.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 195.3ms
Speed: 11.5ms preprocess, 195.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 190.2ms
Speed: 10.4ms preprocess, 190.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 198.9ms
Speed: 6.8ms preprocess, 198.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 199.6ms
Speed: 5.7ms preprocess, 199.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 197.9ms
Speed: 4.3ms preprocess, 197.9ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 204.9ms
Speed: 7.0ms preprocess, 204.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 141.4ms
Speed: 4.7ms preprocess, 141.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 125.2ms
Speed: 4.4ms preprocess, 125.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 128.4ms
Speed: 4.1ms preprocess, 128.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 126.1ms
Speed: 4.2ms preprocess, 126.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 124.4ms
Speed: 4.5ms preprocess, 124.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 134.8ms
Speed: 4.5ms preprocess, 134.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 131.1ms
Speed: 4.4ms preprocess, 131.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 127.0ms
Speed: 4.4ms preprocess, 127.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 129.4ms
Speed: 5.2ms preprocess, 129.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 140.9ms
Speed: 4.4ms preprocess, 140.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 125.5ms
Speed: 4.4ms preprocess, 125.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 131.2ms
Speed: 4.3ms preprocess, 131.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 133.4ms
Speed: 5.3ms preprocess, 133.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 128.7ms
Speed: 4.5ms preprocess, 128.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 139.4ms
Speed: 4.3ms preprocess, 139.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.1ms
Speed: 4.4ms preprocess, 131.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 128.8ms
Speed: 4.3ms preprocess, 128.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 125.3ms
Speed: 4.3ms preprocess, 125.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 126.7ms
Speed: 4.5ms preprocess, 126.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 129.0ms
Speed: 4.4ms preprocess, 129.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 Birds, 126.8ms
Speed: 4.5ms preprocess, 126.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 128.5ms
Speed: 4.5ms preprocess, 128.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 127.1ms
Speed: 4.6ms preprocess, 127.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 140.3ms
Speed: 4.5ms preprocess, 140.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 126.4ms
Speed: 4.4ms preprocess, 126.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.1ms
Speed: 4.7ms preprocess, 131.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 128.0ms
Speed: 4.3ms preprocess, 128.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.4ms
Speed: 4.4ms preprocess, 131.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.5ms
Speed: 4.7ms preprocess, 131.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 128.4ms
Speed: 4.4ms preprocess, 128.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 128.5ms
Speed: 4.5ms preprocess, 128.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 129.1ms
Speed: 4.7ms preprocess, 129.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 139.7ms
Speed: 4.4ms preprocess, 139.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 130.6ms
Speed: 4.5ms preprocess, 130.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 134.4ms
Speed: 5.5ms preprocess, 134.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.0ms
Speed: 4.3ms preprocess, 131.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 127.9ms
Speed: 4.4ms preprocess, 127.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 154.7ms
Speed: 4.5ms preprocess, 154.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 128.4ms
Speed: 4.5ms preprocess, 128.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 128.7ms
Speed: 5.3ms preprocess, 128.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 128.2ms
Speed: 4.4ms preprocess, 128.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 135.4ms
Speed: 4.4ms preprocess, 135.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.7ms
Speed: 6.6ms preprocess, 131.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 128.6ms
Speed: 4.7ms preprocess, 128.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 188.3ms
Speed: 4.4ms preprocess, 188.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 206.3ms
Speed: 4.2ms preprocess, 206.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 195.6ms
Speed: 5.9ms preprocess, 195.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 219.7ms
Speed: 5.9ms preprocess, 219.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 212.6ms
Speed: 4.3ms preprocess, 212.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 212.6ms
Speed: 4.7ms preprocess, 212.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 226.8ms
Speed: 6.7ms preprocess, 226.8ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 193.5ms
Speed: 4.4ms preprocess, 193.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 123.7ms
Speed: 4.6ms preprocess, 123.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 128.9ms
Speed: 4.7ms preprocess, 128.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 125.3ms
Speed: 4.4ms preprocess, 125.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 130.6ms
Speed: 4.9ms preprocess, 130.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 145.5ms
Speed: 4.4ms preprocess, 145.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 123.7ms
Speed: 4.4ms preprocess, 123.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 128.0ms
Speed: 4.5ms preprocess, 128.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 128.1ms
Speed: 4.7ms preprocess, 128.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 133.4ms
Speed: 4.3ms preprocess, 133.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 149.5ms
Speed: 4.4ms preprocess, 149.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 137.7ms
Speed: 4.3ms preprocess, 137.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 129.4ms
Speed: 4.7ms preprocess, 129.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 130.3ms
Speed: 4.4ms preprocess, 130.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 130.1ms
Speed: 5.9ms preprocess, 130.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 127.5ms
Speed: 4.5ms preprocess, 127.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 129.0ms
Speed: 4.5ms preprocess, 129.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 128.1ms
Speed: 4.7ms preprocess, 128.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 132.5ms
Speed: 4.4ms preprocess, 132.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 142.4ms
Speed: 4.8ms preprocess, 142.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 129.1ms
Speed: 4.5ms preprocess, 129.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.7ms
Speed: 7.7ms preprocess, 131.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 130.1ms
Speed: 4.4ms preprocess, 130.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 133.1ms
Speed: 4.7ms preprocess, 133.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 133.2ms
Speed: 4.2ms preprocess, 133.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 129.6ms
Speed: 4.4ms preprocess, 129.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 127.3ms
Speed: 4.4ms preprocess, 127.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 125.2ms
Speed: 4.4ms preprocess, 125.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 142.3ms
Speed: 4.4ms preprocess, 142.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 129.8ms
Speed: 4.3ms preprocess, 129.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 128.5ms
Speed: 4.3ms preprocess, 128.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 130.0ms
Speed: 4.3ms preprocess, 130.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 135.0ms
Speed: 4.2ms preprocess, 135.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 144.8ms
Speed: 4.5ms preprocess, 144.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 126.8ms
Speed: 4.4ms preprocess, 126.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 129.8ms
Speed: 4.4ms preprocess, 129.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 136.5ms
Speed: 4.5ms preprocess, 136.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 143.7ms
Speed: 4.4ms preprocess, 143.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 125.2ms
Speed: 4.5ms preprocess, 125.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.2ms
Speed: 4.4ms preprocess, 131.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 131.4ms
Speed: 4.4ms preprocess, 131.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 133.3ms
Speed: 5.7ms preprocess, 133.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 147.7ms
Speed: 4.4ms preprocess, 147.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 126.4ms
Speed: 4.4ms preprocess, 126.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 144.4ms
Speed: 5.7ms preprocess, 144.4ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 204.4ms
Speed: 4.4ms preprocess, 204.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 213.2ms
Speed: 5.4ms preprocess, 213.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 212.8ms
Speed: 4.4ms preprocess, 212.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 206.7ms
Speed: 8.3ms preprocess, 206.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 202.4ms
Speed: 6.5ms preprocess, 202.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 218.8ms
Speed: 8.6ms preprocess, 218.8ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 198.2ms
Speed: 4.3ms preprocess, 198.2ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 146.1ms
Speed: 4.0ms preprocess, 146.1ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 129.7ms
Speed: 4.4ms preprocess, 129.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 126.0ms
Speed: 4.6ms preprocess, 126.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 128.2ms
Speed: 4.5ms preprocess, 128.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 130.4ms
Speed: 3.9ms preprocess, 130.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 134.1ms
Speed: 4.5ms preprocess, 134.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 126.8ms
Speed: 5.5ms preprocess, 126.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 157.1ms
Speed: 3.9ms preprocess, 157.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 128.4ms
Speed: 4.4ms preprocess, 128.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 144.6ms
Speed: 4.2ms preprocess, 144.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 130.6ms
Speed: 4.2ms preprocess, 130.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 131.5ms
Speed: 4.2ms preprocess, 131.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 131.0ms
Speed: 4.8ms preprocess, 131.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 130.4ms
Speed: 4.4ms preprocess, 130.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 144.1ms
Speed: 4.5ms preprocess, 144.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 128.3ms
Speed: 4.2ms preprocess, 128.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.5ms

              idf1      mota      motp  num_switches
Tracking  0.944882  0.953621  0.127913             6

In [ ]:
run_ocsort_save_json(model, "/content/oclusion_birds.mp4", "output_oclusion_birds.mp4", "oclusion_birds_results.json")
convert_json_to_mot("/content/occlusion_birds_gt.json", "/content/occlusion_birds_gt.txt")
convert_json_to_mot("oclusion_birds_results.json", "oclusion_birds_results.txt")
compute_tracking_metrics("/content/occlusion_birds_gt.txt", "oclusion_birds_results.txt")

0: 352x640 1 Bird, 107.3ms
Speed: 3.2ms preprocess, 107.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 122.2ms
Speed: 4.1ms preprocess, 122.2ms inference, 1.5ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 121.3ms
Speed: 4.8ms preprocess, 121.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 118.7ms
Speed: 4.3ms preprocess, 118.7ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 121.3ms
Speed: 4.1ms preprocess, 121.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 118.8ms
Speed: 4.1ms preprocess, 118.8ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 112.1ms
Speed: 4.1ms preprocess, 112.1ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 132.7ms
Speed: 4.2ms preprocess, 132.7ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 117.8ms
Speed: 3.7ms preprocess, 117.8ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 112.3ms
Speed: 4.1ms preprocess, 112.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 113.0ms
Speed: 4.1ms preprocess, 113.0ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 112.4ms
Speed: 4.1ms preprocess, 112.4ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 116.1ms
Speed: 4.2ms preprocess, 116.1ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 110.5ms
Speed: 4.1ms preprocess, 110.5ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 115.2ms
Speed: 4.3ms preprocess, 115.2ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 112.6ms
Speed: 4.0ms preprocess, 112.6ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 115.8ms
Speed: 4.1ms preprocess, 115.8ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 109.3ms
Speed: 4.0ms preprocess, 109.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 113.4ms
Speed: 4.1ms preprocess, 113.4ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 116.3ms
Speed: 4.4ms preprocess, 116.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 112.2ms
Speed: 4.0ms preprocess, 112.2ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 114.8ms
Speed: 4.2ms preprocess, 114.8ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 109.7ms
Speed: 3.9ms preprocess, 109.7ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 113.3ms
Speed: 4.0ms preprocess, 113.3ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 127.3ms
Speed: 4.1ms preprocess, 127.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 118.7ms
Speed: 4.0ms preprocess, 118.7ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 112.0ms
Speed: 4.2ms preprocess, 112.0ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 115.7ms
Speed: 4.1ms preprocess, 115.7ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 115.8ms
Speed: 4.0ms preprocess, 115.8ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 115.9ms
Speed: 3.8ms preprocess, 115.9ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 132.6ms
Speed: 4.2ms preprocess, 132.6ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 108.7ms
Speed: 4.3ms preprocess, 108.7ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 111.5ms
Speed: 5.8ms preprocess, 111.5ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 113.3ms
Speed: 4.3ms preprocess, 113.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 109.4ms
Speed: 4.0ms preprocess, 109.4ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 113.1ms
Speed: 4.2ms preprocess, 113.1ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 132.4ms
Speed: 4.1ms preprocess, 132.4ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 119.9ms
Speed: 4.0ms preprocess, 119.9ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 113.4ms
Speed: 4.2ms preprocess, 113.4ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 Birds, 112.9ms
Speed: 4.1ms preprocess, 112.9ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 114.2ms
Speed: 4.1ms preprocess, 114.2ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 114.3ms
Speed: 4.1ms preprocess, 114.3ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 112.5ms
Speed: 4.1ms preprocess, 112.5ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 114.7ms
Speed: 4.1ms preprocess, 114.7ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 114.7ms
Speed: 4.2ms preprocess, 114.7ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 111.9ms
Speed: 4.1ms preprocess, 111.9ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 135.4ms
Speed: 4.2ms preprocess, 135.4ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 178.6ms
Speed: 4.0ms preprocess, 178.6ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 185.6ms
Speed: 7.1ms preprocess, 185.6ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 174.3ms
Speed: 4.9ms preprocess, 174.3ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 169.6ms
Speed: 4.2ms preprocess, 169.6ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 193.8ms
Speed: 4.1ms preprocess, 193.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 Birds, 167.8ms
Speed: 4.3ms preprocess, 167.8ms inference, 1.5ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 182.2ms
Speed: 11.8ms preprocess, 182.2ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 176.0ms
Speed: 5.2ms preprocess, 176.0ms inference, 1.5ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 Birds, 189.2ms
Speed: 4.0ms preprocess, 189.2ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 108.1ms
Speed: 4.0ms preprocess, 108.1ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 119.2ms
Speed: 4.1ms preprocess, 119.2ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 110.2ms
Speed: 8.4ms preprocess, 110.2ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 117.3ms
Speed: 3.9ms preprocess, 117.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 Birds, 125.5ms
Speed: 4.1ms preprocess, 125.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 Birds, 121.0ms
Speed: 4.3ms preprocess, 121.0ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 113.7ms
Speed: 3.9ms preprocess, 113.7ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 113.7ms
Speed: 4.1ms preprocess, 113.7ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 111.5ms
Speed: 4.1ms preprocess, 111.5ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 116.2ms
Speed: 4.4ms preprocess, 116.2ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 124.2ms
Speed: 5.0ms preprocess, 124.2ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 115.3ms
Speed: 4.1ms preprocess, 115.3ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 Bird, 109.8ms
Speed: 4.1ms preprocess, 109.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 Birds, 112.9ms
Speed: 4.1ms preprocess, 112.9ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 4 Birds, 126.1ms
Speed: 4.2ms preprocess, 126.1ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 5 Birds, 111.3ms
Speed: 4.1ms preprocess, 111.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 Birds, 135.5ms
Speed: 4.1ms preprocess, 135.5ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 4 Birds, 117.4ms
Speed: 3.8ms preprocess, 117.4ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 4 Birds, 111.0ms
Speed: 4.1ms preprocess, 111.0ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 4 Birds, 119.3ms
Speed: 4.1ms preprocess, 119.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 Birds, 117.5ms
Speed: 4.1ms preprocess, 117.5ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 Birds, 115.9ms
Speed: 4.8ms preprocess, 115.9ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 Birds, 109.8ms
Speed: 5.1ms preprocess, 109.8ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 114.5ms
Speed: 3.9ms preprocess, 114.5ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 114.4ms
Speed: 4.2ms preprocess, 114.4ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 109.0ms
Speed: 4.0ms preprocess, 109.0ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 111.7ms
Speed: 4.1ms preprocess, 111.7ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 128.0ms
Speed: 4.1ms preprocess, 128.0ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 109.6ms
Speed: 4.1ms preprocess, 109.6ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 120.3ms
Speed: 4.2ms preprocess, 120.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 109.9ms
Speed: 4.1ms preprocess, 109.9ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 117.8ms
Speed: 4.1ms preprocess, 117.8ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 111.6ms
Speed: 4.0ms preprocess, 111.6ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 124.8ms
Speed: 4.1ms preprocess, 124.8ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 112.0ms
Speed: 4.1ms preprocess, 112.0ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 113.6ms
Speed: 4.1ms preprocess, 113.6ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 116.4ms
Speed: 4.2ms preprocess, 116.4ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 113.8ms
Speed: 4.0ms preprocess, 113.8ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 115.5ms
Speed: 3.9ms preprocess, 115.5ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 130.8ms
Speed: 4.0ms preprocess, 130.8ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 110.5ms
Speed: 4.4ms preprocess, 110.5ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 110.8ms
Speed: 4.1ms preprocess, 110.8ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 113.6ms
Speed: 4.2ms preprocess, 113.6ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 119.6ms
Speed: 4.3ms preprocess, 119.6ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 109.1ms
Speed: 4.0ms preprocess, 109.1ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 126.0ms
Speed: 5.2ms preprocess, 126.0ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 113.9ms
Speed: 4.1ms preprocess, 113.9ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 111.7ms
Speed: 3.9ms preprocess, 111.7ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 115.3ms
Speed: 4.2ms preprocess, 115.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 110.3ms
Speed: 4.0ms preprocess, 110.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 114.9ms
Speed: 4.0ms preprocess, 114.9ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 107.0ms
Speed: 4.0ms preprocess, 107.0ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 111.0ms
Speed: 4.1ms preprocess, 111.0ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 114.0ms
Speed: 4.1ms preprocess, 114.0ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 113.3ms
Speed: 4.4ms preprocess, 113.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 129.2ms
Speed: 4.0ms preprocess, 129.2ms inference, 1.7ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 188.6ms
Speed: 4.3ms preprocess, 188.6ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 171.1ms
Speed: 4.3ms preprocess, 171.1ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 176.2ms
Speed: 3.7ms preprocess, 176.2ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 157.1ms
Speed: 4.0ms preprocess, 157.1ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 197.8ms
Speed: 4.2ms preprocess, 197.8ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 163.2ms
Speed: 5.9ms preprocess, 163.2ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 186.6ms
Speed: 4.4ms preprocess, 186.6ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 187.7ms
Speed: 4.4ms preprocess, 187.7ms inference, 1.5ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 179.0ms
Speed: 4.5ms preprocess, 179.0ms inference, 1.5ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 174.4ms
Speed: 3.8ms preprocess, 174.4ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 117.2ms
Speed: 4.0ms preprocess, 117.2ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 116.1ms
Speed: 4.1ms preprocess, 116.1ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 111.9ms
Speed: 4.1ms preprocess, 111.9ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 114.2ms
Speed: 4.0ms preprocess, 114.2ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 132.0ms
Speed: 4.0ms preprocess, 132.0ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 111.5ms
Speed: 4.2ms preprocess, 111.5ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 111.4ms
Speed: 4.5ms preprocess, 111.4ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 116.7ms
Speed: 4.2ms preprocess, 116.7ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 108.0ms
Speed: 4.1ms preprocess, 108.0ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 111.7ms
Speed: 4.1ms preprocess, 111.7ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 122.6ms
Speed: 4.1ms preprocess, 122.6ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 117.8ms
Speed: 4.4ms preprocess, 117.8ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 110.9ms
Speed: 4.1ms preprocess, 110.9ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 115.6ms
Speed: 4.0ms preprocess, 115.6ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 116.4ms
Speed: 4.1ms preprocess, 116.4ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 113.6ms
Speed: 4.9ms preprocess, 113.6ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 120.0ms
Speed: 5.2ms preprocess, 120.0ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 122.5ms
Speed: 4.5ms preprocess, 122.5ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 114.2ms
Speed: 4.1ms preprocess, 114.2ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 106.6ms
Speed: 3.9ms preprocess, 106.6ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 125.2ms
Speed: 4.1ms preprocess, 125.2ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 112.9ms
Speed: 4.1ms preprocess, 112.9ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 111.6ms
Speed: 5.9ms preprocess, 111.6ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 116.4ms
Speed: 4.1ms preprocess, 116.4ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 109.4ms
Speed: 4.0ms preprocess, 109.4ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 116.3ms
Speed: 4.1ms preprocess, 116.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 107.3ms
Speed: 4.0ms preprocess, 107.3ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 126.9ms
Speed: 4.8ms preprocess, 126.9ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 109.6ms
Speed: 4.0ms preprocess, 109.6ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 112.6ms
Speed: 4.0ms preprocess, 112.6ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 113.7ms
Speed: 4.1ms preprocess, 113.7ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 106.7ms
Speed: 3.9ms preprocess, 106.7ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 111.5ms
Speed: 4.0ms preprocess, 111.5ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 123.8ms
Speed: 3.9ms preprocess, 123.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 125.0ms
Speed: 3.9ms preprocess, 125.0ms inference, 1.0ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 Birds, 111.9ms

              idf1      mota      motp  num_switches
Tracking  0.926332  0.890323  0.167798             2

In [ ]:
run_ocsort_save_json(model, "/content/birds_beach.mp4", "output_birds_beach.mp4", "birds_beach_results.json")

convert_json_to_mot("birds_beach_results.json", "birds_beach_results.txt") # bb
convert_json_to_mot("/content/bb_gt_output.json", "/content/bb_gt_output.txt") # bb gt

compute_tracking_metrics("/content/bb_gt_output.txt", "birds_beach_results.txt") #compare

0: 384x640 2 Birds, 119.8ms
Speed: 5.5ms preprocess, 119.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 116.2ms
Speed: 4.0ms preprocess, 116.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 129.8ms
Speed: 3.9ms preprocess, 129.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.6ms
Speed: 4.1ms preprocess, 115.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 118.3ms
Speed: 4.0ms preprocess, 118.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 Bird, 123.3ms
Speed: 4.1ms preprocess, 123.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 116.5ms
Speed: 4.4ms preprocess, 116.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 114.3ms
Speed: 4.3ms preprocess, 114.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 118.2ms
Speed: 4.6ms preprocess, 118.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 111.2ms
Speed: 4.6ms preprocess, 111.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 113.9ms
Speed: 4.2ms preprocess, 113.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 117.3ms
Speed: 4.2ms preprocess, 117.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 118.8ms
Speed: 4.2ms preprocess, 118.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 118.4ms
Speed: 4.3ms preprocess, 118.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 116.5ms
Speed: 4.5ms preprocess, 116.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 133.1ms
Speed: 3.9ms preprocess, 133.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 Bird, 116.5ms
Speed: 4.4ms preprocess, 116.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 113.7ms
Speed: 4.6ms preprocess, 113.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 118.2ms
Speed: 4.5ms preprocess, 118.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 114.0ms
Speed: 4.3ms preprocess, 114.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 117.2ms
Speed: 4.2ms preprocess, 117.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.6ms
Speed: 4.4ms preprocess, 115.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 130.5ms
Speed: 4.4ms preprocess, 130.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 117.3ms
Speed: 4.2ms preprocess, 117.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 120.4ms
Speed: 4.2ms preprocess, 120.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 117.5ms
Speed: 4.4ms preprocess, 117.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 117.5ms
Speed: 4.5ms preprocess, 117.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.0ms
Speed: 4.4ms preprocess, 115.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 119.7ms
Speed: 4.6ms preprocess, 119.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 120.9ms
Speed: 4.8ms preprocess, 120.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 117.2ms
Speed: 4.5ms preprocess, 117.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 123.6ms
Speed: 4.3ms preprocess, 123.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 116.4ms
Speed: 4.3ms preprocess, 116.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 114.1ms
Speed: 4.3ms preprocess, 114.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 119.6ms
Speed: 4.4ms preprocess, 119.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 131.5ms
Speed: 4.4ms preprocess, 131.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 117.8ms
Speed: 4.3ms preprocess, 117.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 119.7ms
Speed: 4.3ms preprocess, 119.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 115.9ms
Speed: 4.5ms preprocess, 115.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.0ms
Speed: 4.8ms preprocess, 115.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 114.0ms
Speed: 4.8ms preprocess, 114.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.8ms
Speed: 4.3ms preprocess, 115.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 135.2ms
Speed: 4.0ms preprocess, 135.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 118.3ms
Speed: 3.8ms preprocess, 118.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.2ms
Speed: 4.0ms preprocess, 115.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 117.7ms
Speed: 4.3ms preprocess, 117.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 116.2ms
Speed: 4.5ms preprocess, 116.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 114.6ms
Speed: 4.6ms preprocess, 114.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 114.6ms
Speed: 4.2ms preprocess, 114.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 128.2ms
Speed: 8.6ms preprocess, 128.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 121.5ms
Speed: 3.7ms preprocess, 121.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 114.8ms
Speed: 4.3ms preprocess, 114.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 113.1ms
Speed: 4.4ms preprocess, 113.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 171.9ms
Speed: 5.2ms preprocess, 171.9ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 183.4ms
Speed: 4.2ms preprocess, 183.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 183.5ms
Speed: 4.5ms preprocess, 183.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 172.9ms
Speed: 4.3ms preprocess, 172.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 167.8ms
Speed: 6.2ms preprocess, 167.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 170.6ms
Speed: 4.0ms preprocess, 170.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 174.1ms
Speed: 4.4ms preprocess, 174.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 180.1ms
Speed: 4.5ms preprocess, 180.1ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 174.2ms
Speed: 4.4ms preprocess, 174.2ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 181.1ms
Speed: 4.2ms preprocess, 181.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 183.3ms
Speed: 9.5ms preprocess, 183.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 132.5ms
Speed: 4.3ms preprocess, 132.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 113.9ms
Speed: 4.3ms preprocess, 113.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.4ms
Speed: 4.6ms preprocess, 115.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.0ms
Speed: 4.1ms preprocess, 115.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 116.7ms
Speed: 4.6ms preprocess, 116.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.6ms
Speed: 4.2ms preprocess, 115.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 117.2ms
Speed: 4.1ms preprocess, 117.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 133.6ms
Speed: 4.3ms preprocess, 133.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.2ms
Speed: 4.3ms preprocess, 115.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 117.6ms
Speed: 4.0ms preprocess, 117.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 119.0ms
Speed: 4.0ms preprocess, 119.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 118.6ms
Speed: 4.0ms preprocess, 118.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 114.3ms
Speed: 3.9ms preprocess, 114.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 121.4ms
Speed: 4.3ms preprocess, 121.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 117.4ms
Speed: 4.1ms preprocess, 117.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 113.3ms
Speed: 4.4ms preprocess, 113.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 115.3ms
Speed: 4.1ms preprocess, 115.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 116.7ms
Speed: 4.1ms preprocess, 116.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.5ms
Speed: 4.2ms preprocess, 115.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 114.7ms
Speed: 3.9ms preprocess, 114.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 131.7ms
Speed: 3.9ms preprocess, 131.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 114.9ms
Speed: 3.9ms preprocess, 114.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 116.4ms
Speed: 3.9ms preprocess, 116.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 115.0ms
Speed: 3.9ms preprocess, 115.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 116.9ms
Speed: 3.7ms preprocess, 116.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 115.3ms
Speed: 3.8ms preprocess, 115.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 119.9ms
Speed: 3.8ms preprocess, 119.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 126.4ms
Speed: 4.3ms preprocess, 126.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 117.5ms
Speed: 3.7ms preprocess, 117.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 117.9ms
Speed: 3.8ms preprocess, 117.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 118.2ms
Speed: 3.7ms preprocess, 118.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.2ms
Speed: 3.8ms preprocess, 115.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 121.2ms
Speed: 4.2ms preprocess, 121.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 122.9ms
Speed: 4.7ms preprocess, 122.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 130.3ms
Speed: 4.2ms preprocess, 130.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 116.7ms
Speed: 4.6ms preprocess, 116.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.3ms
Speed: 4.3ms preprocess, 115.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 116.2ms
Speed: 4.5ms preprocess, 116.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 114.1ms
Speed: 4.3ms preprocess, 114.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 Bird, 117.4ms
Speed: 4.3ms preprocess, 117.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 124.7ms
Speed: 4.7ms preprocess, 124.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 117.5ms
Speed: 4.3ms preprocess, 117.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 118.8ms
Speed: 4.2ms preprocess, 118.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 117.2ms
Speed: 4.3ms preprocess, 117.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 114.2ms
Speed: 4.2ms preprocess, 114.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 118.9ms
Speed: 4.2ms preprocess, 118.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.6ms
Speed: 4.4ms preprocess, 115.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 129.9ms
Speed: 4.1ms preprocess, 129.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 113.8ms
Speed: 4.2ms preprocess, 113.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 116.6ms
Speed: 5.3ms preprocess, 116.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 122.1ms
Speed: 4.4ms preprocess, 122.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 119.2ms
Speed: 4.2ms preprocess, 119.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 115.5ms
Speed: 4.3ms preprocess, 115.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 115.4ms
Speed: 4.3ms preprocess, 115.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 114.5ms
Speed: 10.3ms preprocess, 114.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 116.8ms
Speed: 5.0ms preprocess, 116.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 120.7ms
Speed: 5.1ms preprocess, 120.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 138.6ms
Speed: 5.0ms preprocess, 138.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 120.1ms
Speed: 3.9ms preprocess, 120.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 117.3ms
Speed: 4.2ms preprocess, 117.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 129.1ms
Speed: 4.6ms preprocess, 129.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 114.6ms
Speed: 3.8ms preprocess, 114.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 119.6ms
Speed: 5.0ms preprocess, 119.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 112.6ms
Speed: 4.3ms preprocess, 112.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 178.2ms
Speed: 4.4ms preprocess, 178.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 176.6ms
Speed: 4.3ms preprocess, 176.6ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 179.7ms
Speed: 4.3ms preprocess, 179.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 175.6ms
Speed: 4.3ms preprocess, 175.6ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 177.8ms
Speed: 4.7ms preprocess, 177.8ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 172.3ms
Speed: 6.2ms preprocess, 172.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 172.0ms
Speed: 5.0ms preprocess, 172.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 200.0ms
Speed: 4.0ms preprocess, 200.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 172.9ms
Speed: 7.9ms preprocess, 172.9ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 182.8ms
Speed: 4.8ms preprocess, 182.8ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 179.7ms
Speed: 4.7ms preprocess, 179.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 127.0ms
Speed: 4.3ms preprocess, 127.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 117.2ms
Speed: 4.3ms preprocess, 117.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 116.2ms
Speed: 4.4ms preprocess, 116.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 119.9ms
Speed: 4.4ms preprocess, 119.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 117.6ms
Speed: 4.1ms preprocess, 117.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.9ms
Speed: 4.0ms preprocess, 115.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 117.1ms
Speed: 5.2ms preprocess, 117.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 126.3ms
Speed: 4.3ms preprocess, 126.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 116.2ms
Speed: 5.6ms preprocess, 116.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 114.8ms
Speed: 4.8ms preprocess, 114.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 114.8ms
Speed: 4.4ms preprocess, 114.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 118.4ms
Speed: 4.3ms preprocess, 118.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 119.1ms
Speed: 3.8ms preprocess, 119.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 114.5ms
Speed: 4.2ms preprocess, 114.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 121.9ms
Speed: 7.2ms preprocess, 121.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 116.8ms
Speed: 4.0ms preprocess, 116.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 117.7ms
Speed: 4.0ms preprocess, 117.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 118.7ms
Speed: 3.7ms preprocess, 118.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.0ms

              idf1      mota      motp  num_switches
Tracking  0.814338  0.879852  0.244715             5

In [ ]:
run_ocsort_save_json(model, "/content/desert_birds.mp4", "output_desert_birds.mp4", "desert_birds_results.json")
convert_json_to_mot("desert_birds_results.json", "desert_birds_results.txt")
convert_json_to_mot("/content/gt_desert_annotations.json", "/content/gt_desert_annotations.txt")
compute_tracking_metrics("/content/gt_desert_annotations.txt", "desert_birds_results.txt")

0: 384x640 6 Birds, 115.4ms
Speed: 4.1ms preprocess, 115.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 132.4ms
Speed: 4.3ms preprocess, 132.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 129.2ms
Speed: 4.6ms preprocess, 129.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 148.8ms
Speed: 4.5ms preprocess, 148.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 132.3ms
Speed: 5.4ms preprocess, 132.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 131.9ms
Speed: 4.8ms preprocess, 131.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 126.0ms
Speed: 4.6ms preprocess, 126.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 129.0ms
Speed: 4.4ms preprocess, 129.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 134.0ms
Speed: 6.3ms preprocess, 134.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 130.3ms
Speed: 5.1ms preprocess, 130.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.6ms
Speed: 4.4ms preprocess, 131.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.1ms
Speed: 4.3ms preprocess, 131.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 145.8ms
Speed: 4.6ms preprocess, 145.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 132.7ms
Speed: 4.5ms preprocess, 132.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 132.1ms
Speed: 4.7ms preprocess, 132.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 128.7ms
Speed: 4.3ms preprocess, 128.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 132.8ms
Speed: 5.2ms preprocess, 132.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 196.3ms
Speed: 4.5ms preprocess, 196.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 205.2ms
Speed: 4.8ms preprocess, 205.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 217.5ms
Speed: 4.8ms preprocess, 217.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 215.2ms
Speed: 5.9ms preprocess, 215.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 204.5ms
Speed: 4.8ms preprocess, 204.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 222.7ms
Speed: 5.2ms preprocess, 222.7ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 202.8ms
Speed: 6.8ms preprocess, 202.8ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 128.2ms
Speed: 4.8ms preprocess, 128.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.2ms
Speed: 4.5ms preprocess, 131.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 136.4ms
Speed: 4.8ms preprocess, 136.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 134.6ms
Speed: 4.4ms preprocess, 134.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 Birds, 130.7ms
Speed: 4.6ms preprocess, 130.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 132.2ms
Speed: 4.6ms preprocess, 132.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 129.3ms
Speed: 5.8ms preprocess, 129.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 149.0ms
Speed: 4.4ms preprocess, 149.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 132.0ms
Speed: 4.5ms preprocess, 132.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 132.1ms
Speed: 5.8ms preprocess, 132.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 137.9ms
Speed: 4.5ms preprocess, 137.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 146.7ms
Speed: 4.8ms preprocess, 146.7ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 132.2ms
Speed: 4.5ms preprocess, 132.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.0ms
Speed: 4.4ms preprocess, 131.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 134.6ms
Speed: 4.5ms preprocess, 134.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 130.1ms
Speed: 4.5ms preprocess, 130.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 146.9ms
Speed: 5.4ms preprocess, 146.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 133.4ms
Speed: 4.4ms preprocess, 133.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.1ms
Speed: 5.0ms preprocess, 131.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 136.4ms
Speed: 4.4ms preprocess, 136.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 150.2ms
Speed: 5.2ms preprocess, 150.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 129.9ms
Speed: 4.6ms preprocess, 129.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 136.6ms
Speed: 6.2ms preprocess, 136.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 133.1ms
Speed: 4.4ms preprocess, 133.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 133.2ms
Speed: 4.4ms preprocess, 133.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 145.3ms
Speed: 5.4ms preprocess, 145.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 136.8ms
Speed: 4.4ms preprocess, 136.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 135.5ms
Speed: 7.7ms preprocess, 135.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 133.7ms
Speed: 4.5ms preprocess, 133.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 142.3ms
Speed: 5.2ms preprocess, 142.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 129.5ms
Speed: 4.5ms preprocess, 129.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 133.4ms
Speed: 4.8ms preprocess, 133.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 128.8ms
Speed: 5.5ms preprocess, 128.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 129.1ms
Speed: 4.6ms preprocess, 129.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 130.0ms
Speed: 4.5ms preprocess, 130.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 135.2ms
Speed: 4.4ms preprocess, 135.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 126.9ms
Speed: 4.7ms preprocess, 126.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 132.5ms
Speed: 4.6ms preprocess, 132.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 143.2ms
Speed: 5.5ms preprocess, 143.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 128.0ms
Speed: 4.6ms preprocess, 128.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 134.9ms
Speed: 4.6ms preprocess, 134.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 129.8ms
Speed: 4.4ms preprocess, 129.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 128.3ms
Speed: 4.6ms preprocess, 128.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 185.3ms
Speed: 5.1ms preprocess, 185.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 181.3ms
Speed: 4.5ms preprocess, 181.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 205.6ms
Speed: 11.6ms preprocess, 205.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 224.2ms
Speed: 5.1ms preprocess, 224.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 200.5ms
Speed: 11.5ms preprocess, 200.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 194.8ms
Speed: 4.4ms preprocess, 194.8ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 193.9ms
Speed: 12.6ms preprocess, 193.9ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 125.5ms
Speed: 4.5ms preprocess, 125.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 126.8ms
Speed: 4.6ms preprocess, 126.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 143.0ms
Speed: 4.4ms preprocess, 143.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 125.3ms
Speed: 4.5ms preprocess, 125.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 133.6ms
Speed: 4.1ms preprocess, 133.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 134.6ms
Speed: 5.1ms preprocess, 134.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 128.2ms
Speed: 4.5ms preprocess, 128.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 142.1ms
Speed: 4.6ms preprocess, 142.1ms inference, 0.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 138.2ms
Speed: 5.2ms preprocess, 138.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 131.4ms
Speed: 4.5ms preprocess, 131.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 128.2ms
Speed: 4.5ms preprocess, 128.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 129.4ms
Speed: 4.5ms preprocess, 129.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 129.3ms
Speed: 4.9ms preprocess, 129.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 130.9ms
Speed: 4.5ms preprocess, 130.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 129.7ms
Speed: 4.4ms preprocess, 129.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 126.3ms
Speed: 4.7ms preprocess, 126.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 144.9ms
Speed: 4.3ms preprocess, 144.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.8ms
Speed: 4.4ms preprocess, 131.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.8ms
Speed: 4.3ms preprocess, 131.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 125.8ms
Speed: 4.5ms preprocess, 125.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 133.9ms
Speed: 5.2ms preprocess, 133.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 135.2ms
Speed: 4.7ms preprocess, 135.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 131.8ms
Speed: 4.6ms preprocess, 131.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 130.2ms
Speed: 4.3ms preprocess, 130.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 128.1ms
Speed: 4.4ms preprocess, 128.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 154.7ms
Speed: 4.3ms preprocess, 154.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 131.8ms
Speed: 4.5ms preprocess, 131.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 151.6ms
Speed: 4.8ms preprocess, 151.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 129.3ms
Speed: 5.1ms preprocess, 129.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 136.7ms
Speed: 4.4ms preprocess, 136.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 129.5ms
Speed: 4.5ms preprocess, 129.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 133.5ms
Speed: 4.6ms preprocess, 133.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 132.7ms
Speed: 4.6ms preprocess, 132.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 129.4ms
Speed: 4.5ms preprocess, 129.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 143.9ms
Speed: 4.9ms preprocess, 143.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 134.1ms
Speed: 4.4ms preprocess, 134.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 128.4ms
Speed: 4.4ms preprocess, 128.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 129.6ms
Speed: 5.6ms preprocess, 129.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 144.7ms
Speed: 4.4ms preprocess, 144.7ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 129.5ms
Speed: 4.4ms preprocess, 129.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 126.3ms
Speed: 4.4ms preprocess, 126.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 126.2ms
Speed: 4.4ms preprocess, 126.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 126.8ms
Speed: 4.5ms preprocess, 126.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 218.9ms
Speed: 5.4ms preprocess, 218.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 224.8ms
Speed: 7.1ms preprocess, 224.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 210.2ms
Speed: 4.4ms preprocess, 210.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 213.9ms
Speed: 8.3ms preprocess, 213.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 206.6ms
Speed: 6.1ms preprocess, 206.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 203.8ms
Speed: 12.6ms preprocess, 203.8ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 216.2ms
Speed: 4.4ms preprocess, 216.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 154.6ms
Speed: 4.3ms preprocess, 154.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 130.6ms
Speed: 4.8ms preprocess, 130.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 124.7ms
Speed: 4.6ms preprocess, 124.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 143.7ms
Speed: 4.7ms preprocess, 143.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 125.0ms
Speed: 4.4ms preprocess, 125.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 131.5ms
Speed: 5.0ms preprocess, 131.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 134.2ms
Speed: 4.3ms preprocess, 134.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 128.6ms
Speed: 4.5ms preprocess, 128.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 131.2ms
Speed: 4.7ms preprocess, 131.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 135.2ms
Speed: 4.6ms preprocess, 135.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 131.9ms
Speed: 4.4ms preprocess, 131.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 130.1ms
Speed: 4.1ms preprocess, 130.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 145.3ms
Speed: 4.4ms preprocess, 145.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 125.7ms
Speed: 4.5ms preprocess, 125.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 129.7ms
Speed: 4.0ms preprocess, 129.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 135.4ms
Speed: 6.4ms preprocess, 135.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 127.6ms
Speed: 4.6ms preprocess, 127.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 126.3ms
Speed: 5.3ms preprocess, 126.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 133.9ms
Speed: 4.6ms preprocess, 133.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 132.9ms
Speed: 4.5ms preprocess, 132.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 128.9ms
Speed: 4.6ms preprocess, 128.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 145.9ms
Speed: 4.5ms preprocess, 145.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 125.8ms
Speed: 4.4ms preprocess, 125.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 134.9ms
Speed: 5.0ms preprocess, 134.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 124.4ms
Speed: 7.7ms preprocess, 124.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 133.3ms
Speed: 4.5ms preprocess, 133.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 127.4ms
Speed: 7.5ms preprocess, 127.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 137.7ms
Speed: 4.7ms preprocess, 137.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 128.7ms
Speed: 5.2ms preprocess, 128.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 129.4ms
Speed: 4.4ms preprocess, 129.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 145.5ms
Speed: 4.6ms preprocess, 145.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 128.7ms
Speed: 5.4ms preprocess, 128.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 130.7ms
Speed: 5.8ms preprocess, 130.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 132.5ms

              idf1     mota      motp  num_switches
Tracking  0.882203  0.91723  0.157093             8

# **Generalized function:**
same pipeline- 5 videos 3 models: 11n 11m and our pre trained

In [29]:
def run_full_tracking_pipeline(model, video_path, gt_json_path, pred_json_output_json, output_video_path=None):
    import os

    # Derive default video output path if not provided
    if output_video_path is None:
        output_video_path = f"tracked_{os.path.basename(video_path)}"

    # Derive predicted .txt output from predicted .json
    pred_txt_output = pred_json_output_json.replace(".json", ".txt")

    # Derive GT .txt output
    gt_txt_output = gt_json_path.replace(".json", ".txt")

    print("🔍 Running detection + tracking...")
    run_ocsort_save_json(model, video_path, output_video_path, pred_json_output_json)

    print("📄 Converting ground-truth annotations to MOT format...")
    convert_json_to_mot(gt_json_path, gt_txt_output)

    print("📄 Converting predictions to MOT format...")
    convert_json_to_mot(pred_json_output_json, pred_txt_output)

    print("📊 Computing tracking metrics...")
    compute_tracking_metrics(gt_txt_output, pred_txt_output)

    print("📈 Calculating mAP (COCO style)...")
    map_5095, map_50 = map_calc_coco(
        gt_json_path=gt_json_path,
        pred_json_path=pred_json_output_json,
        video_path=video_path
    )
    print(f"mAP@0.50: {map_50:.4f}")
    print(f"mAP@0.50:0.95: {map_5095:.4f}")

    print("✅ Done!")

In [ ]:
model = YOLO("yolo11n.pt")

run_full_tracking_pipeline(model, "/content/birds_sky.mp4", "/content/gt_birds_sky_results_yolo11x.json", "birds_sky_results.json")

run_full_tracking_pipeline(model, "/content/birds_beach.mp4", "/content/bb_gt_output.json", "birds_beach_results.json")

run_full_tracking_pipeline(model, "/content/oclusion_birds.mp4", "/content/occlusion_birds_gt.json", "oclusion_birds_results.json")

run_full_tracking_pipeline(model, "/content/similar_birds.mp4", "/content/annotations_gt_SB.json", "similar_birds_results.json")

run_full_tracking_pipeline(model, "/content/desert_birds.mp4", "/content/gt_desert_annotations.json", "desert_birds_results.json")

Streaming output truncated to the last 5000 lines.

0: 352x640 1 airplane, 127.1ms
Speed: 3.7ms preprocess, 127.1ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 133.8ms
Speed: 7.6ms preprocess, 133.8ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 124.7ms
Speed: 4.5ms preprocess, 124.7ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 127.3ms
Speed: 4.2ms preprocess, 127.3ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 131.0ms
Speed: 4.1ms preprocess, 131.0ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 125.8ms
Speed: 4.2ms preprocess, 125.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 124.9ms
Speed: 4.4ms preprocess, 124.9ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 122.8ms
Speed: 5.1ms preprocess, 122.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 2 birds, 115.5ms
Speed: 4.0ms preprocess, 115.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 124.9ms
Speed: 3.7ms preprocess, 124.9ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 132.9ms
Speed: 3.8ms preprocess, 132.9ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 126.4ms
Speed: 3.8ms preprocess, 126.4ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 143.8ms
Speed: 3.8ms preprocess, 143.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 120.8ms
Speed: 4.2ms preprocess, 120.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 128.1ms
Speed: 4.1ms preprocess, 128.1ms inference, 1.7ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 126.7ms
Speed: 3.8ms preprocess, 126.7ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 118.3ms
Speed: 4.2ms preprocess, 118.3ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 139.9ms
Speed: 4.2ms preprocess, 139.9ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 127.3ms
Speed: 3.8ms preprocess, 127.3ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 124.4ms
Speed: 3.9ms preprocess, 124.4ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 127.2ms
Speed: 4.2ms preprocess, 127.2ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 124.1ms
Speed: 3.6ms preprocess, 124.1ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 121.8ms
Speed: 4.2ms preprocess, 121.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 122.5ms
Speed: 7.7ms preprocess, 122.5ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 123.7ms
Speed: 5.7ms preprocess, 123.7ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 128.1ms
Speed: 4.2ms preprocess, 128.1ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 120.4ms
Speed: 5.0ms preprocess, 120.4ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 1 bird, 183.3ms
Speed: 5.9ms preprocess, 183.3ms inference, 1.8ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 4 airplanes, 180.8ms
Speed: 3.8ms preprocess, 180.8ms inference, 1.9ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 179.9ms
Speed: 9.4ms preprocess, 179.9ms inference, 3.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 193.2ms
Speed: 14.8ms preprocess, 193.2ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 177.4ms
Speed: 10.2ms preprocess, 177.4ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 180.4ms
Speed: 4.0ms preprocess, 180.4ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 191.7ms
Speed: 4.3ms preprocess, 191.7ms inference, 1.7ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 193.5ms
Speed: 4.5ms preprocess, 193.5ms inference, 2.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 205.2ms
Speed: 4.6ms preprocess, 205.2ms inference, 1.9ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 188.3ms
Speed: 4.4ms preprocess, 188.3ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 121.0ms
Speed: 4.1ms preprocess, 121.0ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 123.9ms
Speed: 3.8ms preprocess, 123.9ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 118.8ms
Speed: 3.8ms preprocess, 118.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 138.5ms
Speed: 3.7ms preprocess, 138.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 124.8ms
Speed: 3.6ms preprocess, 124.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 125.4ms
Speed: 4.0ms preprocess, 125.4ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 117.5ms
Speed: 3.7ms preprocess, 117.5ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 121.6ms
Speed: 3.8ms preprocess, 121.6ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 125.7ms
Speed: 3.8ms preprocess, 125.7ms inference, 2.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 126.0ms
Speed: 3.6ms preprocess, 126.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 kite, 121.6ms
Speed: 3.8ms preprocess, 121.6ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 1 kite, 117.9ms
Speed: 4.1ms preprocess, 117.9ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 133.6ms
Speed: 3.7ms preprocess, 133.6ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 kites, 116.4ms
Speed: 4.1ms preprocess, 116.4ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 137.1ms
Speed: 4.1ms preprocess, 137.1ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 kites, 119.3ms
Speed: 4.0ms preprocess, 119.3ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 kites, 119.0ms
Speed: 4.0ms preprocess, 119.0ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 kite, 123.8ms
Speed: 4.0ms preprocess, 123.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 kites, 115.2ms
Speed: 3.9ms preprocess, 115.2ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 kite, 126.2ms
Speed: 4.3ms preprocess, 126.2ms inference, 1.7ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 kite, 125.5ms
Speed: 6.9ms preprocess, 125.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 kite, 117.3ms
Speed: 4.4ms preprocess, 117.3ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 124.9ms
Speed: 3.8ms preprocess, 124.9ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 117.6ms
Speed: 3.9ms preprocess, 117.6ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 116.3ms
Speed: 4.1ms preprocess, 116.3ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 139.0ms
Speed: 3.9ms preprocess, 139.0ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 airplanes, 116.9ms
Speed: 4.0ms preprocess, 116.9ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 birds, 123.9ms
Speed: 4.1ms preprocess, 123.9ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 3 birds, 115.0ms
Speed: 3.9ms preprocess, 115.0ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 3 birds, 122.9ms
Speed: 4.1ms preprocess, 122.9ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 149.6ms
Speed: 4.1ms preprocess, 149.6ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 125.4ms
Speed: 4.1ms preprocess, 125.4ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 120.1ms
Speed: 4.0ms preprocess, 120.1ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 123.7ms
Speed: 4.1ms preprocess, 123.7ms inference, 2.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 126.4ms
Speed: 4.1ms preprocess, 126.4ms inference, 1.5ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 123.4ms
Speed: 4.1ms preprocess, 123.4ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 124.6ms
Speed: 4.0ms preprocess, 124.6ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 124.0ms
Speed: 3.8ms preprocess, 124.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 113.8ms
Speed: 4.1ms preprocess, 113.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 117.0ms
Speed: 4.2ms preprocess, 117.0ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 125.2ms
Speed: 4.0ms preprocess, 125.2ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 1 kite, 139.5ms
Speed: 3.9ms preprocess, 139.5ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 117.5ms
Speed: 3.7ms preprocess, 117.5ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 117.3ms
Speed: 4.0ms preprocess, 117.3ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 117.8ms
Speed: 4.2ms preprocess, 117.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 114.7ms
Speed: 4.1ms preprocess, 114.7ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 123.3ms
Speed: 3.8ms preprocess, 123.3ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 121.5ms
Speed: 4.1ms preprocess, 121.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 124.4ms
Speed: 3.8ms preprocess, 124.4ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 118.7ms
Speed: 3.8ms preprocess, 118.7ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 120.7ms
Speed: 3.9ms preprocess, 120.7ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 114.2ms
Speed: 4.1ms preprocess, 114.2ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 189.8ms
Speed: 4.1ms preprocess, 189.8ms inference, 1.8ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 192.2ms
Speed: 4.0ms preprocess, 192.2ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 183.6ms
Speed: 4.0ms preprocess, 183.6ms inference, 1.5ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 189.5ms
Speed: 4.0ms preprocess, 189.5ms inference, 1.9ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 182.0ms
Speed: 6.2ms preprocess, 182.0ms inference, 2.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 179.6ms
Speed: 7.9ms preprocess, 179.6ms inference, 1.5ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 189.6ms
Speed: 10.5ms preprocess, 189.6ms inference, 2.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 193.8ms
Speed: 11.0ms preprocess, 193.8ms inference, 1.8ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 206.5ms
Speed: 4.1ms preprocess, 206.5ms inference, 1.9ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 147.2ms
Speed: 4.7ms preprocess, 147.2ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 121.6ms
Speed: 3.7ms preprocess, 121.6ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 bird, 1 kite, 123.8ms
Speed: 3.7ms preprocess, 123.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 112.4ms
Speed: 4.0ms preprocess, 112.4ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 117.5ms
Speed: 3.9ms preprocess, 117.5ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 115.0ms
Speed: 3.6ms preprocess, 115.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 112.7ms
Speed: 4.1ms preprocess, 112.7ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 109.5ms
Speed: 4.1ms preprocess, 109.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 122.6ms
Speed: 3.7ms preprocess, 122.6ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 128.8ms
Speed: 4.1ms preprocess, 128.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 113.8ms
Speed: 4.3ms preprocess, 113.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 117.0ms
Speed: 4.0ms preprocess, 117.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 114.8ms
Speed: 4.1ms preprocess, 114.8ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 118.0ms
Speed: 3.8ms preprocess, 118.0ms inference, 1.8ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 119.5ms
Speed: 8.6ms preprocess, 119.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 123.0ms
Speed: 4.3ms preprocess, 123.0ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 116.0ms
Speed: 4.1ms preprocess, 116.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 123.8ms
Speed: 4.1ms preprocess, 123.8ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 110.5ms
Speed: 3.9ms preprocess, 110.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 119.2ms
Speed: 4.2ms preprocess, 119.2ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 115.6ms
Speed: 4.0ms preprocess, 115.6ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 116.3ms
Speed: 4.0ms preprocess, 116.3ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 113.5ms
Speed: 3.9ms preprocess, 113.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 127.2ms
Speed: 4.1ms preprocess, 127.2ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 122.2ms
Speed: 4.0ms preprocess, 122.2ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 108.7ms
Speed: 3.9ms preprocess, 108.7ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 127.6ms
Speed: 4.0ms preprocess, 127.6ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 1 bird, 111.8ms
Speed: 4.1ms preprocess, 111.8ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 1 airplane, 2 birds, 124.9ms
Speed: 4.7ms preprocess, 124.9ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 111.4ms
Speed: 9.9ms preprocess, 111.4ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 124.4ms
Speed: 4.1ms preprocess, 124.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 115.9ms
Speed: 3.9ms preprocess, 115.9ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 119.7ms
Speed: 7.7ms preprocess, 119.7ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 119.4ms
Speed: 3.9ms preprocess, 119.4ms inference, 1.1ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 111.9ms
Speed: 4.0ms preprocess, 111.9ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 120.5ms
Speed: 4.6ms preprocess, 120.5ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 115.5ms
Speed: 3.7ms preprocess, 115.5ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 121.6ms
Speed: 4.0ms preprocess, 121.6ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 115.3ms
Speed: 7.3ms preprocess, 115.3ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 121.8ms
Speed: 3.9ms preprocess, 121.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 116.0ms
Speed: 3.7ms preprocess, 116.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 120.2ms
Speed: 4.0ms preprocess, 120.2ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 115.9ms
Speed: 3.8ms preprocess, 115.9ms inference, 1.3ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 1 kite, 130.6ms
Speed: 4.0ms preprocess, 130.6ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 120.7ms
Speed: 3.7ms preprocess, 120.7ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 122.0ms
Speed: 4.0ms preprocess, 122.0ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 118.7ms
Speed: 4.0ms preprocess, 118.7ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 122.7ms
Speed: 3.8ms preprocess, 122.7ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 113.9ms
Speed: 3.8ms preprocess, 113.9ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 140.3ms
Speed: 3.8ms preprocess, 140.3ms inference, 1.5ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 111.8ms
Speed: 9.2ms preprocess, 111.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 123.0ms
Speed: 4.4ms preprocess, 123.0ms inference, 1.4ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 113.8ms
Speed: 7.3ms preprocess, 113.8ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)

0: 352x640 2 birds, 117.2ms
Speed: 4.0ms preprocess, 117.2ms inference, 1.2ms postprocess per image at shape (1, 3, 352, 640)


In [ ]:
model = YOLO("yolo11m.pt")

run_full_tracking_pipeline(model, "/content/birds_sky.mp4", "/content/gt_birds_sky_results_yolo11x.json", "birds_sky_results.json")

run_full_tracking_pipeline(model, "/content/birds_beach.mp4", "/content/bb_gt_output.json", "birds_beach_results.json")

run_full_tracking_pipeline(model, "/content/oclusion_birds.mp4", "/content/occlusion_birds_gt.json", "oclusion_birds_results.json")

run_full_tracking_pipeline(model, "/content/similar_birds.mp4", "/content/annotations_gt_SB.json", "similar_birds_results.json")

run_full_tracking_pipeline(model, "/content/desert_birds.mp4", "/content/gt_desert_annotations.json", "desert_birds_results.json")

In [ ]:
model = YOLO("/content/bestbirdsonly.pt")

run_full_tracking_pipeline(model, "/content/birds_sky.mp4", "/content/gt_birds_sky_results_yolo11x.json", "birds_sky_results.json")

run_full_tracking_pipeline(model, "/content/birds_beach.mp4", "/content/bb_gt_output.json", "birds_beach_results.json")

run_full_tracking_pipeline(model, "/content/oclusion_birds.mp4", "/content/occlusion_birds_gt.json", "oclusion_birds_results.json")

run_full_tracking_pipeline(model, "/content/similar_birds.mp4", "/content/annotations_gt_SB.json", "similar_birds_results.json")

run_full_tracking_pipeline(model, "/content/desert_birds.mp4", "/content/gt_desert_annotations.json", "desert_birds_results.json")

In [28]:
run_full_tracking_pipeline(model, "/content/videos /birds_beach_856799-hd_1920_1080_25fps.mp4", "/content/ground truth/gt_birds_beach.json", "birds_beach_results.json")

run_full_tracking_pipeline(model, "/content/videos /similar_birds_8824697-uhd_3840_2160_30fps.mp4", "/content/ground truth/gt_similar_birds.json", "similar_birds_results.json")

run_full_tracking_pipeline(model, "/content/videos /desert_birds_4438487-uhd_3840_2160_24fps.mp4", "/content/ground truth/gt_desert_birds.json", "desert_birds_results.json")

🔍 Running detection + tracking...

0: 384x640 2 birds, 134.0ms
Speed: 6.2ms preprocess, 134.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 139.7ms
Speed: 4.0ms preprocess, 139.7ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 149.7ms
Speed: 4.5ms preprocess, 149.7ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 151.6ms
Speed: 4.9ms preprocess, 151.6ms inference, 3.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 135.4ms
Speed: 6.2ms preprocess, 135.4ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 140.1ms
Speed: 4.8ms preprocess, 140.1ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 146.7ms
Speed: 4.6ms preprocess, 146.7ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 131.9ms
Speed: 4.7ms preprocess, 131.9ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 129.7ms
Speed: 8.0ms preprocess, 129.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 128.0ms
Speed: 4.8ms preprocess, 128.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 131.0ms
Speed: 5.1ms preprocess, 131.0ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 131.1ms
Speed: 4.6ms preprocess, 131.1ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 146.2ms
Speed: 4.8ms preprocess, 146.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 133.1ms
Speed: 4.7ms preprocess, 133.1ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 144.0ms
Speed: 4.5ms preprocess, 144.0ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 134.9ms
Speed: 4.8ms preprocess, 134.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 127.5ms
Speed: 4.7ms preprocess, 127.5ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 134.4ms
Speed: 6.0ms preprocess, 134.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 2 birds, 138.5ms
Speed: 4.8ms preprocess, 138.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 129.5ms
Speed: 3.3ms preprocess, 129.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 115.3ms
Speed: 5.3ms preprocess, 115.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 120.5ms
Speed: 4.2ms preprocess, 120.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 118.2ms
Speed: 4.3ms preprocess, 118.2ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 122.0ms
Speed: 4.4ms preprocess, 122.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 129.7ms
Speed: 4.6ms preprocess, 129.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 127.2ms
Speed: 4.0ms preprocess, 127.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 120.6ms
Speed: 3.8ms preprocess, 120.6ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 122.9ms
Speed: 3.8ms preprocess, 122.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 118.6ms
Speed: 3.8ms preprocess, 118.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 123.4ms
Speed: 3.9ms preprocess, 123.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 130.6ms
Speed: 3.9ms preprocess, 130.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 137.1ms
Speed: 6.4ms preprocess, 137.1ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 124.1ms
Speed: 4.2ms preprocess, 124.1ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 187.1ms
Speed: 4.0ms preprocess, 187.1ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 183.8ms
Speed: 11.0ms preprocess, 183.8ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 181.6ms
Speed: 4.3ms preprocess, 181.6ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 189.5ms
Speed: 4.8ms preprocess, 189.5ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 173.2ms
Speed: 4.3ms preprocess, 173.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 174.6ms
Speed: 4.4ms preprocess, 174.6ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 178.4ms
Speed: 5.2ms preprocess, 178.4ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 197.9ms
Speed: 4.5ms preprocess, 197.9ms inference, 2.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 180.9ms
Speed: 4.2ms preprocess, 180.9ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 184.6ms
Speed: 3.8ms preprocess, 184.6ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 173.1ms
Speed: 4.7ms preprocess, 173.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 117.7ms
Speed: 4.2ms preprocess, 117.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 134.1ms
Speed: 4.1ms preprocess, 134.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 116.5ms
Speed: 4.1ms preprocess, 116.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 122.0ms
Speed: 4.2ms preprocess, 122.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 121.0ms
Speed: 3.9ms preprocess, 121.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 125.7ms
Speed: 4.1ms preprocess, 125.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 123.9ms
Speed: 3.8ms preprocess, 123.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 133.9ms
Speed: 4.2ms preprocess, 133.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 135.5ms
Speed: 6.4ms preprocess, 135.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 127.2ms
Speed: 4.6ms preprocess, 127.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 133.6ms
Speed: 4.1ms preprocess, 133.6ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 135.7ms
Speed: 4.3ms preprocess, 135.7ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 136.5ms
Speed: 4.2ms preprocess, 136.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 121.6ms
Speed: 7.1ms preprocess, 121.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 124.0ms
Speed: 4.3ms preprocess, 124.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 124.2ms
Speed: 4.3ms preprocess, 124.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 118.9ms
Speed: 4.2ms preprocess, 118.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 118.1ms
Speed: 4.0ms preprocess, 118.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 2 birds, 121.5ms
Speed: 3.6ms preprocess, 121.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 122.1ms
Speed: 4.0ms preprocess, 122.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 134.5ms
Speed: 3.8ms preprocess, 134.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 116.9ms
Speed: 4.4ms preprocess, 116.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 116.4ms
Speed: 4.1ms preprocess, 116.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 118.4ms
Speed: 4.2ms preprocess, 118.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 124.0ms
Speed: 4.3ms preprocess, 124.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 124.0ms
Speed: 4.8ms preprocess, 124.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 130.5ms
Speed: 5.3ms preprocess, 130.5ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 130.0ms
Speed: 4.7ms preprocess, 130.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 128.1ms
Speed: 6.9ms preprocess, 128.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 132.0ms
Speed: 4.5ms preprocess, 132.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 128.6ms
Speed: 4.7ms preprocess, 128.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 128.1ms
Speed: 4.6ms preprocess, 128.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 120.0ms
Speed: 4.3ms preprocess, 120.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 132.5ms
Speed: 5.4ms preprocess, 132.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 119.6ms
Speed: 3.8ms preprocess, 119.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 117.1ms
Speed: 4.4ms preprocess, 117.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 115.9ms
Speed: 4.0ms preprocess, 115.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 119.5ms
Speed: 4.1ms preprocess, 119.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 129.6ms
Speed: 4.7ms preprocess, 129.6ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 144.4ms
Speed: 4.9ms preprocess, 144.4ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 132.0ms
Speed: 4.1ms preprocess, 132.0ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 134.7ms
Speed: 4.3ms preprocess, 134.7ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 136.1ms
Speed: 4.3ms preprocess, 136.1ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 134.2ms
Speed: 5.0ms preprocess, 134.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 125.6ms
Speed: 4.3ms preprocess, 125.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 131.0ms
Speed: 4.4ms preprocess, 131.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 116.8ms
Speed: 4.1ms preprocess, 116.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 116.1ms
Speed: 4.2ms preprocess, 116.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 115.6ms
Speed: 4.2ms preprocess, 115.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bird, 119.7ms
Speed: 4.2ms preprocess, 119.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 137.7ms
Speed: 4.0ms preprocess, 137.7ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 142.1ms
Speed: 4.4ms preprocess, 142.1ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 131.1ms
Speed: 5.4ms preprocess, 131.1ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 130.6ms
Speed: 4.6ms preprocess, 130.6ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 131.3ms
Speed: 4.7ms preprocess, 131.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 133.4ms
Speed: 4.8ms preprocess, 133.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 121.5ms
Speed: 5.0ms preprocess, 121.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 133.1ms
Speed: 3.8ms preprocess, 133.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 119.1ms
Speed: 4.3ms preprocess, 119.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 146.7ms
Speed: 3.7ms preprocess, 146.7ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 177.1ms
Speed: 7.6ms preprocess, 177.1ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 197.0ms
Speed: 6.2ms preprocess, 197.0ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 205.1ms
Speed: 4.7ms preprocess, 205.1ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 194.7ms
Speed: 5.6ms preprocess, 194.7ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 189.7ms
Speed: 4.7ms preprocess, 189.7ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 188.2ms
Speed: 4.7ms preprocess, 188.2ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 182.9ms
Speed: 4.2ms preprocess, 182.9ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 207.9ms
Speed: 7.1ms preprocess, 207.9ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 180.0ms
Speed: 4.1ms preprocess, 180.0ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 202.9ms
Speed: 7.6ms preprocess, 202.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 135.1ms
Speed: 4.3ms preprocess, 135.1ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 165.2ms
Speed: 4.9ms preprocess, 165.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 131.1ms
Speed: 4.6ms preprocess, 131.1ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 136.6ms
Speed: 4.6ms preprocess, 136.6ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 130.6ms
Speed: 4.6ms preprocess, 130.6ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 134.0ms
Speed: 4.7ms preprocess, 134.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 138.1ms
Speed: 4.9ms preprocess, 138.1ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 2 birds, 151.5ms
Speed: 9.0ms preprocess, 151.5ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 137.9ms
Speed: 4.7ms preprocess, 137.9ms inference, 2.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 144.2ms
Speed: 7.0ms preprocess, 144.2ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 122.9ms
Speed: 4.4ms preprocess, 122.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 122.6ms
Speed: 6.2ms preprocess, 122.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 122.5ms
Speed: 4.3ms preprocess, 122.5ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 132.7ms
Speed: 5.8ms preprocess, 132.7ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 118.6ms
Speed: 4.4ms preprocess, 118.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 124.9ms
Speed: 5.8ms preprocess, 124.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 140.2ms
Speed: 5.1ms preprocess, 140.2ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 135.9ms
Speed: 5.2ms preprocess, 135.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 135.0ms
Speed: 4.6ms preprocess, 135.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 143.6ms
Speed: 4.5ms preprocess, 143.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 137.4ms
Speed: 4.1ms preprocess, 137.4ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 130.5ms
Speed: 4.8ms preprocess, 130.5ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 128.9ms
Speed: 4.8ms preprocess, 128.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 134.9ms
Speed: 5.1ms preprocess, 134.9ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 136.1ms
Speed: 4.7ms preprocess, 136.1ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 132.8ms
Speed: 4.6ms preprocess, 132.8ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 132.5ms
Speed: 4.9ms preprocess, 132.5ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 125.0ms
Speed: 4.7ms preprocess, 125.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 120.5ms
Speed: 4.9ms preprocess, 120.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 114.7ms
Speed: 4.5ms preprocess, 114.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 117.5ms
Speed: 4.2ms preprocess, 117.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 127.1ms
Speed: 6.3ms preprocess, 127.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 122.2ms
Speed: 4.0ms preprocess, 122.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 118.2ms
Speed: 3.9ms preprocess, 118.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 3 birds, 119.1ms
Speed: 3.8ms preprocess, 119.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 119.0ms
Speed: 3.7ms preprocess, 119.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 118.0ms
Speed: 4.4ms preprocess, 118.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 133.5ms
Speed: 4.2ms preprocess, 133.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 122.7ms
Speed: 4.2ms preprocess, 122.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 118.0ms
Speed: 4.4ms preprocess, 118.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 birds, 118.5ms
Speed: 4.3ms preprocess, 118.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 birds, 121.9ms
Speed: 3.8ms preprocess, 121.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 birds, 114.2ms

In [42]:
run_full_tracking_pipeline(model, "/content/videos /birds_beach_856799-hd_1920_1080_25fps.mp4", "/content/ground truth/gt_birds_beach.json", "birds_beach_results.json")

🔍 Running detection + tracking...

0: 384x640 2 Birds, 129.9ms
Speed: 4.0ms preprocess, 129.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 138.5ms
Speed: 4.3ms preprocess, 138.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 114.9ms
Speed: 4.3ms preprocess, 114.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 123.0ms
Speed: 4.3ms preprocess, 123.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 115.5ms
Speed: 4.4ms preprocess, 115.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 Bird, 118.5ms
Speed: 4.3ms preprocess, 118.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 116.5ms
Speed: 4.2ms preprocess, 116.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 122.0ms
Speed: 4.1ms preprocess, 122.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 131.0ms
Speed: 4.1ms preprocess, 131.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 119.7ms
Speed: 4.1ms preprocess, 119.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 122.0ms
Speed: 4.0ms preprocess, 122.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 135.6ms
Speed: 4.4ms preprocess, 135.6ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 133.7ms
Speed: 4.9ms preprocess, 133.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 136.2ms
Speed: 4.7ms preprocess, 136.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 153.2ms
Speed: 4.9ms preprocess, 153.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 142.3ms
Speed: 4.5ms preprocess, 142.3ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 Bird, 128.8ms
Speed: 5.1ms preprocess, 128.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 123.9ms
Speed: 4.5ms preprocess, 123.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 118.1ms
Speed: 4.7ms preprocess, 118.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 118.3ms
Speed: 4.6ms preprocess, 118.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 126.3ms
Speed: 4.4ms preprocess, 126.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 116.1ms
Speed: 4.5ms preprocess, 116.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 115.7ms
Speed: 4.4ms preprocess, 115.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 160.4ms
Speed: 4.9ms preprocess, 160.4ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 199.4ms
Speed: 6.4ms preprocess, 199.4ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 224.6ms
Speed: 6.1ms preprocess, 224.6ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 187.9ms
Speed: 6.4ms preprocess, 187.9ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 195.9ms
Speed: 4.7ms preprocess, 195.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 189.0ms
Speed: 4.9ms preprocess, 189.0ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 198.4ms
Speed: 7.2ms preprocess, 198.4ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 208.6ms
Speed: 7.8ms preprocess, 208.6ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 228.4ms
Speed: 4.5ms preprocess, 228.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 210.2ms
Speed: 4.8ms preprocess, 210.2ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 241.8ms
Speed: 4.9ms preprocess, 241.8ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 127.3ms
Speed: 4.7ms preprocess, 127.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 127.6ms
Speed: 4.9ms preprocess, 127.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 128.0ms
Speed: 5.0ms preprocess, 128.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 130.9ms
Speed: 4.8ms preprocess, 130.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 127.3ms
Speed: 4.9ms preprocess, 127.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 146.4ms
Speed: 4.6ms preprocess, 146.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 133.0ms
Speed: 4.5ms preprocess, 133.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 125.2ms
Speed: 4.7ms preprocess, 125.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 126.8ms
Speed: 4.5ms preprocess, 126.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 129.6ms
Speed: 4.5ms preprocess, 129.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 130.4ms
Speed: 4.6ms preprocess, 130.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 146.7ms
Speed: 4.7ms preprocess, 146.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 131.5ms
Speed: 4.8ms preprocess, 131.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 116.0ms
Speed: 4.5ms preprocess, 116.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 120.8ms
Speed: 4.4ms preprocess, 120.8ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 117.1ms
Speed: 4.2ms preprocess, 117.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 113.8ms
Speed: 3.9ms preprocess, 113.8ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 120.7ms
Speed: 4.3ms preprocess, 120.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.1ms
Speed: 8.3ms preprocess, 115.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 131.8ms
Speed: 4.5ms preprocess, 131.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 131.6ms
Speed: 5.5ms preprocess, 131.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 133.4ms
Speed: 4.9ms preprocess, 133.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 126.8ms
Speed: 4.9ms preprocess, 126.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 125.8ms
Speed: 4.9ms preprocess, 125.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 142.7ms
Speed: 6.2ms preprocess, 142.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 125.8ms
Speed: 5.1ms preprocess, 125.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 130.1ms
Speed: 4.4ms preprocess, 130.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 131.5ms
Speed: 4.4ms preprocess, 131.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 126.6ms
Speed: 4.6ms preprocess, 126.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 127.8ms
Speed: 4.8ms preprocess, 127.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 145.3ms
Speed: 5.4ms preprocess, 145.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 132.6ms
Speed: 4.9ms preprocess, 132.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 128.0ms
Speed: 5.0ms preprocess, 128.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 131.5ms
Speed: 5.2ms preprocess, 131.5ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 129.9ms
Speed: 4.6ms preprocess, 129.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 128.3ms
Speed: 4.4ms preprocess, 128.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 151.6ms
Speed: 4.6ms preprocess, 151.6ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 132.1ms
Speed: 4.7ms preprocess, 132.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 128.8ms
Speed: 5.0ms preprocess, 128.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 132.5ms
Speed: 4.5ms preprocess, 132.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 129.4ms
Speed: 4.9ms preprocess, 129.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 133.2ms
Speed: 4.7ms preprocess, 133.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 139.4ms
Speed: 5.5ms preprocess, 139.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 117.4ms
Speed: 4.5ms preprocess, 117.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 119.1ms
Speed: 4.4ms preprocess, 119.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.7ms
Speed: 4.4ms preprocess, 115.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 115.8ms
Speed: 4.3ms preprocess, 115.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 115.7ms
Speed: 4.1ms preprocess, 115.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 135.0ms
Speed: 4.4ms preprocess, 135.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 127.7ms
Speed: 4.3ms preprocess, 127.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 132.8ms
Speed: 4.5ms preprocess, 132.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 129.2ms
Speed: 4.3ms preprocess, 129.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 132.9ms
Speed: 4.7ms preprocess, 132.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 129.5ms
Speed: 4.7ms preprocess, 129.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 144.9ms
Speed: 5.0ms preprocess, 144.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 130.4ms
Speed: 4.6ms preprocess, 130.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 141.5ms
Speed: 4.5ms preprocess, 141.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 134.3ms
Speed: 4.6ms preprocess, 134.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 149.3ms
Speed: 4.8ms preprocess, 149.3ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 212.7ms
Speed: 4.2ms preprocess, 212.7ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 200.2ms
Speed: 4.7ms preprocess, 200.2ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 185.9ms
Speed: 6.9ms preprocess, 185.9ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 197.7ms
Speed: 9.4ms preprocess, 197.7ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 187.6ms
Speed: 7.4ms preprocess, 187.6ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 190.3ms
Speed: 11.3ms preprocess, 190.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 191.3ms
Speed: 13.1ms preprocess, 191.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 201.2ms
Speed: 10.2ms preprocess, 201.2ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 210.6ms
Speed: 7.5ms preprocess, 210.6ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 227.4ms
Speed: 4.5ms preprocess, 227.4ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 Bird, 124.6ms
Speed: 5.2ms preprocess, 124.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 124.9ms
Speed: 4.9ms preprocess, 124.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 122.0ms
Speed: 4.1ms preprocess, 122.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 124.3ms
Speed: 4.1ms preprocess, 124.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 117.5ms
Speed: 4.2ms preprocess, 117.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 132.4ms
Speed: 4.2ms preprocess, 132.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 118.8ms
Speed: 4.4ms preprocess, 118.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 121.5ms
Speed: 4.5ms preprocess, 121.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 118.5ms
Speed: 4.9ms preprocess, 118.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 120.2ms
Speed: 4.4ms preprocess, 120.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 120.4ms
Speed: 3.9ms preprocess, 120.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 149.4ms
Speed: 6.6ms preprocess, 149.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 131.6ms
Speed: 4.4ms preprocess, 131.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 136.4ms
Speed: 4.4ms preprocess, 136.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 127.0ms
Speed: 5.0ms preprocess, 127.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 132.0ms
Speed: 5.2ms preprocess, 132.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 128.9ms
Speed: 5.2ms preprocess, 128.9ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 145.5ms
Speed: 4.2ms preprocess, 145.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 128.1ms
Speed: 4.6ms preprocess, 128.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 125.1ms
Speed: 4.9ms preprocess, 125.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 129.9ms
Speed: 4.5ms preprocess, 129.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 135.2ms
Speed: 4.6ms preprocess, 135.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 133.1ms
Speed: 4.6ms preprocess, 133.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 139.1ms
Speed: 9.2ms preprocess, 139.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 127.5ms
Speed: 4.6ms preprocess, 127.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 127.3ms
Speed: 4.6ms preprocess, 127.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 131.0ms
Speed: 4.7ms preprocess, 131.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 132.2ms
Speed: 4.8ms preprocess, 132.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 132.3ms
Speed: 4.8ms preprocess, 132.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 142.1ms
Speed: 4.3ms preprocess, 142.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 130.2ms
Speed: 4.9ms preprocess, 130.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 128.1ms
Speed: 4.4ms preprocess, 128.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 132.1ms
Speed: 4.8ms preprocess, 132.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 126.9ms
Speed: 4.9ms preprocess, 126.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 130.4ms
Speed: 4.5ms preprocess, 130.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 128.6ms
Speed: 4.1ms preprocess, 128.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 116.5ms
Speed: 4.4ms preprocess, 116.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 143.7ms
Speed: 4.5ms preprocess, 143.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 116.1ms
Speed: 4.3ms preprocess, 116.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 117.6ms
Speed: 4.2ms preprocess, 117.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 121.2ms
Speed: 4.6ms preprocess, 121.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 125.0ms
Speed: 4.6ms preprocess, 125.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 170.7ms
Speed: 6.2ms preprocess, 170.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 139.3ms
Speed: 5.0ms preprocess, 139.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 140.7ms
Speed: 5.0ms preprocess, 140.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 127.2ms
Speed: 6.7ms preprocess, 127.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 131.7ms
Speed: 4.6ms preprocess, 131.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 128.6ms
Speed: 4.5ms preprocess, 128.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 135.1ms
Speed: 5.6ms preprocess, 135.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 128.7ms
Speed: 4.6ms preprocess, 128.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 130.6ms
Speed: 4.9ms preprocess, 130.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 Birds, 126.3ms
Speed: 4.9ms preprocess, 126.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 122.2ms
Speed: 5.0ms preprocess, 122.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 120.8ms
Speed: 3.9ms preprocess, 120.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)


In [43]:
run_full_tracking_pipeline(model, "/content/videos /similar_birds_8824697-uhd_3840_2160_30fps.mp4", "/content/ground truth/gt_similar_birds.json", "similar_birds_results.json")

🔍 Running detection + tracking...

0: 384x640 5 Birds, 153.9ms
Speed: 10.1ms preprocess, 153.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.9ms
Speed: 5.3ms preprocess, 131.9ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 143.5ms
Speed: 6.7ms preprocess, 143.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 146.9ms
Speed: 5.4ms preprocess, 146.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 173.3ms
Speed: 4.9ms preprocess, 173.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 151.2ms
Speed: 5.6ms preprocess, 151.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 145.4ms
Speed: 6.3ms preprocess, 145.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 157.6ms
Speed: 5.5ms preprocess, 157.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 171.5ms
Speed: 5.3ms preprocess, 171.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 153.7ms
Speed: 5.7ms preprocess, 153.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 152.5ms
Speed: 5.5ms preprocess, 152.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 149.7ms
Speed: 6.5ms preprocess, 149.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 178.5ms
Speed: 5.3ms preprocess, 178.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 160.1ms
Speed: 6.1ms preprocess, 160.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 151.7ms
Speed: 6.8ms preprocess, 151.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 156.8ms
Speed: 6.9ms preprocess, 156.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 160.1ms
Speed: 12.4ms preprocess, 160.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 131.3ms
Speed: 6.0ms preprocess, 131.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 139.1ms
Speed: 4.2ms preprocess, 139.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 128.5ms
Speed: 4.4ms preprocess, 128.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 139.7ms
Speed: 4.5ms preprocess, 139.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 148.5ms
Speed: 4.5ms preprocess, 148.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 157.8ms
Speed: 5.5ms preprocess, 157.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 152.4ms
Speed: 5.4ms preprocess, 152.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 162.1ms
Speed: 5.3ms preprocess, 162.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 136.8ms
Speed: 4.5ms preprocess, 136.8ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 141.0ms
Speed: 4.2ms preprocess, 141.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.4ms
Speed: 4.5ms preprocess, 131.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 134.8ms
Speed: 4.8ms preprocess, 134.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 143.7ms
Speed: 6.0ms preprocess, 143.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 158.7ms
Speed: 5.6ms preprocess, 158.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 155.1ms
Speed: 5.3ms preprocess, 155.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 149.1ms
Speed: 7.0ms preprocess, 149.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 168.9ms
Speed: 6.8ms preprocess, 168.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 195.5ms
Speed: 8.5ms preprocess, 195.5ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 204.3ms
Speed: 4.6ms preprocess, 204.3ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 237.0ms
Speed: 4.9ms preprocess, 237.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 235.5ms
Speed: 13.2ms preprocess, 235.5ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 255.6ms
Speed: 6.9ms preprocess, 255.6ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 207.2ms
Speed: 4.8ms preprocess, 207.2ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 221.7ms
Speed: 6.6ms preprocess, 221.7ms inference, 2.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 132.4ms
Speed: 4.7ms preprocess, 132.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 137.5ms
Speed: 4.5ms preprocess, 137.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 135.7ms
Speed: 4.4ms preprocess, 135.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 131.4ms
Speed: 4.6ms preprocess, 131.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 133.7ms
Speed: 4.8ms preprocess, 133.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 132.5ms
Speed: 4.5ms preprocess, 132.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.8ms
Speed: 4.6ms preprocess, 131.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 127.8ms
Speed: 4.4ms preprocess, 127.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 135.1ms
Speed: 5.5ms preprocess, 135.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 142.1ms
Speed: 4.6ms preprocess, 142.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 144.8ms
Speed: 4.8ms preprocess, 144.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 124.1ms
Speed: 4.6ms preprocess, 124.1ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 137.3ms
Speed: 4.8ms preprocess, 137.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 132.0ms
Speed: 4.5ms preprocess, 132.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 139.6ms
Speed: 4.3ms preprocess, 139.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 148.9ms
Speed: 7.7ms preprocess, 148.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 151.3ms
Speed: 5.0ms preprocess, 151.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 Birds, 153.8ms
Speed: 5.8ms preprocess, 153.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 149.9ms
Speed: 5.0ms preprocess, 149.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 152.3ms
Speed: 5.0ms preprocess, 152.3ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 158.4ms
Speed: 5.1ms preprocess, 158.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 151.8ms
Speed: 5.2ms preprocess, 151.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 154.4ms
Speed: 5.0ms preprocess, 154.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 153.7ms
Speed: 4.9ms preprocess, 153.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 159.6ms
Speed: 6.4ms preprocess, 159.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 159.0ms
Speed: 5.6ms preprocess, 159.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 181.6ms
Speed: 5.0ms preprocess, 181.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 155.2ms
Speed: 5.6ms preprocess, 155.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 155.1ms
Speed: 5.2ms preprocess, 155.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 152.9ms
Speed: 5.2ms preprocess, 152.9ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 167.9ms
Speed: 5.3ms preprocess, 167.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 153.5ms
Speed: 5.3ms preprocess, 153.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 158.5ms
Speed: 5.2ms preprocess, 158.5ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 156.8ms
Speed: 5.5ms preprocess, 156.8ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 153.1ms
Speed: 4.5ms preprocess, 153.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 136.5ms
Speed: 4.4ms preprocess, 136.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 135.2ms
Speed: 4.8ms preprocess, 135.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 131.3ms
Speed: 4.6ms preprocess, 131.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 153.2ms
Speed: 5.4ms preprocess, 153.2ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 163.9ms
Speed: 6.3ms preprocess, 163.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 239.4ms
Speed: 5.3ms preprocess, 239.4ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 232.2ms
Speed: 8.3ms preprocess, 232.2ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 237.9ms
Speed: 11.0ms preprocess, 237.9ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 234.3ms
Speed: 5.4ms preprocess, 234.3ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 249.1ms
Speed: 11.0ms preprocess, 249.1ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 236.8ms
Speed: 6.8ms preprocess, 236.8ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 304.4ms
Speed: 5.2ms preprocess, 304.4ms inference, 3.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 161.7ms
Speed: 5.4ms preprocess, 161.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 150.9ms
Speed: 5.5ms preprocess, 150.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 143.5ms
Speed: 5.0ms preprocess, 143.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 136.9ms
Speed: 7.0ms preprocess, 136.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 156.6ms
Speed: 4.8ms preprocess, 156.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 134.3ms
Speed: 4.7ms preprocess, 134.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 136.5ms
Speed: 4.6ms preprocess, 136.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 165.1ms
Speed: 5.3ms preprocess, 165.1ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 167.6ms
Speed: 5.5ms preprocess, 167.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 155.9ms
Speed: 5.3ms preprocess, 155.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 157.3ms
Speed: 5.4ms preprocess, 157.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 161.6ms
Speed: 5.7ms preprocess, 161.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 178.8ms
Speed: 7.7ms preprocess, 178.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 152.1ms
Speed: 5.4ms preprocess, 152.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 157.1ms
Speed: 5.2ms preprocess, 157.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 158.5ms
Speed: 5.2ms preprocess, 158.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 179.7ms
Speed: 5.1ms preprocess, 179.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 159.4ms
Speed: 5.4ms preprocess, 159.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 140.5ms
Speed: 4.8ms preprocess, 140.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 132.4ms
Speed: 4.7ms preprocess, 132.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 145.1ms
Speed: 4.6ms preprocess, 145.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 133.2ms
Speed: 4.6ms preprocess, 133.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 155.3ms
Speed: 4.4ms preprocess, 155.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 155.3ms
Speed: 6.4ms preprocess, 155.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 169.3ms
Speed: 5.4ms preprocess, 169.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 155.8ms
Speed: 4.9ms preprocess, 155.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 148.2ms
Speed: 5.1ms preprocess, 148.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 152.0ms
Speed: 6.9ms preprocess, 152.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 156.5ms
Speed: 6.9ms preprocess, 156.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 153.4ms
Speed: 5.2ms preprocess, 153.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 154.2ms
Speed: 5.2ms preprocess, 154.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 154.6ms
Speed: 6.8ms preprocess, 154.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 169.5ms
Speed: 6.9ms preprocess, 169.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 157.9ms
Speed: 5.4ms preprocess, 157.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 138.7ms
Speed: 5.7ms preprocess, 138.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 134.5ms
Speed: 4.2ms preprocess, 134.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 143.4ms
Speed: 4.5ms preprocess, 143.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 134.9ms
Speed: 5.4ms preprocess, 134.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 156.6ms
Speed: 5.3ms preprocess, 156.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 215.9ms
Speed: 5.1ms preprocess, 215.9ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 264.8ms
Speed: 5.0ms preprocess, 264.8ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 254.1ms
Speed: 6.5ms preprocess, 254.1ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 241.4ms
Speed: 5.1ms preprocess, 241.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 256.0ms
Speed: 5.4ms preprocess, 256.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 270.3ms
Speed: 13.2ms preprocess, 270.3ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 289.2ms
Speed: 5.3ms preprocess, 289.2ms inference, 2.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 136.5ms
Speed: 4.8ms preprocess, 136.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 139.4ms
Speed: 4.7ms preprocess, 139.4ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 134.4ms
Speed: 4.5ms preprocess, 134.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 145.3ms
Speed: 4.7ms preprocess, 145.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 133.2ms
Speed: 5.0ms preprocess, 133.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 137.2ms
Speed: 4.8ms preprocess, 137.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 136.5ms
Speed: 4.6ms preprocess, 136.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 130.7ms
Speed: 4.7ms preprocess, 130.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 150.2ms
Speed: 4.6ms preprocess, 150.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 146.9ms
Speed: 5.2ms preprocess, 146.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 153.9ms
Speed: 5.3ms preprocess, 153.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 152.7ms
Speed: 5.2ms preprocess, 152.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 165.2ms
Speed: 5.2ms preprocess, 165.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 145.0ms
Speed: 5.8ms preprocess, 145.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 153.2ms
Speed: 5.6ms preprocess, 153.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 166.7ms
Speed: 5.3ms preprocess, 166.7ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 143.9ms
Speed: 6.1ms preprocess, 143.9ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 132.3ms
Speed: 4.6ms preprocess, 132.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 133.6ms
Speed: 4.7ms preprocess, 133.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 132.0ms
Speed: 4.6ms preprocess, 132.0ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 145.0ms
Speed: 6.7ms preprocess, 145.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 149.7ms
Speed: 5.4ms preprocess, 149.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 150.1ms
Speed: 5.2ms preprocess, 150.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)


In [44]:

run_full_tracking_pipeline(model, "/content/videos /desert_birds_4438487-uhd_3840_2160_24fps.mp4", "/content/ground truth/gt_desert_birds.json", "desert_birds_results.json")

🔍 Running detection + tracking...

0: 384x640 6 Birds, 229.4ms
Speed: 8.3ms preprocess, 229.4ms inference, 6.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 265.5ms
Speed: 7.3ms preprocess, 265.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 258.1ms
Speed: 13.4ms preprocess, 258.1ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 228.6ms
Speed: 5.6ms preprocess, 228.6ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 228.6ms
Speed: 4.8ms preprocess, 228.6ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 205.5ms
Speed: 5.9ms preprocess, 205.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 138.2ms
Speed: 5.1ms preprocess, 138.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 147.3ms
Speed: 5.3ms preprocess, 147.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 159.6ms
Speed: 5.8ms preprocess, 159.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 157.2ms
Speed: 5.3ms preprocess, 157.2ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 154.4ms
Speed: 6.2ms preprocess, 154.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 161.3ms
Speed: 5.4ms preprocess, 161.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 157.1ms
Speed: 5.9ms preprocess, 157.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 166.8ms
Speed: 5.3ms preprocess, 166.8ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 160.0ms
Speed: 5.7ms preprocess, 160.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 156.8ms
Speed: 5.6ms preprocess, 156.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 155.6ms
Speed: 5.4ms preprocess, 155.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 174.5ms
Speed: 5.0ms preprocess, 174.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 156.4ms
Speed: 5.9ms preprocess, 156.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 138.6ms
Speed: 5.2ms preprocess, 138.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 135.9ms
Speed: 4.7ms preprocess, 135.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 145.9ms
Speed: 4.6ms preprocess, 145.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 133.6ms
Speed: 5.1ms preprocess, 133.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 155.2ms
Speed: 4.8ms preprocess, 155.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 153.8ms
Speed: 5.2ms preprocess, 153.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 158.0ms
Speed: 5.3ms preprocess, 158.0ms inference, 2.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 7 Birds, 159.6ms
Speed: 5.4ms preprocess, 159.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 152.6ms
Speed: 5.6ms preprocess, 152.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 8 Birds, 147.0ms
Speed: 5.6ms preprocess, 147.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 166.9ms
Speed: 5.2ms preprocess, 166.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 153.0ms
Speed: 5.2ms preprocess, 153.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 153.7ms
Speed: 5.5ms preprocess, 153.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 158.7ms
Speed: 5.7ms preprocess, 158.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 168.7ms
Speed: 5.0ms preprocess, 168.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 154.8ms
Speed: 5.1ms preprocess, 154.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 158.5ms
Speed: 5.3ms preprocess, 158.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 153.8ms
Speed: 6.1ms preprocess, 153.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 177.8ms
Speed: 5.2ms preprocess, 177.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 157.9ms
Speed: 5.1ms preprocess, 157.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 154.2ms
Speed: 4.9ms preprocess, 154.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 157.6ms
Speed: 5.2ms preprocess, 157.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 171.9ms
Speed: 5.0ms preprocess, 171.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 155.3ms
Speed: 5.3ms preprocess, 155.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 212.4ms
Speed: 8.4ms preprocess, 212.4ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 268.4ms
Speed: 4.7ms preprocess, 268.4ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 227.5ms
Speed: 12.4ms preprocess, 227.5ms inference, 3.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 220.8ms
Speed: 11.1ms preprocess, 220.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 221.0ms
Speed: 4.4ms preprocess, 221.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 208.5ms
Speed: 5.6ms preprocess, 208.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 243.6ms
Speed: 5.7ms preprocess, 243.6ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 145.6ms
Speed: 4.7ms preprocess, 145.6ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 168.4ms
Speed: 5.1ms preprocess, 168.4ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 155.3ms
Speed: 5.2ms preprocess, 155.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 153.8ms
Speed: 5.3ms preprocess, 153.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 157.0ms
Speed: 5.0ms preprocess, 157.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 159.1ms
Speed: 5.7ms preprocess, 159.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 156.6ms
Speed: 5.5ms preprocess, 156.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 171.5ms
Speed: 4.9ms preprocess, 171.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 137.4ms
Speed: 5.1ms preprocess, 137.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 136.4ms
Speed: 4.9ms preprocess, 136.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 146.1ms
Speed: 4.4ms preprocess, 146.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 145.2ms
Speed: 4.9ms preprocess, 145.2ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 167.0ms
Speed: 6.4ms preprocess, 167.0ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 153.1ms
Speed: 5.7ms preprocess, 153.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 157.6ms
Speed: 5.6ms preprocess, 157.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 172.3ms
Speed: 5.8ms preprocess, 172.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 138.6ms
Speed: 5.2ms preprocess, 138.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 136.1ms
Speed: 4.5ms preprocess, 136.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 135.7ms
Speed: 4.5ms preprocess, 135.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 133.4ms
Speed: 4.6ms preprocess, 133.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 149.5ms
Speed: 8.9ms preprocess, 149.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 149.4ms
Speed: 6.0ms preprocess, 149.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 Birds, 152.2ms
Speed: 5.9ms preprocess, 152.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 153.1ms
Speed: 5.5ms preprocess, 153.1ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 149.8ms
Speed: 5.2ms preprocess, 149.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 152.6ms
Speed: 5.4ms preprocess, 152.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 155.2ms
Speed: 5.5ms preprocess, 155.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 158.4ms
Speed: 5.5ms preprocess, 158.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 158.1ms
Speed: 5.6ms preprocess, 158.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 159.0ms
Speed: 5.8ms preprocess, 159.0ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 163.6ms
Speed: 5.5ms preprocess, 163.6ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 171.4ms
Speed: 5.6ms preprocess, 171.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 154.2ms
Speed: 5.7ms preprocess, 154.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 159.1ms
Speed: 5.2ms preprocess, 159.1ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 155.2ms
Speed: 6.6ms preprocess, 155.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 164.9ms
Speed: 5.4ms preprocess, 164.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 6 Birds, 153.4ms
Speed: 5.2ms preprocess, 153.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 157.2ms
Speed: 5.5ms preprocess, 157.2ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 229.9ms
Speed: 9.3ms preprocess, 229.9ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 246.2ms
Speed: 10.0ms preprocess, 246.2ms inference, 2.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 257.4ms
Speed: 5.1ms preprocess, 257.4ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 262.0ms
Speed: 7.6ms preprocess, 262.0ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 5 Birds, 251.6ms
Speed: 8.0ms preprocess, 251.6ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 223.9ms
Speed: 11.3ms preprocess, 223.9ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 289.1ms
Speed: 4.8ms preprocess, 289.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 160.6ms
Speed: 4.9ms preprocess, 160.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 154.1ms
Speed: 5.9ms preprocess, 154.1ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 148.2ms
Speed: 5.1ms preprocess, 148.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 153.1ms
Speed: 5.1ms preprocess, 153.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 155.8ms
Speed: 5.3ms preprocess, 155.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 151.7ms
Speed: 5.2ms preprocess, 151.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 132.2ms
Speed: 4.6ms preprocess, 132.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 129.9ms
Speed: 4.4ms preprocess, 129.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 139.2ms
Speed: 4.4ms preprocess, 139.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 140.3ms
Speed: 4.6ms preprocess, 140.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 153.8ms
Speed: 5.4ms preprocess, 153.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 178.6ms
Speed: 5.0ms preprocess, 178.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 152.8ms
Speed: 5.6ms preprocess, 152.8ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 155.3ms
Speed: 5.1ms preprocess, 155.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 140.5ms
Speed: 4.8ms preprocess, 140.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 155.7ms
Speed: 4.6ms preprocess, 155.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 134.2ms
Speed: 4.5ms preprocess, 134.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 136.3ms
Speed: 4.6ms preprocess, 136.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 131.7ms
Speed: 4.5ms preprocess, 131.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 147.8ms
Speed: 4.4ms preprocess, 147.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 135.6ms
Speed: 5.0ms preprocess, 135.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 138.0ms
Speed: 4.6ms preprocess, 138.0ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 140.6ms
Speed: 4.8ms preprocess, 140.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 150.6ms
Speed: 5.3ms preprocess, 150.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 166.7ms
Speed: 5.1ms preprocess, 166.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 156.1ms
Speed: 5.2ms preprocess, 156.1ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 156.8ms
Speed: 5.3ms preprocess, 156.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 168.4ms
Speed: 5.3ms preprocess, 168.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 160.2ms
Speed: 5.2ms preprocess, 160.2ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 155.1ms
Speed: 5.4ms preprocess, 155.1ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 153.8ms
Speed: 5.3ms preprocess, 153.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 171.9ms
Speed: 5.4ms preprocess, 171.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 156.8ms
Speed: 5.4ms preprocess, 156.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 150.6ms
Speed: 5.4ms preprocess, 150.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 134.6ms
Speed: 4.7ms preprocess, 134.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 154.6ms
Speed: 4.5ms preprocess, 154.6ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 135.0ms
Speed: 4.5ms preprocess, 135.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 133.1ms
Speed: 4.6ms preprocess, 133.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 161.2ms
Speed: 6.7ms preprocess, 161.2ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 269.4ms
Speed: 5.2ms preprocess, 269.4ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 242.2ms
Speed: 5.4ms preprocess, 242.2ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 244.0ms
Speed: 12.3ms preprocess, 244.0ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 206.3ms
Speed: 5.4ms preprocess, 206.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 237.3ms
Speed: 5.3ms preprocess, 237.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 267.1ms
Speed: 9.8ms preprocess, 267.1ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 260.8ms
Speed: 9.6ms preprocess, 260.8ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 156.6ms
Speed: 5.1ms preprocess, 156.6ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 158.4ms
Speed: 5.6ms preprocess, 158.4ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 152.7ms
Speed: 5.7ms preprocess, 152.7ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 150.7ms
Speed: 5.2ms preprocess, 150.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 157.6ms
Speed: 5.5ms preprocess, 157.6ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 152.7ms
Speed: 5.2ms preprocess, 152.7ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 149.2ms
Speed: 5.2ms preprocess, 149.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 137.6ms
Speed: 4.8ms preprocess, 137.6ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 138.1ms
Speed: 4.8ms preprocess, 138.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 134.3ms
Speed: 4.8ms preprocess, 134.3ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 167.1ms
Speed: 4.6ms preprocess, 167.1ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 137.2ms
Speed: 4.5ms preprocess, 137.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 131.4ms
Speed: 4.5ms preprocess, 131.4ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 137.8ms
Speed: 5.2ms preprocess, 137.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 148.5ms
Speed: 4.6ms preprocess, 148.5ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 Birds, 137.9ms
Speed: 4.4ms preprocess, 137.9ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)
